#==========
#
# Variables defined by this module:
#   IECORE_FOUND
#   IECORE_INCLUDE_DIRS
#   IECORE_LIBRARIES
#
# Usage: 
#   FIND_PACKAGE( IECore )
#   FIND_PACKAGE( IECore REQUIRED )
#
#==========

FIND_PATH(IECORE_INCLUDE_DIR NAMES IECore/IECore.h)
FIND_LIBRARY( IECORE_LIBRARY IECore)

# did we find everything?
INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( IECORE DEFAULT_MSG IECORE_LIBRARY IECORE_INCLUDE_DIR)

# Copy the results to the output variables.
IF(IECORE_FOUND)
  SET(IECORE_LIBRARIES ${IECORE_LIBRARY})
  SET(IECORE_INCLUDE_DIRS ${IECORE_INCLUDE_DIR})
ELSE(IECORE_FOUND)
  SET(IECORE_LIBRARIES)
  SET(IECORE_INCLUDE_DIRS)
ENDIF(IECORE_FOUND)

MARK_AS_ADVANCED( IECORE_INCLUDE_DIR IECORE_LIBRARY)

