#==========
#
# Variables defined by this module:
#   IECORERI_FOUND    
#   IECORERI_INCLUDE_DIRS
#   IECORERI_LIBRARIES
#
# Usage: 
#   FIND_PACKAGE( IECoreRI )
#   FIND_PACKAGE( IECoreRI REQUIRED )
#
#==========

FIND_PATH( IECORERI_INCLUDE_DIR NAMES IECoreRI/RIBWriter.h)
FIND_LIBRARY( IECORERI_LIBRARY IECoreRI)

# did we find everything?
INCLUDE( FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS( IECORERI DEFAULT_MSG IECORERI_LIBRARY IECORERI_INCLUDE_DIR)

# Copy the results to the output variables.
IF(IECORERI_FOUND)
  SET(IECORERI_LIBRARIES ${IECORERI_LIBRARY})
  SET(IECORERI_INCLUDE_DIRS ${IECORERI_INCLUDE_DIR})
ELSE(IECORERI_FOUND)
  SET(IECORERI_LIBRARIES)
  SET(IECORERI_INCLUDE_DIRS)
ENDIF(IECORERI_FOUND)

MARK_AS_ADVANCED( IECORERI_INCLUDE_DIR IECORERI_LIBRARY)
