# - Find ImageStack
# Find IMAGESTACK headers and libraries.
#
#  IMAGESTACK_INCLUDE_DIRS - where to find ImageStack includes.
#  IMAGESTACK_LIBRARIES    - List of libraries when using ImageStack.
#  IMAGESTACK_FOUND        - True if ImageStack found.

# Look for the header file.
FIND_PATH(IMAGESTACK_INCLUDE_DIR NAMES ImageStack/ImageStack.h)

# Look for the library.
FIND_LIBRARY(IMAGESTACK_LIBRARY NAMES ImageStack)

# handle the QUIETLY and REQUIRED arguments and set IMAGESTACK_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(IMAGESTACK DEFAULT_MSG IMAGESTACK_LIBRARY IMAGESTACK_INCLUDE_DIR)

# Copy the results to the output variables.
IF(IMAGESTACK_FOUND)
  SET(IMAGESTACK_LIBRARIES ${IMAGESTACK_LIBRARY})
  SET(IMAGESTACK_INCLUDE_DIRS ${IMAGESTACK_INCLUDE_DIR})
ELSE(IMAGESTACK_FOUND)
  SET(IMAGESTACK_LIBRARIES)
  SET(IMAGESTACK_INCLUDE_DIRS)
ENDIF(IMAGESTACK_FOUND)

MARK_AS_ADVANCED(IMAGESTACK_INCLUDE_DIR IMAGESTACK_LIBRARY)
