# - Find OpenCV
# Find the OpenCV headers and libraries.
#
#  OPENCV_INCLUDE_DIRS - where to find OpenCV uncludes.
#  OPENCV_LIBRARIES    - List of libraries when using OpenCV.
#  OPENCV_FOUND        - True if OpenCV found.

# Look for the header file.
FIND_PATH( OPENCV_INCLUDE_DIR NAMES opencv/cv.h)

# Look for the libraries.
FIND_LIBRARY( OPENCV_LIBRARY NAMES cv)
FIND_LIBRARY( OPENCV_AUX_LIBRARY NAMES cvaux)
FIND_LIBRARY( OPENCV_CXCORE_LIBRARY NAMES cxcore)
FIND_LIBRARY( OPENCV_ML_LIBRARY NAMES ml)

INCLUDE( FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS( OPENCV DEFAULT_MSG OPENCV_LIBRARY OPENCV_AUX_LIBRARY OPENCV_CXCORE_LIBRARY OPENCV_ML_LIBRARY OPENCV_INCLUDE_DIR)

# Copy the results to the output variables.
IF( OPENCV_FOUND)
  SET( OPENCV_LIBRARIES ${OPENCV_LIBRARY} ${OPENCV_AUX_LIBRARY} ${OPENCV_CXCORE_LIBRARY} ${OPENCV_ML_LIBRARY})
  SET( OPENCV_INCLUDE_DIRS ${OPENCV_INCLUDE_DIR} ${OPENCV_INCLUDE_DIR}/opencv)
ELSE( OPENCV_FOUND)
  SET( OPENCV_LIBRARIES)
  SET( OPENCV_INCLUDE_DIRS)
ENDIF( OPENCV_FOUND)

MARK_AS_ADVANCED( OPENCV_INCLUDE_DIR OPENCV_LIBRARY OPENCV_AUX_LIBRARY OPENCV_CXCORE_LIBRARY OPENCV_ML_LIBRARY)

