OFX Support: OFX::Double3DParamDescriptor Class Reference
OFX::Double3DParamDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a 3D double param.
Public Member Functions
void setDimensionLabels (const std::string &x, const std::string &y, const std::string &z)
set the dimension labels
void setDefault (double x, double y, double z)
set the default value, default is 0
void setRange (double minX, double minY, double minZ, double maxX, double maxY, double maxZ)
set the hard min/max range, default is INT_MIN, INT_MAX
void setDisplayRange (double minX, double minY, double minZ, double maxX, double maxY, double maxZ)
set the display min and max, default is to be the same as the range param
Protected Member Functions
mDeclareProtectedAssignAndCC (Double3DParamDescriptor)
Double3DParamDescriptor (void)
Double3DParamDescriptor (const std::string &name, OfxPropertySetHandle props)
hidden constructor
Friends
class ParamSetDescriptor
Constructor & Destructor Documentation
OFX::Double3DParamDescriptor::Double3DParamDescriptor (void) [inline, protected]
OFX::Double3DParamDescriptor::Double3DParamDescriptor (const std::string & name, OfxPropertySetHandle props) [protected]
hidden constructor
ctor
Member Function Documentation
OFX::Double3DParamDescriptor::mDeclareProtectedAssignAndCC (Double3DParamDescriptor) [protected]
void OFX::Double3DParamDescriptor::setDimensionLabels (const std::string & x, const std::string & y, const std::string & z)
set the dimension labels
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetString().
void OFX::Double3DParamDescriptor::setDefault (double x, double y, double z)
set the default value, default is 0
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::Double3DParamDescriptor::setRange (double minX, double minY, double minZ, double maxX, double maxY, double maxZ)
set the hard min/max range, default is INT_MIN, INT_MAX
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::Double3DParamDescriptor::setDisplayRange (double minX, double minY, double minZ, double maxX, double maxY, double maxZ)
set the display min and max, default is to be the same as the range param
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetDouble().
Friends And Related Function Documentation
friend class ParamSetDescriptor [friend]
Reimplemented from OFX::BaseDoubleParamDescriptor.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp