OFX Support: OFX::Double3DParam Class Reference
OFX::Double3DParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up an doubleeger param.
Public Member Functions
void setDefault (double x, double y, double z)
set the default value, default is 0
void setRange (double minX, double minY, double minZ, double maxX, double maxY, double maxZ)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
void setDisplayRange (double minX, double minY, double minZ, double maxX, double maxY, double maxZ)
set the display min and max, default is to be the same as the range param
void getDefault (double &x, double &y, double &z)
het the default value
void getRange (double &minX, double &minY, double &minZ, double &maxX, double &maxY, double &maxZ)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
void getDisplayRange (double &minX, double &minY, double &minZ, double &maxX, double &maxY, double &maxZ)
set the display min and max, default is to be the same as the range param
void getValue (double &x, double &y, double &z)
get value
void getValueAtTime (double t, double &x, double &y, double &z)
get the value at a time
void setValue (double x, double y, double z)
set value
void setValueAtTime (double t, double x, double y, double z)
set the value at a time, implicitly adds a keyframe
void differentiate (double t, double &x, double &y, double &z)
differentiate the param
Ofx3DPointD differentiate (double t)
differentiate the param
void integrate (double t1, double t2, double &x, double &y, double &z)
integrate the param
Ofx3DPointD integrate (double t1, double t2)
integrate the param
Protected Member Functions
mDeclareProtectedAssignAndCC (Double3DParam)
Double3DParam (void)
Double3DParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::Double3DParam::Double3DParam (void) [inline, protected]
OFX::Double3DParam::Double3DParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::Double3DParam::mDeclareProtectedAssignAndCC (Double3DParam) [protected]
void OFX::Double3DParam::setDefault (double x, double y, double z)
set the default value, default is 0
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::Double3DParam::setRange (double minX, double minY, double minZ, double maxX, double maxY, double maxZ)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::Double3DParam::setDisplayRange (double minX, double minY, double minZ, double maxX, double maxY, double maxZ)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::Double3DParam::getDefault (double & x, double & y, double & z)
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::Double3DParam::getRange (double & minX, double & minY, double & minZ, double & maxX, double & maxY, double & maxZ)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::Double3DParam::getDisplayRange (double & minX, double & minY, double & minZ, double & maxX, double & maxY, double & maxZ)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::Double3DParam::getValue (double & x, double & y, double & z)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::Double3DParam::getValueAtTime (double t, double & x, double & y, double & z)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::Double3DParam::setValue (double x, double y, double z)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::Double3DParam::setValueAtTime (double t, double x, double y, double z)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
void OFX::Double3DParam::differentiate (double t, double & x, double & y, double & z)
differentiate the param
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Referenced by differentiate().
Ofx3DPointD OFX::Double3DParam::differentiate (double t) [inline]
differentiate the param
References differentiate(), Ofx3DPointD::x, Ofx3DPointD::y, and Ofx3DPointD::z.
void OFX::Double3DParam::integrate (double t1, double t2, double & x, double & y, double & z)
integrate the param
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Referenced by integrate().
Ofx3DPointD OFX::Double3DParam::integrate (double t1, double t2) [inline]
integrate the param
References integrate(), Ofx3DPointD::x, Ofx3DPointD::y, and Ofx3DPointD::z.
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::BaseDoubleParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp