OFX Support: OFX::BaseDoubleParamDescriptor Class Reference
OFX::BaseDoubleParamDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Common base to all double param types.
Public Member Functions
void setDoubleType (DoubleTypeEnum v)
set the type of the double param, defaults to eDoubleTypePlain
void setIncrement (double v)
set the sensitivity of any gui slider
void setDigits (int v)
set the number of digits printed after a decimal point in any gui
Protected Member Functions
mDeclareProtectedAssignAndCC (BaseDoubleParamDescriptor)
BaseDoubleParamDescriptor (void)
BaseDoubleParamDescriptor (const std::string &name, ParamTypeEnum type, OfxPropertySetHandle props)
hidden constructor
Friends
class ParamSetDescriptor
Constructor & Destructor Documentation
OFX::BaseDoubleParamDescriptor::BaseDoubleParamDescriptor (void) [inline, protected]
OFX::BaseDoubleParamDescriptor::BaseDoubleParamDescriptor (const std::string & name, ParamTypeEnum type, OfxPropertySetHandle props) [protected]
hidden constructor
Member Function Documentation
OFX::BaseDoubleParamDescriptor::mDeclareProtectedAssignAndCC (BaseDoubleParamDescriptor) [protected]
void OFX::BaseDoubleParamDescriptor::setDoubleType (DoubleTypeEnum v)
set the type of the double param, defaults to eDoubleTypePlain
References OFX::ParamDescriptor::_paramProps, OFX::eDoubleTypeAbsoluteTime, OFX::eDoubleTypeAngle, OFX::eDoubleTypeNormalisedX, OFX::eDoubleTypeNormalisedXAbsolute, OFX::eDoubleTypeNormalisedXY, OFX::eDoubleTypeNormalisedXYAbsolute, OFX::eDoubleTypeNormalisedY, OFX::eDoubleTypeNormalisedYAbsolute, OFX::eDoubleTypePlain, OFX::eDoubleTypeScale, OFX::eDoubleTypeTime, and OFX::PropertySet::propSetString().
void OFX::BaseDoubleParamDescriptor::setIncrement (double v)
set the sensitivity of any gui slider
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::BaseDoubleParamDescriptor::setDigits (int v)
set the number of digits printed after a decimal point in any gui
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
Friends And Related Function Documentation
friend class ParamSetDescriptor [friend]
Reimplemented from OFX::ValueParamDescriptor.
Reimplemented in OFX::DoubleParamDescriptor, OFX::Double2DParamDescriptor, and OFX::Double3DParamDescriptor.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp