OFX Support: OFX::RGBAParam Class Reference
OFX::RGBAParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up an RGB param.
Public Member Functions
void setDefault (double r, double g, double b, double a)
set the default value, default is 0
void getDefault (double &r, double &g, double &b, double &a)
get default value
void getValue (double &r, double &g, double &b, double &a)
get value
void getValueAtTime (double t, double &r, double &g, double &b, double &a)
get the value at a time
void setValue (double r, double g, double b, double a)
set value
void setValueAtTime (double t, double r, double g, double b, double a)
set the value at a time, implicitly adds a keyframe
Protected Member Functions
mDeclareProtectedAssignAndCC (RGBAParam)
RGBAParam (void)
RGBAParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::RGBAParam::RGBAParam (void) [inline, protected]
OFX::RGBAParam::RGBAParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::RGBAParam::mDeclareProtectedAssignAndCC (RGBAParam) [protected]
void OFX::RGBAParam::setDefault (double r, double g, double b, double a)
set the default value, default is 0
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::RGBAParam::getDefault (double & r, double & g, double & b, double & a)
get default value
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::RGBAParam::getValue (double & r, double & g, double & b, double & a)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::RGBAParam::getValueAtTime (double t, double & r, double & g, double & b, double & a)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::RGBAParam::setValue (double r, double g, double b, double a)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::RGBAParam::setValueAtTime (double t, double r, double g, double b, double a)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::ValueParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp