OFX Support: OFX::BooleanParam Class Reference
OFX::BooleanParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a boolean param.
Public Member Functions
void setDefault (bool v)
set the default value
void getDefault (bool &v)
get the default value
bool getDefault (void)
get the default value
void getValue (bool &v)
get value
bool getValue (void)
get value
void getValueAtTime (double t, bool &v)
get the value at a time
bool getValueAtTime (double t)
get value
void setValue (bool v)
set value
void setValueAtTime (double t, bool v)
set the value at a time, implicitly adds a keyframe
Protected Member Functions
mDeclareProtectedAssignAndCC (BooleanParam)
BooleanParam (void)
BooleanParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::BooleanParam::BooleanParam (void) [inline, protected]
OFX::BooleanParam::BooleanParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::BooleanParam::mDeclareProtectedAssignAndCC (BooleanParam) [protected]
void OFX::BooleanParam::setDefault (bool v)
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::BooleanParam::getDefault (bool & v)
get the default value
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
bool OFX::BooleanParam::getDefault (void) [inline]
get the default value
void OFX::BooleanParam::getValue (bool & v)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
bool OFX::BooleanParam::getValue (void) [inline]
get value
void OFX::BooleanParam::getValueAtTime (double t, bool & v)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
Referenced by getValueAtTime().
bool OFX::BooleanParam::getValueAtTime (double t) [inline]
get value
References getValueAtTime().
void OFX::BooleanParam::setValue (bool v)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::BooleanParam::setValueAtTime (double t, bool v)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::ValueParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp