OFX Support: OFX::ClipPreferencesSetter Class Reference
OFX::ClipPreferencesSetter Class Reference
#include <ofxsImageEffect.h>
Detailed Description
Class used to set the clip preferences of the effect.
Public Member Functions
ClipPreferencesSetter (OFX::PropertySet props, const StringStringMap &depthPropNames, const StringStringMap &componentPropNames, const StringStringMap &PARPropNames)
bool didSomething (void) const
void setClipComponents (Clip &clip, PixelComponentEnum comps)
, force the host to set a clip's mapped component type to be comps.
void setClipBitDepth (Clip &clip, BitDepthEnum bitDepth)
, force the host to set a clip's mapped bit depth be bitDepth
void setPixelAspectRatio (Clip &clip, double PAR)
, force the host to set a clip's mapped Pixel Aspect Ratio to be PAR
void setOutputFrameRate (double v)
Allows an effect to change the output frame rate.
void setOutputPremultiplication (PreMultiplicationEnum v)
Set the premultiplication state of the output clip.
void setOutputHasContinousSamples (bool v)
Set whether the effect can be continously sampled.
void setOutputFrameVarying (bool v)
Sets whether the effect will produce different images in all frames, even if the no params or input images are varying (eg: a noise generator).
void setOutputFielding (FieldEnum v)
Sets the output fielding.
Constructor & Destructor Documentation
OFX::ClipPreferencesSetter::ClipPreferencesSetter (OFX::PropertySet props, const StringStringMap & depthPropNames, const StringStringMap & componentPropNames, const StringStringMap & PARPropNames) [inline]
Member Function Documentation
bool OFX::ClipPreferencesSetter::didSomething (void) const [inline]
void OFX::ClipPreferencesSetter::setClipComponents (Clip & clip, PixelComponentEnum comps)
, force the host to set a clip's mapped component type to be comps.
Only callable on non optional clips in all contexts. Must set comps to be one of the types the effect says it supports on the given clip.
See the OFX API documentation for the default values of this.
References OFX::ePixelComponentAlpha, OFX::ePixelComponentRGBA, OFX::Clip::name(), and OFX::PropertySet::propSetString().
void OFX::ClipPreferencesSetter::setClipBitDepth (Clip & clip, BitDepthEnum bitDepth)
, force the host to set a clip's mapped bit depth be bitDepth
Only callable if the OFX::ImageEffectHostDescription::supportsMultipleClipDepths is true.
See the OFX API documentation for the default values of this.
References OFX::eBitDepthFloat, OFX::eBitDepthUByte, OFX::eBitDepthUShort, OFX::Clip::name(), and OFX::PropertySet::propSetString().
void OFX::ClipPreferencesSetter::setPixelAspectRatio (Clip & clip, double PAR)
, force the host to set a clip's mapped Pixel Aspect Ratio to be PAR
Only callable if the OFX::ImageEffectHostDescription::supportsMultipleClipPARs is true.
Default is up to the host, generally based on the input clips.
Not supported by most host applications.
References OFX::Clip::name(), and OFX::PropertySet::propSetDouble().
void OFX::ClipPreferencesSetter::setOutputFrameRate (double v)
Allows an effect to change the output frame rate.
Only callable if OFX::ImageEffectHostDescription::supportsSetableFrameRate is true.
Default is controlled by the host, typically the framerate of the input clips.
References OFX::PropertySet::propSetDouble().
void OFX::ClipPreferencesSetter::setOutputPremultiplication (PreMultiplicationEnum v)
Set the premultiplication state of the output clip.
Defaults to the premultiplication state of ???
References OFX::eImageOpaque, OFX::eImagePreMultiplied, OFX::eImageUnPreMultiplied, and OFX::PropertySet::propSetString().
void OFX::ClipPreferencesSetter::setOutputHasContinousSamples (bool v)
Set whether the effect can be continously sampled.
Defaults to false.
References OFX::PropertySet::propSetInt().
void OFX::ClipPreferencesSetter::setOutputFrameVarying (bool v)
Sets whether the effect will produce different images in all frames, even if the no params or input images are varying (eg: a noise generator).
Defaults to false.
References OFX::PropertySet::propSetInt().
void OFX::ClipPreferencesSetter::setOutputFielding (FieldEnum v)
Sets the output fielding.
Default is host dependent, must be one of
eFieldNone,
eFieldLower,
eFieldUpper
References OFX::eFieldLower, OFX::eFieldNone, OFX::eFieldUpper, and OFX::PropertySet::propSetString().
The documentation for this class was generated from the following files:
ofxsImageEffect.h
ofxsImageEffect.cpp