OFX Support: OFX::Int3DParam Class Reference
OFX::Int3DParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up an integer param.
Public Member Functions
void setDefault (int x, int y, int z)
set the default value, default is 0
void setRange (int minX, int minY, int minZ, int maxX, int maxY, int maxZ)
set the hard min/max range, default is INT_MIN, INT_MAX
void setDisplayRange (int minX, int minY, int minZ, int maxX, int maxY, int maxZ)
set the display min and max, default is to be the same as the range param
void getDefault (int &x, int &y, int &z)
het the default value
void getRange (int &minX, int &minY, int &minZ, int &maxX, int &maxY, int &maxZ)
set the hard min/max range, default is INT_MIN, INT_MAX
void getDisplayRange (int &minX, int &minY, int &minZ, int &maxX, int &maxY, int &maxZ)
set the display min and max, default is to be the same as the range param
void getValue (int &x, int &y, int &z)
get value
void getValueAtTime (double t, int &x, int &y, int &z)
get the value at a time
void setValue (int x, int y, int z)
set value
void setValueAtTime (double t, int x, int y, int z)
set the value at a time, implicitly adds a keyframe
Protected Member Functions
mDeclareProtectedAssignAndCC (Int3DParam)
Int3DParam (void)
Int3DParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::Int3DParam::Int3DParam (void) [inline, protected]
OFX::Int3DParam::Int3DParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::Int3DParam::mDeclareProtectedAssignAndCC (Int3DParam) [protected]
void OFX::Int3DParam::setDefault (int x, int y, int z)
set the default value, default is 0
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::Int3DParam::setRange (int minX, int minY, int minZ, int maxX, int maxY, int maxZ)
set the hard min/max range, default is INT_MIN, INT_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::Int3DParam::setDisplayRange (int minX, int minY, int minZ, int maxX, int maxY, int maxZ)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::Int3DParam::getDefault (int & x, int & y, int & z)
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
void OFX::Int3DParam::getRange (int & minX, int & minY, int & minZ, int & maxX, int & maxY, int & maxZ)
set the hard min/max range, default is INT_MIN, INT_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
void OFX::Int3DParam::getDisplayRange (int & minX, int & minY, int & minZ, int & maxX, int & maxY, int & maxZ)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
void OFX::Int3DParam::getValue (int & x, int & y, int & z)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::Int3DParam::getValueAtTime (double t, int & x, int & y, int & z)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::Int3DParam::setValue (int x, int y, int z)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::Int3DParam::setValueAtTime (double t, int x, int y, int z)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::ValueParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp