OFX Support: OFX::Int2DParam Class Reference
OFX::Int2DParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up an integer param.
Public Member Functions
void setDefault (int x, int y)
set the default value, default is 0
void setDefault (const OfxPointI &v)
set the default value, default is 0
void setRange (int minX, int minY, int maxX, int maxY)
set the hard min/max range, default is INT_MIN, INT_MAX
void setDisplayRange (int minX, int minY, int maxX, int maxY)
set the display min and max, default is to be the same as the range param
void getDefault (int &x, int &y)
het the default value
OfxPointI getDefault (void)
get the default value
void getRange (int &minX, int &minY, int &maxX, int &maxY)
set the hard min/max range, default is INT_MIN, INT_MAX
void getDisplayRange (int &minX, int &minY, int &maxX, int &maxY)
set the display min and max, default is to be the same as the range param
void getValue (int &x, int &y)
get value
OfxPointI getValue (void)
get the value
void getValueAtTime (double t, int &x, int &y)
get the value at a time
OfxPointI getValueAtTime (double t)
get the value
void setValue (int x, int y)
set value
void setValue (const OfxPointI &v)
set the current value
void setValueAtTime (double t, int x, int y)
set the value at a time, implicitly adds a keyframe
void setValueAtTime (double t, const OfxPointI &v)
set the current value
Protected Member Functions
mDeclareProtectedAssignAndCC (Int2DParam)
Int2DParam (void)
Int2DParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::Int2DParam::Int2DParam (void) [inline, protected]
OFX::Int2DParam::Int2DParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::Int2DParam::mDeclareProtectedAssignAndCC (Int2DParam) [protected]
void OFX::Int2DParam::setDefault (int x, int y)
set the default value, default is 0
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
Referenced by setDefault().
void OFX::Int2DParam::setDefault (const OfxPointI & v) [inline]
set the default value, default is 0
References setDefault().
void OFX::Int2DParam::setRange (int minX, int minY, int maxX, int maxY)
set the hard min/max range, default is INT_MIN, INT_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::Int2DParam::setDisplayRange (int minX, int minY, int maxX, int maxY)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::Int2DParam::getDefault (int & x, int & y)
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
OfxPointI OFX::Int2DParam::getDefault (void) [inline]
get the default value
void OFX::Int2DParam::getRange (int & minX, int & minY, int & maxX, int & maxY)
set the hard min/max range, default is INT_MIN, INT_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
void OFX::Int2DParam::getDisplayRange (int & minX, int & minY, int & maxX, int & maxY)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
void OFX::Int2DParam::getValue (int & x, int & y)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
OfxPointI OFX::Int2DParam::getValue (void) [inline]
get the value
void OFX::Int2DParam::getValueAtTime (double t, int & x, int & y)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
Referenced by getValueAtTime().
OfxPointI OFX::Int2DParam::getValueAtTime (double t) [inline]
get the value
References getValueAtTime().
void OFX::Int2DParam::setValue (int x, int y)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
Referenced by setValue().
void OFX::Int2DParam::setValue (const OfxPointI & v) [inline]
set the current value
References setValue().
void OFX::Int2DParam::setValueAtTime (double t, int x, int y)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Referenced by setValueAtTime().
void OFX::Int2DParam::setValueAtTime (double t, const OfxPointI & v) [inline]
set the current value
References setValueAtTime().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::ValueParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp