OFX Support: OFX::ValueParamDescriptor Class Reference
OFX::ValueParamDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a value holding param.
Public Member Functions
~ValueParamDescriptor ()
dtor
void setAnimates (bool v)
set whether the param can animate, defaults to true in most cases
void setIsPersistant (bool v)
set whether the param is persistant, defaults to true
void setEvaluateOnChange (bool v)
Set's whether the value of the param is significant (ie: affects the rendered image), defaults to true.
void setCacheInvalidation (CacheInvalidationEnum v)
Set's how any cache should be invalidated if the parameter is changed, defaults to eCacheInvalidateValueChange.
void setCanUndo (bool v)
Set whether the param should appear on any undo stack.
void setInteractDescriptor (ParamInteractDescriptor *desc)
Protected Member Functions
mDeclareProtectedAssignAndCC (ValueParamDescriptor)
ValueParamDescriptor (void)
ValueParamDescriptor (const std::string &name, ParamTypeEnum type, OfxPropertySetHandle props)
hidden constructor
Protected Attributes
std::auto_ptr
< ParamInteractDescriptor > _interact
Friends
class ParamSetDescriptor
Constructor & Destructor Documentation
OFX::ValueParamDescriptor::ValueParamDescriptor (void) [inline, protected]
OFX::ValueParamDescriptor::ValueParamDescriptor (const std::string & name, ParamTypeEnum type, OfxPropertySetHandle props) [protected]
hidden constructor
ctor
OFX::ValueParamDescriptor::~ValueParamDescriptor ()
dtor
Member Function Documentation
OFX::ValueParamDescriptor::mDeclareProtectedAssignAndCC (ValueParamDescriptor) [protected]
void OFX::ValueParamDescriptor::setAnimates (bool v)
set whether the param can animate, defaults to true in most cases
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::ValueParamDescriptor::setIsPersistant (bool v)
set whether the param is persistant, defaults to true
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::ValueParamDescriptor::setEvaluateOnChange (bool v)
Set's whether the value of the param is significant (ie: affects the rendered image), defaults to true.
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::ValueParamDescriptor::setCacheInvalidation (CacheInvalidationEnum v)
Set's how any cache should be invalidated if the parameter is changed, defaults to eCacheInvalidateValueChange.
References OFX::ParamDescriptor::_paramProps, OFX::eCacheInvalidateValueAll, OFX::eCacheInvalidateValueChange, OFX::eCacheInvalidateValueChangeToEnd, and OFX::PropertySet::propSetString().
void OFX::ValueParamDescriptor::setCanUndo (bool v)
Set whether the param should appear on any undo stack.
Set's whether the value of the param is significant (ie: affects the rendered image), defaults to true.
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::ValueParamDescriptor::setInteractDescriptor (ParamInteractDescriptor * desc)
References _interact, OFX::ParamDescriptor::_paramProps, OFX::InteractDescriptor::getMainEntry(), OFX::ParamDescriptor::getName(), OFX::PropertySet::propSetPointer(), and OFX::ParamInteractDescriptor::setParamName().
Friends And Related Function Documentation
friend class ParamSetDescriptor [friend]
Reimplemented from OFX::ParamDescriptor.
Reimplemented in OFX::StringParamDescriptor, OFX::IntParamDescriptor, OFX::Int2DParamDescriptor, OFX::Int3DParamDescriptor, OFX::BaseDoubleParamDescriptor, OFX::DoubleParamDescriptor, OFX::Double2DParamDescriptor, OFX::Double3DParamDescriptor, OFX::RGBParamDescriptor, OFX::RGBAParamDescriptor, OFX::BooleanParamDescriptor, OFX::ChoiceParamDescriptor, and OFX::CustomParamDescriptor.
Member Data Documentation
std::auto_ptr<ParamInteractDescriptor> OFX::ValueParamDescriptor::_interact [protected]
Referenced by setInteractDescriptor().
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp