OFX Support: OFX::MultiThread::Processor Class Reference
OFX::MultiThread::Processor Class Reference
#include <ofxsMultiThread.h>
Detailed Description
Class that wraps up SMP multi-processing.
Public Member Functions
Processor ()
ctor
virtual ~Processor ()
dtor
virtual void multiThreadFunction (unsigned int threadID, unsigned int nThreads)=0
function that will be called in each thread. ID is from 0..nThreads-1 nThreads are the number of threads it is being run over
virtual void multiThread (unsigned int nCPUs=0)
call this to kick off multi threading
Constructor & Destructor Documentation
OFX::MultiThread::Processor::Processor (void)
ctor
OFX::MultiThread::Processor::~Processor () [virtual]
dtor
Member Function Documentation
virtual void OFX::MultiThread::Processor::multiThreadFunction (unsigned int threadID, unsigned int nThreads) [pure virtual]
function that will be called in each thread. ID is from 0..nThreads-1 nThreads are the number of threads it is being run over
Referenced by multiThread().
void OFX::MultiThread::Processor::multiThread (unsigned int nCPUs = 0) [virtual]
call this to kick off multi threading
Function to pass to the multi thread suite.
The nCPUs is 0, the maximum allowable number of CPUs will be used.
References OFX::MultiThread::getNumCPUs(), OFX::Private::gThreadSuite, multiThreadFunction(), and OFX::throwSuiteStatusException().
The documentation for this class was generated from the following files:
ofxsMultiThread.h
ofxsMultiThread.cpp