OFX Support: OFX::ImageEffectDescriptor Class Reference
OFX::ImageEffectDescriptor Class Reference
#include <ofxsImageEffect.h>
Detailed Description
Wraps up an effect descriptor, used in the describe actions.
Public Member Functions
ImageEffectDescriptor (OfxImageEffectHandle handle)
ctor
~ImageEffectDescriptor ()
dtor
const PropertySet & getPropertySet () const
PropertySet & getPropertySet ()
void setLabels (const std::string &label, const std::string &shortLabel, const std::string &longLabel)
, set the label properties in a plugin
void setPluginGrouping (const std::string &group)
Set the plugin grouping, defaults to "".
void addSupportedContext (ContextEnum v)
Add a context to those supported, defaults to none, must be called at least once.
void addSupportedBitDepth (BitDepthEnum v)
Add a pixel depth to those supported, defaults to none, must be called at least once.
void setSingleInstance (bool v)
Is the plugin single instance only ? defaults to false.
void setHostFrameThreading (bool v)
Does the plugin expect the host to perform per frame SMP threading defaults to true.
void setSupportsMultiResolution (bool v)
Does the plugin support multi resolution images, defaults to true.
void setSupportsTiles (bool v)
Does the plugin support image tiling, defaults to true.
void setTemporalClipAccess (bool v)
Does the plugin perform temporal clip access, defaults to false.
void setRenderTwiceAlways (bool v)
Does the plugin want to have render called twice per frame in all circumanstances for fielded images ? defaults to true.
void setSupportsMultipleClipDepths (bool v)
Does the plugin support inputs and output clips of differing depths, defaults to false.
void setSupportsMultipleClipPARs (bool v)
Does the plugin support inputs and output clips of pixel aspect ratios, defaults to false.
void setRenderThreadSafety (RenderSafetyEnum v)
How thread safe is the plugin, defaults to eRenderInstanceSafe.
void addClipPreferencesSlaveParam (ParamDescriptor &p)
If the slave param changes the clip preferences need to be re-evaluated.
ClipDescriptor * defineClip (const std::string &name)
Create a clip, only callable from describe in context.
const std::map< std::string,
std::string > & getClipComponentPropNames () const
Access to the string maps needed for runtime properties. Because the char array must persist after the call, we need these to be stored in the descriptor, which is only deleted on unload.
const std::map< std::string,
std::string > & getClipDepthPropNames () const
const std::map< std::string,
std::string > & getClipPARPropNames () const
const std::map< std::string,
std::string > & getClipROIPropNames () const
const std::map< std::string,
std::string > & getClipFrameRangePropNames () const
virtual void setOverlayInteractDescriptor (EffectOverlayDescriptor *desc)
override this to create an interact for the effect
Protected Member Functions
mDeclareProtectedAssignAndCC (ImageEffectDescriptor)
ImageEffectDescriptor (void)
Protected Attributes
OfxImageEffectHandle _effectHandle
The effect handle.
PropertySet _effectProps
properties for this clip
std::map< std::string,
ClipDescriptor * > _definedClips
Set of all previously defined parameters, defined on demand.
std::map< std::string,
std::string > _clipComponentsPropNames
Set of strings for clip preferences action (stored in here so the array persists and can be used in a property name).
std::map< std::string,
std::string > _clipDepthPropNames
std::map< std::string,
std::string > _clipPARPropNames
std::map< std::string,
std::string > _clipROIPropNames
std::map< std::string,
std::string > _clipFrameRangePropNames
std::auto_ptr
< EffectOverlayDescriptor > _overlayDescriptor
Constructor & Destructor Documentation
OFX::ImageEffectDescriptor::ImageEffectDescriptor (void) [inline, protected]
OFX::ImageEffectDescriptor::ImageEffectDescriptor (OfxImageEffectHandle handle)
ctor
effect descriptor ctor
References _effectProps, OFX::Private::gEffectSuite, OFX::PropertySet::propSetHandle(), OFX::ParamSetDescriptor::setParamSetHandle(), OFX::throwSuiteStatusException(), and OFX::Validation::validatePluginDescriptorProperties().
OFX::ImageEffectDescriptor::~ImageEffectDescriptor ()
dtor
References _definedClips.
Member Function Documentation
OFX::ImageEffectDescriptor::mDeclareProtectedAssignAndCC (ImageEffectDescriptor) [protected]
const PropertySet& OFX::ImageEffectDescriptor::getPropertySet () const [inline]
References _effectProps.
PropertySet& OFX::ImageEffectDescriptor::getPropertySet () [inline]
References _effectProps.
void OFX::ImageEffectDescriptor::setLabels (const std::string & label, const std::string & shortLabel, const std::string & longLabel)
, set the label properties in a plugin
References _effectProps, and OFX::PropertySet::propSetString().
void OFX::ImageEffectDescriptor::setPluginGrouping (const std::string & group)
Set the plugin grouping, defaults to "".
Set the plugin grouping.
References _effectProps, and OFX::PropertySet::propSetString().
void OFX::ImageEffectDescriptor::addSupportedContext (ContextEnum v)
Add a context to those supported, defaults to none, must be called at least once.
Add a context to those supported.
References _effectProps, OFX::eContextFilter, OFX::eContextGeneral, OFX::eContextGenerator, OFX::eContextPaint, OFX::eContextRetimer, OFX::eContextTransition, OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
void OFX::ImageEffectDescriptor::addSupportedBitDepth (BitDepthEnum v)
Add a pixel depth to those supported, defaults to none, must be called at least once.
Add a pixel depth to those supported.
References _effectProps, OFX::eBitDepthFloat, OFX::eBitDepthUByte, OFX::eBitDepthUShort, OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
void OFX::ImageEffectDescriptor::setSingleInstance (bool v)
Is the plugin single instance only ? defaults to false.
Is the plugin single instance only ?
References _effectProps, and OFX::PropertySet::propSetInt().
void OFX::ImageEffectDescriptor::setHostFrameThreading (bool v)
Does the plugin expect the host to perform per frame SMP threading defaults to true.
Does the plugin expect the host to perform per frame SMP threading.
References _effectProps, and OFX::PropertySet::propSetInt().
void OFX::ImageEffectDescriptor::setSupportsMultiResolution (bool v)
Does the plugin support multi resolution images, defaults to true.
Does the plugin support multi resolution images.
References _effectProps, and OFX::PropertySet::propSetInt().
void OFX::ImageEffectDescriptor::setSupportsTiles (bool v)
Does the plugin support image tiling, defaults to true.
Does the plugin support image tiling.
References _effectProps, and OFX::PropertySet::propSetInt().
void OFX::ImageEffectDescriptor::setTemporalClipAccess (bool v)
Does the plugin perform temporal clip access, defaults to false.
Does the plugin perform temporal clip access.
References _effectProps, and OFX::PropertySet::propSetInt().
void OFX::ImageEffectDescriptor::setRenderTwiceAlways (bool v)
Does the plugin want to have render called twice per frame in all circumanstances for fielded images ? defaults to true.
Does the plugin want to have render called twice per frame in all circumanstances for fielded images ?
References _effectProps, and OFX::PropertySet::propSetInt().
void OFX::ImageEffectDescriptor::setSupportsMultipleClipDepths (bool v)
Does the plugin support inputs and output clips of differing depths, defaults to false.
Does the plugin support inputs and output clips of differing depths.
References _effectProps, and OFX::PropertySet::propSetInt().
void OFX::ImageEffectDescriptor::setSupportsMultipleClipPARs (bool v)
Does the plugin support inputs and output clips of pixel aspect ratios, defaults to false.
Does the plugin support inputs and output clips of pixel aspect ratios.
References _effectProps, and OFX::PropertySet::propSetInt().
void OFX::ImageEffectDescriptor::setRenderThreadSafety (RenderSafetyEnum v)
How thread safe is the plugin, defaults to eRenderInstanceSafe.
What kind of thread safety does the plugin have.
References _effectProps, OFX::eRenderFullySafe, OFX::eRenderInstanceSafe, OFX::eRenderUnsafe, and OFX::PropertySet::propSetString().
void OFX::ImageEffectDescriptor::addClipPreferencesSlaveParam (ParamDescriptor & p)
If the slave param changes the clip preferences need to be re-evaluated.
If the slave param changes the clip preferences need to be re-evaluated.
References _effectProps, OFX::ParamDescriptor::getName(), OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
ClipDescriptor * OFX::ImageEffectDescriptor::defineClip (const std::string & name)
Create a clip, only callable from describe in context.
The returned clip must not be deleted by the client code. This is all managed by the ImageEffectDescriptor itself.
References _clipComponentsPropNames, _clipDepthPropNames, _clipFrameRangePropNames, _clipPARPropNames, _clipROIPropNames, _definedClips, _effectHandle, and OFX::Private::gEffectSuite.
const std::map<std::string, std::string>& OFX::ImageEffectDescriptor::getClipComponentPropNames () const [inline]
Access to the string maps needed for runtime properties. Because the char array must persist after the call, we need these to be stored in the descriptor, which is only deleted on unload.
References _clipComponentsPropNames.
Referenced by OFX::Private::clipPreferencesAction().
const std::map<std::string, std::string>& OFX::ImageEffectDescriptor::getClipDepthPropNames () const [inline]
References _clipDepthPropNames.
Referenced by OFX::Private::clipPreferencesAction().
const std::map<std::string, std::string>& OFX::ImageEffectDescriptor::getClipPARPropNames () const [inline]
References _clipPARPropNames.
Referenced by OFX::Private::clipPreferencesAction().
const std::map<std::string, std::string>& OFX::ImageEffectDescriptor::getClipROIPropNames () const [inline]
References _clipROIPropNames.
const std::map<std::string, std::string>& OFX::ImageEffectDescriptor::getClipFrameRangePropNames () const [inline]
References _clipFrameRangePropNames.
void OFX::ImageEffectDescriptor::setOverlayInteractDescriptor (EffectOverlayDescriptor * desc) [virtual]
override this to create an interact for the effect
References _effectProps, _overlayDescriptor, OFX::InteractDescriptor::getMainEntry(), OFX::gHostDescription, and OFX::PropertySet::propSetPointer().
Member Data Documentation
OfxImageEffectHandle OFX::ImageEffectDescriptor::_effectHandle [protected]
The effect handle.
Referenced by defineClip().
PropertySet OFX::ImageEffectDescriptor::_effectProps [protected]
properties for this clip
Referenced by addClipPreferencesSlaveParam(), addSupportedBitDepth(), addSupportedContext(), getPropertySet(), ImageEffectDescriptor(), setHostFrameThreading(), setLabels(), setOverlayInteractDescriptor(), setPluginGrouping(), setRenderThreadSafety(), setRenderTwiceAlways(), setSingleInstance(), setSupportsMultipleClipDepths(), setSupportsMultipleClipPARs(), setSupportsMultiResolution(), setSupportsTiles(), and setTemporalClipAccess().
std::map<std::string, ClipDescriptor *> OFX::ImageEffectDescriptor::_definedClips [protected]
Set of all previously defined parameters, defined on demand.
Referenced by defineClip(), and ~ImageEffectDescriptor().
std::map<std::string, std::string> OFX::ImageEffectDescriptor::_clipComponentsPropNames [protected]
Set of strings for clip preferences action (stored in here so the array persists and can be used in a property name).
Referenced by defineClip(), and getClipComponentPropNames().
std::map<std::string, std::string> OFX::ImageEffectDescriptor::_clipDepthPropNames [protected]
Referenced by defineClip(), and getClipDepthPropNames().
std::map<std::string, std::string> OFX::ImageEffectDescriptor::_clipPARPropNames [protected]
Referenced by defineClip(), and getClipPARPropNames().
std::map<std::string, std::string> OFX::ImageEffectDescriptor::_clipROIPropNames [protected]
Referenced by defineClip(), and getClipROIPropNames().
std::map<std::string, std::string> OFX::ImageEffectDescriptor::_clipFrameRangePropNames [protected]
Referenced by defineClip(), and getClipFrameRangePropNames().
std::auto_ptr<EffectOverlayDescriptor> OFX::ImageEffectDescriptor::_overlayDescriptor [protected]
Referenced by setOverlayInteractDescriptor().
The documentation for this class was generated from the following files:
ofxsImageEffect.h
ofxsImageEffect.cpp