OFX Support: OFX::FactoryMainEntryHelper< FACTORY > Class Template Reference
OFX::FactoryMainEntryHelper< FACTORY > Class Template Reference
#include <ofxsImageEffect.h>
template<class FACTORY>
class OFX::FactoryMainEntryHelper< FACTORY >
Protected Member Functions
const std::string & getHelperID () const
unsigned int getHelperMajorVersion () const
unsigned int getHelperMinorVersion () const
std::string toString (unsigned int val)
FactoryMainEntryHelper (const std::string &id, unsigned int maj, unsigned int min)
const std::string & getHelperUID () const
Static Protected Member Functions
static OfxStatus mainEntry (const char *action, const void *handle, OfxPropertySetHandle in, OfxPropertySetHandle out)
Protected Attributes
std::string _id
unsigned int _maj
unsigned int _min
Static Protected Attributes
static std::string _uid
Constructor & Destructor Documentation
template<class FACTORY> OFX::FactoryMainEntryHelper< FACTORY >::FactoryMainEntryHelper (const std::string & id, unsigned int maj, unsigned int min) [inline, protected]
References OFX::FactoryMainEntryHelper< FACTORY >::_uid, and OFX::FactoryMainEntryHelper< FACTORY >::toString().
Member Function Documentation
template<class FACTORY> const std::string& OFX::FactoryMainEntryHelper< FACTORY >::getHelperID () const [inline, protected]
References OFX::FactoryMainEntryHelper< FACTORY >::_id.
template<class FACTORY> unsigned int OFX::FactoryMainEntryHelper< FACTORY >::getHelperMajorVersion () const [inline, protected]
References OFX::FactoryMainEntryHelper< FACTORY >::_maj.
template<class FACTORY> unsigned int OFX::FactoryMainEntryHelper< FACTORY >::getHelperMinorVersion () const [inline, protected]
References OFX::FactoryMainEntryHelper< FACTORY >::_min.
template<class FACTORY> std::string OFX::FactoryMainEntryHelper< FACTORY >::toString (unsigned int val) [inline, protected]
Referenced by OFX::FactoryMainEntryHelper< FACTORY >::FactoryMainEntryHelper().
template<class FACTORY> const std::string& OFX::FactoryMainEntryHelper< FACTORY >::getHelperUID () const [inline, protected]
References OFX::FactoryMainEntryHelper< FACTORY >::_uid.
template<class FACTORY> static OfxStatus OFX::FactoryMainEntryHelper< FACTORY >::mainEntry (const char * action, const void * handle, OfxPropertySetHandle in, OfxPropertySetHandle out) [inline, static, protected]
References OFX::FactoryMainEntryHelper< FACTORY >::_uid, and OFX::Private::mainEntryStr().
Member Data Documentation
template<class FACTORY> std::string OFX::FactoryMainEntryHelper< T >::_uid [inline, static, protected]
Referenced by OFX::FactoryMainEntryHelper< FACTORY >::FactoryMainEntryHelper(), OFX::FactoryMainEntryHelper< FACTORY >::getHelperUID(), and OFX::FactoryMainEntryHelper< FACTORY >::mainEntry().
template<class FACTORY> std::string OFX::FactoryMainEntryHelper< FACTORY >::_id [protected]
Referenced by OFX::FactoryMainEntryHelper< FACTORY >::getHelperID().
template<class FACTORY> unsigned int OFX::FactoryMainEntryHelper< FACTORY >::_maj [protected]
Referenced by OFX::FactoryMainEntryHelper< FACTORY >::getHelperMajorVersion().
template<class FACTORY> unsigned int OFX::FactoryMainEntryHelper< FACTORY >::_min [protected]
Referenced by OFX::FactoryMainEntryHelper< FACTORY >::getHelperMinorVersion().
The documentation for this class was generated from the following file:
ofxsImageEffect.h