OFX Support: OFX::DoubleParamDescriptor Class Reference
OFX::DoubleParamDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a double param.
Public Member Functions
void setShowTimeMarker (bool v)
if the double type is Absolute time, show a time marker on the time line if possible
void setDefault (double v)
set the default value, default is 0
void setRange (double min, double max)
set the hard min/max range, default is INT_MIN, INT_MAX
void setDisplayRange (double min, double max)
set the display min and max, default is to be the same as the range param
Protected Member Functions
mDeclareProtectedAssignAndCC (DoubleParamDescriptor)
DoubleParamDescriptor (void)
DoubleParamDescriptor (const std::string &name, OfxPropertySetHandle props)
hidden constructor
Friends
class ParamSetDescriptor
Constructor & Destructor Documentation
OFX::DoubleParamDescriptor::DoubleParamDescriptor (void) [inline, protected]
OFX::DoubleParamDescriptor::DoubleParamDescriptor (const std::string & name, OfxPropertySetHandle props) [protected]
hidden constructor
ctor
Member Function Documentation
OFX::DoubleParamDescriptor::mDeclareProtectedAssignAndCC (DoubleParamDescriptor) [protected]
void OFX::DoubleParamDescriptor::setShowTimeMarker (bool v)
if the double type is Absolute time, show a time marker on the time line if possible
void OFX::DoubleParamDescriptor::setDefault (double v)
set the default value, default is 0
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::DoubleParamDescriptor::setRange (double min, double max)
set the hard min/max range, default is INT_MIN, INT_MAX
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::DoubleParamDescriptor::setDisplayRange (double min, double max)
set the display min and max, default is to be the same as the range param
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetDouble().
Friends And Related Function Documentation
friend class ParamSetDescriptor [friend]
Reimplemented from OFX::BaseDoubleParamDescriptor.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp