OFX Support: OFX::DoubleParam Class Reference
OFX::DoubleParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up an doubleeger param.
Public Member Functions
void setDefault (double v)
set the default value
void setShowTimeMarker (bool v)
if the double type is Absolute time, show a time marker on the time line if possible
void setRange (double min, double max)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
void setDisplayRange (double min, double max)
set the display min and max, default is to be the same as the range param
void getDefault (double &v)
het the default value
double getDefault (void)
het the default value
void getRange (double &min, double &max)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
void getDisplayRange (double &min, double &max)
set the display min and max, default is to be the same as the range param
void getValue (double &v)
get value
double getValue (void)
get value
void getValueAtTime (double t, double &v)
get the value at a time
double getValueAtTime (double t)
get value
void setValue (double v)
set value
void setValueAtTime (double t, double v)
set the value at a time, implicitly adds a keyframe
void differentiate (double t, double &v)
differentiate the param
double differentiate (double t)
differentiate the param
void integrate (double t1, double t2, double &v)
integrate the param
double integrate (double t1, double t2)
integrate the param
Protected Member Functions
mDeclareProtectedAssignAndCC (DoubleParam)
DoubleParam (void)
DoubleParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::DoubleParam::DoubleParam (void) [inline, protected]
OFX::DoubleParam::DoubleParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::DoubleParam::mDeclareProtectedAssignAndCC (DoubleParam) [protected]
void OFX::DoubleParam::setDefault (double v)
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::DoubleParam::setShowTimeMarker (bool v)
if the double type is Absolute time, show a time marker on the time line if possible
void OFX::DoubleParam::setRange (double min, double max)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::DoubleParam::setDisplayRange (double min, double max)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::DoubleParam::getDefault (double & v)
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
double OFX::DoubleParam::getDefault (void) [inline]
het the default value
void OFX::DoubleParam::getRange (double & min, double & max)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::DoubleParam::getDisplayRange (double & min, double & max)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::DoubleParam::getValue (double & v)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
double OFX::DoubleParam::getValue (void) [inline]
get value
void OFX::DoubleParam::getValueAtTime (double t, double & v)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
Referenced by getValueAtTime().
double OFX::DoubleParam::getValueAtTime (double t) [inline]
get value
References getValueAtTime().
void OFX::DoubleParam::setValue (double v)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::DoubleParam::setValueAtTime (double t, double v)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
void OFX::DoubleParam::differentiate (double t, double & v)
differentiate the param
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Referenced by differentiate().
double OFX::DoubleParam::differentiate (double t) [inline]
differentiate the param
References differentiate().
void OFX::DoubleParam::integrate (double t1, double t2, double & v)
integrate the param
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Referenced by integrate().
double OFX::DoubleParam::integrate (double t1, double t2) [inline]
integrate the param
References integrate().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::BaseDoubleParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp