OFX Support: OFX::ChoiceParam Class Reference
OFX::ChoiceParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a choice param.
Public Member Functions
void setDefault (int v)
set the default value
void getDefault (int &v)
get the default value
int getNOptions (void)
how many options do we have
void appendOption (const std::string &v)
append an option, default is to have not there
void resetOptions (void)
clear all the options so as to add some new ones in
void getValue (int &v)
get value
void getValueAtTime (double t, int &v)
get the value at a time
void setValue (int v)
set value
void setValueAtTime (double t, int v)
set the value at a time, implicitly adds a keyframe
Protected Member Functions
mDeclareProtectedAssignAndCC (ChoiceParam)
ChoiceParam (void)
ChoiceParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::ChoiceParam::ChoiceParam (void) [inline, protected]
OFX::ChoiceParam::ChoiceParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::ChoiceParam::mDeclareProtectedAssignAndCC (ChoiceParam) [protected]
void OFX::ChoiceParam::setDefault (int v)
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::ChoiceParam::getDefault (int & v)
get the default value
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
int OFX::ChoiceParam::getNOptions (void)
how many options do we have
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDimension().
void OFX::ChoiceParam::appendOption (const std::string & v)
append an option, default is to have not there
set the default value
References OFX::Param::_paramProps, OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
void OFX::ChoiceParam::resetOptions (void)
clear all the options so as to add some new ones in
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propReset().
void OFX::ChoiceParam::getValue (int & v)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::ChoiceParam::getValueAtTime (double t, int & v)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::ChoiceParam::setValue (int v)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::ChoiceParam::setValueAtTime (double t, int v)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::ValueParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp