OFX Support: OFX::IntParam Class Reference
OFX::IntParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up an integer param.
Public Member Functions
void setDefault (int v)
set the default value
void setRange (int min, int max)
set the hard min/max range, default is INT_MIN, INT_MAX
void setDisplayRange (int min, int max)
set the display min and max, default is to be the same as the range param
void getDefault (int &v)
het the default value
int getDefault (void)
het the default value
void getRange (int &min, int &max)
set the hard min/max range, default is INT_MIN, INT_MAX
void getDisplayRange (int &min, int &max)
set the display min and max, default is to be the same as the range param
void getValue (int &v)
get value
int getValue (void)
and a nicer one
void getValueAtTime (double t, int &v)
get the value at a time
int getValueAtTime (double t)
and a nicer one
void setValue (int v)
set value
void setValueAtTime (double t, int v)
set the value at a time, implicitly adds a keyframe
Protected Member Functions
mDeclareProtectedAssignAndCC (IntParam)
IntParam (void)
IntParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::IntParam::IntParam (void) [inline, protected]
OFX::IntParam::IntParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::IntParam::mDeclareProtectedAssignAndCC (IntParam) [protected]
void OFX::IntParam::setDefault (int v)
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::IntParam::setRange (int min, int max)
set the hard min/max range, default is INT_MIN, INT_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::IntParam::setDisplayRange (int min, int max)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::IntParam::getDefault (int & v)
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
int OFX::IntParam::getDefault (void) [inline]
het the default value
void OFX::IntParam::getRange (int & min, int & max)
set the hard min/max range, default is INT_MIN, INT_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
void OFX::IntParam::getDisplayRange (int & min, int & max)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
void OFX::IntParam::getValue (int & v)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
int OFX::IntParam::getValue (void) [inline]
and a nicer one
void OFX::IntParam::getValueAtTime (double t, int & v)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
Referenced by getValueAtTime().
int OFX::IntParam::getValueAtTime (double t) [inline]
and a nicer one
References getValueAtTime().
void OFX::IntParam::setValue (int v)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::IntParam::setValueAtTime (double t, int v)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::ValueParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp