OFX Support: OFX::ParamInteractDescriptor Class Reference
OFX::ParamInteractDescriptor Class Reference
#include <ofxsInteract.h>
Public Member Functions
ParamInteractDescriptor ()
virtual ~ParamInteractDescriptor ()
void setInteractSizeAspect (double asp)
void setInteractMinimumSize (int x, int y)
void setInteractPreferredSize (int x, int y)
virtual void setParamName (const std::string &pName)
Protected Attributes
std::string _paramName
Constructor & Destructor Documentation
OFX::ParamInteractDescriptor::ParamInteractDescriptor () [inline]
virtual OFX::ParamInteractDescriptor::~ParamInteractDescriptor () [inline, virtual]
Member Function Documentation
void OFX::ParamInteractDescriptor::setInteractSizeAspect (double asp)
References OFX::InteractDescriptor::_props, and OFX::PropertySet::propSetDouble().
void OFX::ParamInteractDescriptor::setInteractMinimumSize (int x, int y)
References OFX::InteractDescriptor::_props, and OFX::PropertySet::propSetInt().
void OFX::ParamInteractDescriptor::setInteractPreferredSize (int x, int y)
References OFX::InteractDescriptor::_props, and OFX::PropertySet::propSetInt().
virtual void OFX::ParamInteractDescriptor::setParamName (const std::string & pName) [inline, virtual]
Reimplemented in OFX::DefaultParamInteractDescriptor< DESC, INSTANCE >.
References _paramName.
Referenced by OFX::ValueParamDescriptor::setInteractDescriptor().
Member Data Documentation
std::string OFX::ParamInteractDescriptor::_paramName [protected]
Referenced by setParamName().
The documentation for this class was generated from the following files:
ofxsInteract.h
ofxsInteract.cpp