OFX Support: OFX::StringParamDescriptor Class Reference
OFX::StringParamDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a string param.
Public Member Functions
void setDefault (const std::string &v)
set the default value, default is 0
void setStringType (StringTypeEnum v)
sets the kind of the string param, defaults to eStringSingleLine
void setFilePathExists (bool v)
if the string param is a file path, say that we are picking an existing file, rather than posibly specifying a new one, defaults to true
Protected Member Functions
mDeclareProtectedAssignAndCC (StringParamDescriptor)
StringParamDescriptor (void)
StringParamDescriptor (const std::string &name, OfxPropertySetHandle props)
hidden constructor
Friends
class ParamSetDescriptor
Constructor & Destructor Documentation
OFX::StringParamDescriptor::StringParamDescriptor (void) [inline, protected]
OFX::StringParamDescriptor::StringParamDescriptor (const std::string & name, OfxPropertySetHandle props) [protected]
hidden constructor
hidden ctor
Member Function Documentation
OFX::StringParamDescriptor::mDeclareProtectedAssignAndCC (StringParamDescriptor) [protected]
void OFX::StringParamDescriptor::setDefault (const std::string & v)
set the default value, default is 0
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetString().
void OFX::StringParamDescriptor::setStringType (StringTypeEnum v)
sets the kind of the string param, defaults to eStringSingleLine
References OFX::ParamDescriptor::_paramProps, OFX::eStringTypeDirectoryPath, OFX::eStringTypeFilePath, OFX::eStringTypeLabel, OFX::eStringTypeMultiLine, OFX::eStringTypeSingleLine, and OFX::PropertySet::propSetString().
void OFX::StringParamDescriptor::setFilePathExists (bool v)
if the string param is a file path, say that we are picking an existing file, rather than posibly specifying a new one, defaults to true
if the string param is a file path, say that we are picking an existing file, defaults to true
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
Friends And Related Function Documentation
friend class ParamSetDescriptor [friend]
Reimplemented from OFX::ValueParamDescriptor.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp