OFX Support: OFX::InteractDescriptor Class Reference
OFX::InteractDescriptor Class Reference
#include <ofxsInteract.h>
Public Member Functions
InteractDescriptor ()
virtual ~InteractDescriptor ()
void setPropertySet (OFX::PropertySet *props)
virtual Interact * createInstance (OfxInteractHandle handle, ImageEffect *effect)=0
void setHasAlpha ()
bool getHasAlpha () const
void setBitDepth ()
int getBitDepth () const
virtual OfxPluginEntryPoint * getMainEntry ()=0
virtual void describe ()
Protected Attributes
OFX::PropertySet * _props
Constructor & Destructor Documentation
OFX::InteractDescriptor::InteractDescriptor () [inline]
virtual OFX::InteractDescriptor::~InteractDescriptor () [inline, virtual]
Member Function Documentation
void OFX::InteractDescriptor::setPropertySet (OFX::PropertySet * props) [inline]
References _props.
Referenced by OFX::Private::interactMainEntry().
virtual Interact* OFX::InteractDescriptor::createInstance (OfxInteractHandle handle, ImageEffect * effect) [pure virtual]
Implemented in OFX::DefaultEffectOverlayDescriptor< DESC, INSTANCE >, and OFX::DefaultParamInteractDescriptor< DESC, INSTANCE >.
Referenced by OFX::Private::interactMainEntry().
void OFX::InteractDescriptor::setHasAlpha ()
bool OFX::InteractDescriptor::getHasAlpha () const
void OFX::InteractDescriptor::setBitDepth ()
int OFX::InteractDescriptor::getBitDepth () const
virtual OfxPluginEntryPoint* OFX::InteractDescriptor::getMainEntry () [pure virtual]
Implemented in OFX::DefaultEffectOverlayDescriptor< DESC, INSTANCE >, and OFX::DefaultParamInteractDescriptor< DESC, INSTANCE >.
Referenced by OFX::ValueParamDescriptor::setInteractDescriptor(), and OFX::ImageEffectDescriptor::setOverlayInteractDescriptor().
virtual void OFX::InteractDescriptor::describe () [inline, virtual]
Referenced by OFX::Private::interactMainEntry().
Member Data Documentation
OFX::PropertySet* OFX::InteractDescriptor::_props [protected]
Referenced by OFX::ParamInteractDescriptor::setInteractMinimumSize(), OFX::ParamInteractDescriptor::setInteractPreferredSize(), OFX::ParamInteractDescriptor::setInteractSizeAspect(), and setPropertySet().
The documentation for this class was generated from the following file:
ofxsInteract.h