OFX Support: OFX::Double2DParam Class Reference
OFX::Double2DParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up an doubleeger param.
Public Member Functions
void setDefault (double x, double y)
set the default value, default is 0
void setRange (double minX, double minY, double maxX, double maxY)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
void setDisplayRange (double minX, double minY, double maxX, double maxY)
set the display min and max, default is to be the same as the range param
void getDefault (double &x, double &y)
het the default value
void getRange (double &minX, double &minY, double &maxX, double &maxY)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
void getDisplayRange (double &minX, double &minY, double &maxX, double &maxY)
set the display min and max, default is to be the same as the range param
void getValue (double &x, double &y)
get value
void getValueAtTime (double t, double &x, double &y)
get the value at a time
void setValue (double x, double y)
set value
void setValueAtTime (double t, double x, double y)
set the value at a time, implicitly adds a keyframe
void differentiate (double t, double &x, double &y)
differentiate the param
OfxPointD differentiate (double t)
differentiate the param
void integrate (double t1, double t2, double &x, double &y)
integrate the param
OfxPointD integrate (double t1, double t2)
integrate the param
Protected Member Functions
mDeclareProtectedAssignAndCC (Double2DParam)
Double2DParam (void)
Double2DParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::Double2DParam::Double2DParam (void) [inline, protected]
OFX::Double2DParam::Double2DParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::Double2DParam::mDeclareProtectedAssignAndCC (Double2DParam) [protected]
void OFX::Double2DParam::setDefault (double x, double y)
set the default value, default is 0
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::Double2DParam::setRange (double minX, double minY, double maxX, double maxY)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::Double2DParam::setDisplayRange (double minX, double minY, double maxX, double maxY)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::Double2DParam::getDefault (double & x, double & y)
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::Double2DParam::getRange (double & minX, double & minY, double & maxX, double & maxY)
set the hard min/max range, default is DOUBLE_MIN, DOUBLE_MAX
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::Double2DParam::getDisplayRange (double & minX, double & minY, double & maxX, double & maxY)
set the display min and max, default is to be the same as the range param
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::Double2DParam::getValue (double & x, double & y)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::Double2DParam::getValueAtTime (double t, double & x, double & y)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::Double2DParam::setValue (double x, double y)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::Double2DParam::setValueAtTime (double t, double x, double y)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
void OFX::Double2DParam::differentiate (double t, double & x, double & y)
differentiate the param
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Referenced by differentiate().
OfxPointD OFX::Double2DParam::differentiate (double t) [inline]
differentiate the param
References differentiate().
void OFX::Double2DParam::integrate (double t1, double t2, double & x, double & y)
integrate the param
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Referenced by integrate().
OfxPointD OFX::Double2DParam::integrate (double t1, double t2) [inline]
integrate the param
References integrate().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::BaseDoubleParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp