OFX Support: OFX::CustomParam Class Reference
OFX::CustomParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a custom param, not animation support yet.
Public Member Functions
void setDefault (const std::string &v)
set the default value of the param
void getDefault (std::string &v)
get the default value of the param
void getValue (std::string &v)
get value
void getValueAtTime (double t, std::string &v)
get the value at a time
void setValue (const std::string &v)
set value
void setValueAtTime (double t, const std::string &v)
set the value at a time, implicitly adds a keyframe
Protected Member Functions
mDeclareProtectedAssignAndCC (CustomParam)
CustomParam (void)
CustomParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::CustomParam::CustomParam (void) [inline, protected]
OFX::CustomParam::CustomParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::CustomParam::mDeclareProtectedAssignAndCC (CustomParam) [protected]
void OFX::CustomParam::setDefault (const std::string & v)
set the default value of the param
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetString().
void OFX::CustomParam::getDefault (std::string & v)
get the default value of the param
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetString().
void OFX::CustomParam::getValue (std::string & v)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::CustomParam::getValueAtTime (double t, std::string & v)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::CustomParam::setValue (const std::string & v)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::CustomParam::setValueAtTime (double t, const std::string & v)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::ValueParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp