OFX Support: OFX::BaseDoubleParam Class Reference
OFX::BaseDoubleParam Class Reference
#include <ofxsParam.h>
Detailed Description
Common base to all double param types.
Public Member Functions
void setIncrement (double v)
set the sensitivity of any gui slider
void setDigits (int v)
set the number of digits printed after a decimal point in any gui
void getIncrement (double &v)
get the sensitivity of any gui slider
void getDigits (int &v)
get the number of digits printed after a decimal point in any gui
void getDoubleType (DoubleTypeEnum &v)
get the type of the double param
Protected Member Functions
mDeclareProtectedAssignAndCC (BaseDoubleParam)
BaseDoubleParam (void)
BaseDoubleParam (const ParamSet *paramSet, const std::string &name, ParamTypeEnum type, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::BaseDoubleParam::BaseDoubleParam (void) [inline, protected]
OFX::BaseDoubleParam::BaseDoubleParam (const ParamSet * paramSet, const std::string & name, ParamTypeEnum type, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::BaseDoubleParam::mDeclareProtectedAssignAndCC (BaseDoubleParam) [protected]
void OFX::BaseDoubleParam::setIncrement (double v)
set the sensitivity of any gui slider
References OFX::Param::_paramProps, and OFX::PropertySet::propSetDouble().
void OFX::BaseDoubleParam::setDigits (int v)
set the number of digits printed after a decimal point in any gui
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::BaseDoubleParam::getIncrement (double & v)
get the sensitivity of any gui slider
set the sensitivity of any gui slider
References OFX::Param::_paramProps, and OFX::PropertySet::propGetDouble().
void OFX::BaseDoubleParam::getDigits (int & v)
get the number of digits printed after a decimal point in any gui
set the number of digits printed after a decimal point in any gui
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
void OFX::BaseDoubleParam::getDoubleType (DoubleTypeEnum & v)
get the type of the double param
set the number of digits printed after a decimal point in any gui
References OFX::Param::_paramProps, OFX::eDoubleTypeAbsoluteTime, OFX::eDoubleTypeAngle, OFX::eDoubleTypeNormalisedX, OFX::eDoubleTypeNormalisedXAbsolute, OFX::eDoubleTypeNormalisedXY, OFX::eDoubleTypeNormalisedXYAbsolute, OFX::eDoubleTypeNormalisedY, OFX::eDoubleTypeNormalisedYAbsolute, OFX::eDoubleTypePlain, OFX::eDoubleTypeScale, OFX::eDoubleTypeTime, and OFX::PropertySet::propGetString().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::ValueParam.
Reimplemented in OFX::DoubleParam, OFX::Double2DParam, and OFX::Double3DParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp