OFX Support: OFX::PageParamDescriptor Class Reference
OFX::PageParamDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a page param, not much to it really.
Public Member Functions
void addChild (const ParamDescriptor &p)
adds a child parameter. Note the two existing pseudo params, gColumnSkip and gRowSkip
Static Public Attributes
static DummyParamDescriptor gSkipRow
dummy page positioning parameter to be passed to OFX::PageParamDescriptor::addChild
static DummyParamDescriptor gSkipColumn
dummy page positioning parameter to be passed to OFX::PageParamDescriptor::addChild
Protected Member Functions
mDeclareProtectedAssignAndCC (PageParamDescriptor)
PageParamDescriptor (void)
PageParamDescriptor (const std::string &name, OfxPropertySetHandle props)
hidden constructor
Friends
class ParamSetDescriptor
Constructor & Destructor Documentation
OFX::PageParamDescriptor::PageParamDescriptor (void) [inline, protected]
OFX::PageParamDescriptor::PageParamDescriptor (const std::string & name, OfxPropertySetHandle props) [protected]
hidden constructor
Member Function Documentation
OFX::PageParamDescriptor::mDeclareProtectedAssignAndCC (PageParamDescriptor) [protected]
void OFX::PageParamDescriptor::addChild (const ParamDescriptor & p)
adds a child parameter. Note the two existing pseudo params, gColumnSkip and gRowSkip
References OFX::ParamDescriptor::_paramProps, OFX::ParamDescriptor::getName(), OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
Friends And Related Function Documentation
friend class ParamSetDescriptor [friend]
Reimplemented from OFX::ParamDescriptor.
Member Data Documentation
DummyParamDescriptor OFX::PageParamDescriptor::gSkipRow [static]
dummy page positioning parameter to be passed to OFX::PageParamDescriptor::addChild
DummyParamDescriptor OFX::PageParamDescriptor::gSkipColumn [static]
dummy page positioning parameter to be passed to OFX::PageParamDescriptor::addChild
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp