OFX Support: OFX::Validation::PropertySetDescription Class Reference
OFX::Validation::PropertySetDescription Class Reference
#include <ofxsSupportPrivate.h>
Detailed Description
Describes a set of properties.
Public Member Functions
PropertySetDescription (char *setName,...)
constructor.
virtual ~PropertySetDescription ()
destructor
void addProperty (PropertyDescription *desc, bool deleteOnDestruction=true)
add another property in
void validate (PropertySet &propSet, bool checkDefaults=true, bool logOrdinaryMessages=false)
See if all properties exist and have the correct dimensions.
Protected Attributes
std::string _setName
name of the property set
std::vector
< PropertyDescription * > _descriptions
the descriptions of each property
std::vector
< PropertyDescription * > _deleteThese
The descriptions of each property.
Constructor & Destructor Documentation
OFX::Validation::PropertySetDescription::PropertySetDescription (char * setName, ...)
constructor.
The varargs zero terminated are made from pairs of PropertyDescription * and ints indicating the number of properties pointed to. These are to come from static arrays and need not be deleted
virtual OFX::Validation::PropertySetDescription::~PropertySetDescription () [virtual]
destructor
Member Function Documentation
void OFX::Validation::PropertySetDescription::addProperty (PropertyDescription * desc, bool deleteOnDestruction = true)
add another property in
Referenced by OFX::Validation::initialise().
void OFX::Validation::PropertySetDescription::validate (PropertySet & propSet, bool checkDefaults = true, bool logOrdinaryMessages = false)
See if all properties exist and have the correct dimensions.
Referenced by OFX::Validation::validateActionArgumentsProperties(), OFX::Validation::validateClipDescriptorProperties(), OFX::Validation::validateClipInstanceProperties(), OFX::Validation::validateHostProperties(), OFX::Validation::validateImageProperties(), OFX::Validation::validateParameterProperties(), OFX::Validation::validatePluginDescriptorProperties(), and OFX::Validation::validatePluginInstanceProperties().
Member Data Documentation
std::string OFX::Validation::PropertySetDescription::_setName [protected]
name of the property set
std::vector<PropertyDescription *> OFX::Validation::PropertySetDescription::_descriptions [protected]
the descriptions of each property
std::vector<PropertyDescription *> OFX::Validation::PropertySetDescription::_deleteThese [protected]
The descriptions of each property.
The documentation for this class was generated from the following file:
ofxsSupportPrivate.h