OFX Support: OFX::Clip Class Reference
OFX::Clip Class Reference
#include <ofxsImageEffect.h>
Detailed Description
Wraps up a clip instance.
Public Member Functions
const PropertySet & getPropertySet () const
get the underlying property set on this clip
PropertySet & getPropertySet ()
get the underlying property set on this clip
OfxImageClipHandle getHandle ()
get the OFX clip handle
const std::string & name (void) const
get the name
void getLabels (std::string &label, std::string &shortLabel, std::string &longLabel) const
fetch the labels
BitDepthEnum getPixelDepth (void) const
what is the pixel depth images will be given to us as
PixelComponentEnum getPixelComponents (void) const
what is the components images will be given to us as
std::string getPixelComponentsProperty (void) const
get the string representing the pixel components
BitDepthEnum getUnmappedPixelDepth (void) const
what is the actual pixel depth of the clip
PixelComponentEnum getUnmappedPixelComponents (void) const
what is the component type of the clip
std::string getUnmappedPixelComponentsProperty (void) const
get the string representing the pixel components
PreMultiplicationEnum getPreMultiplication (void) const
get the components in the image
FieldEnum getFieldOrder (void) const
which spatial field comes first temporally
bool isConnected (void) const
is the clip connected
bool hasContinuousSamples (void) const
can the clip be continuously sampled
double getPixelAspectRatio (void) const
get the scale factor that has been applied to this clip
double getFrameRate (void) const
get the frame rate, in frames per second on this clip, after any clip preferences have been applied
OfxRangeD getFrameRange (void) const
return the range of frames over which this clip has images, after any clip preferences have been applied
double getUnmappedFrameRate (void) const
get the frame rate, in frames per second on this clip, before any clip preferences have been applied
OfxRangeD getUnmappedFrameRange (void) const
return the range of frames over which this clip has images, before any clip preferences have been applied
OfxRectD getRegionOfDefinition (double t)
get the RoD for this clip in the cannonical coordinate system
Image * fetchImage (double t)
fetch an image
Image * fetchImage (double t, OfxRectD bounds)
fetch an image, with a specific region in cannonical coordinates
Image * fetchImage (double t, OfxRectD *bounds)
fetch an image, with a specific region in cannonical coordinates
Protected Member Functions
mDeclareProtectedAssignAndCC (Clip)
Clip (ImageEffect *effect, const std::string &name, OfxImageClipHandle handle, OfxPropertySetHandle props)
hidden constructor
Protected Attributes
std::string _clipName
name of the clip
PropertySet _clipProps
properties for this clip
OfxImageClipHandle _clipHandle
handle for this clip
ImageEffect * _effect
effect instance that owns this clip
Friends
class ImageEffect
so one can be made
Constructor & Destructor Documentation
OFX::Clip::Clip (ImageEffect * effect, const std::string & name, OfxImageClipHandle handle, OfxPropertySetHandle props) [protected]
hidden constructor
References _clipProps, and OFX::Validation::validateClipInstanceProperties().
Member Function Documentation
OFX::Clip::mDeclareProtectedAssignAndCC (Clip) [protected]
const PropertySet& OFX::Clip::getPropertySet () const [inline]
get the underlying property set on this clip
References _clipProps.
PropertySet& OFX::Clip::getPropertySet () [inline]
get the underlying property set on this clip
References _clipProps.
OfxImageClipHandle OFX::Clip::getHandle () [inline]
get the OFX clip handle
References _clipHandle.
const std::string& OFX::Clip::name (void) const [inline]
get the name
References _clipName.
Referenced by OFX::Private::framesNeededAction(), OFX::Private::isIdentityAction(), OFX::Private::regionsOfInterestAction(), OFX::ClipPreferencesSetter::setClipBitDepth(), OFX::ClipPreferencesSetter::setClipComponents(), and OFX::ClipPreferencesSetter::setPixelAspectRatio().
void OFX::Clip::getLabels (std::string & label, std::string & shortLabel, std::string & longLabel) const
fetch the labels
References _clipProps, and OFX::PropertySet::propGetString().
BitDepthEnum OFX::Clip::getPixelDepth (void) const
what is the pixel depth images will be given to us as
get the pixel depth
References _clipName, _clipProps, OFX::eBitDepthNone, OFX::Log::error(), isConnected(), OFX::mapStrToBitDepthEnum(), and OFX::PropertySet::propGetString().
PixelComponentEnum OFX::Clip::getPixelComponents (void) const
what is the components images will be given to us as
get the components in the image
References _clipName, _clipProps, OFX::ePixelComponentNone, OFX::Log::error(), isConnected(), OFX::mapStrToPixelComponentEnum(), and OFX::PropertySet::propGetString().
std::string OFX::Clip::getPixelComponentsProperty (void) const [inline]
get the string representing the pixel components
References _clipProps, and OFX::PropertySet::propGetString().
BitDepthEnum OFX::Clip::getUnmappedPixelDepth (void) const
what is the actual pixel depth of the clip
References _clipName, _clipProps, OFX::eBitDepthNone, OFX::Log::error(), isConnected(), OFX::mapStrToBitDepthEnum(), and OFX::PropertySet::propGetString().
PixelComponentEnum OFX::Clip::getUnmappedPixelComponents (void) const
what is the component type of the clip
References _clipName, _clipProps, OFX::ePixelComponentNone, OFX::Log::error(), isConnected(), OFX::mapStrToPixelComponentEnum(), and OFX::PropertySet::propGetString().
std::string OFX::Clip::getUnmappedPixelComponentsProperty (void) const [inline]
get the string representing the pixel components
References _clipProps, and OFX::PropertySet::propGetString().
PreMultiplicationEnum OFX::Clip::getPreMultiplication (void) const
get the components in the image
References _clipName, _clipProps, OFX::eImageOpaque, OFX::Log::error(), OFX::mapStrToPreMultiplicationEnum(), and OFX::PropertySet::propGetString().
FieldEnum OFX::Clip::getFieldOrder (void) const
which spatial field comes first temporally
References _clipName, _clipProps, OFX::eFieldLower, OFX::eFieldNone, OFX::eFieldUpper, OFX::Log::error(), OFX::mapStrToFieldEnum(), and OFX::PropertySet::propGetString().
bool OFX::Clip::isConnected (void) const
is the clip connected
References _clipProps, and OFX::PropertySet::propGetInt().
Referenced by getPixelComponents(), getPixelDepth(), getUnmappedPixelComponents(), and getUnmappedPixelDepth().
bool OFX::Clip::hasContinuousSamples (void) const
can the clip be continuously sampled
References _clipProps, and OFX::PropertySet::propGetInt().
double OFX::Clip::getPixelAspectRatio (void) const
get the scale factor that has been applied to this clip
References _clipProps, and OFX::PropertySet::propGetDouble().
double OFX::Clip::getFrameRate (void) const
get the frame rate, in frames per second on this clip, after any clip preferences have been applied
References _clipProps, and OFX::PropertySet::propGetDouble().
OfxRangeD OFX::Clip::getFrameRange (void) const
return the range of frames over which this clip has images, after any clip preferences have been applied
References _clipProps, and OFX::PropertySet::propGetDouble().
double OFX::Clip::getUnmappedFrameRate (void) const
get the frame rate, in frames per second on this clip, before any clip preferences have been applied
References _clipProps, and OFX::PropertySet::propGetDouble().
OfxRangeD OFX::Clip::getUnmappedFrameRange (void) const
return the range of frames over which this clip has images, before any clip preferences have been applied
References _clipProps, and OFX::PropertySet::propGetDouble().
OfxRectD OFX::Clip::getRegionOfDefinition (double t)
get the RoD for this clip in the cannonical coordinate system
References _clipHandle, OFX::Private::gEffectSuite, and OFX::throwSuiteStatusException().
Image * OFX::Clip::fetchImage (double t)
fetch an image
When finished with, the client code must delete the image.
If the same image is fetched twice, it must be deleted in each case, they will not be the same pointer.
References _clipHandle, OFX::Private::gEffectSuite, and OFX::throwSuiteStatusException().
Referenced by fetchImage().
Image * OFX::Clip::fetchImage (double t, OfxRectD bounds)
fetch an image, with a specific region in cannonical coordinates
When finished with, the client code must delete the image.
If the same image is fetched twice, it must be deleted in each case, they will not be the same pointer.
References _clipHandle, OFX::Private::gEffectSuite, and OFX::throwSuiteStatusException().
Image* OFX::Clip::fetchImage (double t, OfxRectD * bounds) [inline]
fetch an image, with a specific region in cannonical coordinates
When finished with, the client code must delete the image.
If the same image is fetched twice, it must be deleted in each case, they will not be the same pointer.
References fetchImage().
Friends And Related Function Documentation
friend class ImageEffect [friend]
so one can be made
Member Data Documentation
std::string OFX::Clip::_clipName [protected]
name of the clip
Referenced by getFieldOrder(), getPixelComponents(), getPixelDepth(), getPreMultiplication(), getUnmappedPixelComponents(), getUnmappedPixelDepth(), and name().
PropertySet OFX::Clip::_clipProps [protected]
properties for this clip
Referenced by Clip(), getFieldOrder(), getFrameRange(), getFrameRate(), getLabels(), getPixelAspectRatio(), getPixelComponents(), getPixelComponentsProperty(), getPixelDepth(), getPreMultiplication(), getPropertySet(), getUnmappedFrameRange(), getUnmappedFrameRate(), getUnmappedPixelComponents(), getUnmappedPixelComponentsProperty(), getUnmappedPixelDepth(), hasContinuousSamples(), and isConnected().
OfxImageClipHandle OFX::Clip::_clipHandle [protected]
handle for this clip
Referenced by fetchImage(), getHandle(), and getRegionOfDefinition().
ImageEffect* OFX::Clip::_effect [protected]
effect instance that owns this clip
The documentation for this class was generated from the following files:
ofxsImageEffect.h
ofxsImageEffect.cpp