OFX Support: OFX::ChoiceParamDescriptor Class Reference
OFX::ChoiceParamDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a choice param.
Public Member Functions
void setDefault (int v)
set the default value
void appendOption (const std::string &v)
append an option, default is to have not there
int getNOptions (void)
how many options do we have
void resetOptions (void)
clear all the options so as to add some new ones in
Protected Member Functions
mDeclareProtectedAssignAndCC (ChoiceParamDescriptor)
ChoiceParamDescriptor (void)
ChoiceParamDescriptor (const std::string &name, OfxPropertySetHandle props)
hidden constructor
Friends
class ParamSetDescriptor
Constructor & Destructor Documentation
OFX::ChoiceParamDescriptor::ChoiceParamDescriptor (void) [inline, protected]
OFX::ChoiceParamDescriptor::ChoiceParamDescriptor (const std::string & name, OfxPropertySetHandle props) [protected]
hidden constructor
Member Function Documentation
OFX::ChoiceParamDescriptor::mDeclareProtectedAssignAndCC (ChoiceParamDescriptor) [protected]
void OFX::ChoiceParamDescriptor::setDefault (int v)
set the default value
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::ChoiceParamDescriptor::appendOption (const std::string & v)
append an option, default is to have not there
set the default value
References OFX::ParamDescriptor::_paramProps, OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
int OFX::ChoiceParamDescriptor::getNOptions (void)
how many options do we have
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propGetDimension().
void OFX::ChoiceParamDescriptor::resetOptions (void)
clear all the options so as to add some new ones in
set the default value
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propReset().
Friends And Related Function Documentation
friend class ParamSetDescriptor [friend]
Reimplemented from OFX::ValueParamDescriptor.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp