OFX Support: OFX::ParamSetDescriptor Class Reference
OFX::ParamSetDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Describes a set of properties.
Public Member Functions
virtual ~ParamSetDescriptor ()
dtor
ParamDescriptor * getParamDescriptor (const std::string &name) const
tries to fetch a ParamDescriptor, returns 0 if it isn't there
void setPageParamOrder (PageParamDescriptor &p)
estabilishes the order of page params. Do it by calling it in turn for each page
IntParamDescriptor * defineIntParam (const std::string &name)
Define an integer param.
Int2DParamDescriptor * defineInt2DParam (const std::string &name)
Define a 2D integer param.
Int3DParamDescriptor * defineInt3DParam (const std::string &name)
Define a 3D integer param.
DoubleParamDescriptor * defineDoubleParam (const std::string &name)
Define an double param.
Double2DParamDescriptor * defineDouble2DParam (const std::string &name)
Define a 2D double param.
Double3DParamDescriptor * defineDouble3DParam (const std::string &name)
Define a 3D double param.
StringParamDescriptor * defineStringParam (const std::string &name)
Define a string param.
RGBAParamDescriptor * defineRGBAParam (const std::string &name)
Define a RGBA param.
RGBParamDescriptor * defineRGBParam (const std::string &name)
Define an RGB param.
BooleanParamDescriptor * defineBooleanParam (const std::string &name)
Define a Boolean param.
ChoiceParamDescriptor * defineChoiceParam (const std::string &name)
Define a Choice param.
GroupParamDescriptor * defineGroupParam (const std::string &name)
Define a group param.
PageParamDescriptor * definePageParam (const std::string &name)
Define a Page param.
PushButtonParamDescriptor * definePushButtonParam (const std::string &name)
Define a push button param.
CustomParamDescriptor * defineCustomParam (const std::string &name)
Define a custom param.
Protected Member Functions
mDeclareProtectedAssignAndCC (ParamSetDescriptor)
void defineRawParam (const std::string &name, ParamTypeEnum paramType, OfxPropertySetHandle &props)
calls the raw OFX routine to define a param
template<class T>
bool defineParamDescriptor (const std::string &name, ParamTypeEnum paramType, T *&paramPtr)
Define a param descriptor of the given type.
ParamSetDescriptor (void)
Hidden ctor.
void setParamSetHandle (OfxParamSetHandle h)
set the param set handle
ParamDescriptor * findPreviouslyDefinedParam (const std::string &name)
find a param in the map
Protected Attributes
PropertySet _paramSetProps
Properties that belong to this param set.
OfxParamSetHandle _paramSetHandle
Parameter set handle.
std::map< std::string,
ParamDescriptor * > _definedParams
Set of all previously defined parameters, defined on demand.
Constructor & Destructor Documentation
OFX::ParamSetDescriptor::ParamSetDescriptor (void) [protected]
Hidden ctor.
hidden ctor
OFX::ParamSetDescriptor::~ParamSetDescriptor () [virtual]
dtor
References _definedParams.
Member Function Documentation
OFX::ParamSetDescriptor::mDeclareProtectedAssignAndCC (ParamSetDescriptor) [protected]
void OFX::ParamSetDescriptor::defineRawParam (const std::string & name, ParamTypeEnum paramType, OfxPropertySetHandle & props) [protected]
calls the raw OFX routine to define a param
References _paramSetHandle, OFX::Private::gParamSuite, OFX::mapParamTypeEnumToString(), and OFX::throwSuiteStatusException().
Referenced by defineParamDescriptor().
template<class T> bool OFX::ParamSetDescriptor::defineParamDescriptor (const std::string & name, ParamTypeEnum paramType, T *& paramPtr) [inline, protected]
Define a param descriptor of the given type.
References _definedParams, defineRawParam(), and findPreviouslyDefinedParam().
Referenced by defineBooleanParam(), defineChoiceParam(), defineCustomParam(), defineDouble2DParam(), defineDouble3DParam(), defineDoubleParam(), defineGroupParam(), defineInt2DParam(), defineInt3DParam(), defineIntParam(), definePageParam(), definePushButtonParam(), defineRGBAParam(), defineRGBParam(), and defineStringParam().
void OFX::ParamSetDescriptor::setParamSetHandle (OfxParamSetHandle h) [protected]
set the param set handle
References _paramSetHandle, _paramSetProps, OFX::Private::gParamSuite, OFX::PropertySet::propSetHandle(), and OFX::throwSuiteStatusException().
Referenced by OFX::ImageEffectDescriptor::ImageEffectDescriptor().
ParamDescriptor * OFX::ParamSetDescriptor::findPreviouslyDefinedParam (const std::string & name) [protected]
find a param in the map
if a param has been defined in this set, go find it
References _definedParams.
Referenced by defineParamDescriptor().
ParamDescriptor * OFX::ParamSetDescriptor::getParamDescriptor (const std::string & name) const
tries to fetch a ParamDescriptor, returns 0 if it isn't there
References _definedParams.
void OFX::ParamSetDescriptor::setPageParamOrder (PageParamDescriptor & p)
estabilishes the order of page params. Do it by calling it in turn for each page
References _paramSetProps, OFX::ParamDescriptor::getName(), OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
IntParamDescriptor * OFX::ParamSetDescriptor::defineIntParam (const std::string & name)
Define an integer param.
Define an integer param, only callable from describe in context.
References defineParamDescriptor(), and OFX::eIntParam.
Int2DParamDescriptor * OFX::ParamSetDescriptor::defineInt2DParam (const std::string & name)
Define a 2D integer param.
References defineParamDescriptor(), and OFX::eInt2DParam.
Int3DParamDescriptor * OFX::ParamSetDescriptor::defineInt3DParam (const std::string & name)
Define a 3D integer param.
References defineParamDescriptor(), and OFX::eInt3DParam.
DoubleParamDescriptor * OFX::ParamSetDescriptor::defineDoubleParam (const std::string & name)
Define an double param.
Define an double param, only callable from describe in context.
References defineParamDescriptor(), and OFX::eDoubleParam.
Double2DParamDescriptor * OFX::ParamSetDescriptor::defineDouble2DParam (const std::string & name)
Define a 2D double param.
References defineParamDescriptor(), and OFX::eDouble2DParam.
Double3DParamDescriptor * OFX::ParamSetDescriptor::defineDouble3DParam (const std::string & name)
Define a 3D double param.
References defineParamDescriptor(), and OFX::eDouble3DParam.
StringParamDescriptor * OFX::ParamSetDescriptor::defineStringParam (const std::string & name)
Define a string param.
References defineParamDescriptor(), and OFX::eStringParam.
RGBAParamDescriptor * OFX::ParamSetDescriptor::defineRGBAParam (const std::string & name)
Define a RGBA param.
References defineParamDescriptor(), and OFX::eRGBAParam.
RGBParamDescriptor * OFX::ParamSetDescriptor::defineRGBParam (const std::string & name)
Define an RGB param.
References defineParamDescriptor(), and OFX::eRGBParam.
BooleanParamDescriptor * OFX::ParamSetDescriptor::defineBooleanParam (const std::string & name)
Define a Boolean param.
References defineParamDescriptor(), and OFX::eBooleanParam.
ChoiceParamDescriptor * OFX::ParamSetDescriptor::defineChoiceParam (const std::string & name)
Define a Choice param.
References defineParamDescriptor(), and OFX::eChoiceParam.
GroupParamDescriptor * OFX::ParamSetDescriptor::defineGroupParam (const std::string & name)
Define a group param.
References defineParamDescriptor(), and OFX::eGroupParam.
PageParamDescriptor * OFX::ParamSetDescriptor::definePageParam (const std::string & name)
Define a Page param.
References defineParamDescriptor(), and OFX::ePageParam.
PushButtonParamDescriptor * OFX::ParamSetDescriptor::definePushButtonParam (const std::string & name)
Define a push button param.
Define a push button param.
References defineParamDescriptor(), and OFX::ePushButtonParam.
CustomParamDescriptor * OFX::ParamSetDescriptor::defineCustomParam (const std::string & name)
Define a custom param.
References defineParamDescriptor(), and OFX::eCustomParam.
Member Data Documentation
PropertySet OFX::ParamSetDescriptor::_paramSetProps [protected]
Properties that belong to this param set.
Referenced by setPageParamOrder(), and setParamSetHandle().
OfxParamSetHandle OFX::ParamSetDescriptor::_paramSetHandle [protected]
Parameter set handle.
Referenced by defineRawParam(), and setParamSetHandle().
std::map<std::string, ParamDescriptor *> OFX::ParamSetDescriptor::_definedParams [protected]
Set of all previously defined parameters, defined on demand.
Referenced by defineParamDescriptor(), findPreviouslyDefinedParam(), getParamDescriptor(), and ~ParamSetDescriptor().
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp