OFX Support: OFX::ClipDescriptor Class Reference
OFX::ClipDescriptor Class Reference
#include <ofxsImageEffect.h>
Detailed Description
Wraps up a clip.
Public Member Functions
const PropertySet & getPropertySet () const
PropertySet & getPropertySet ()
void setLabels (const std::string &label, const std::string &shortLabel, const std::string &longLabel)
set the label properties
void setFieldExtraction (FieldExtractionEnum v)
set how fielded images are extracted from the clip defaults to eFieldExtractDoubled
void addSupportedComponent (PixelComponentEnum v)
set which components are supported, defaults to none set, this must be called at least once!
void addSupportedComponent (const std::string &comp)
set which components are supported. This version adds by the raw C-string label, allowing you to add custom component types
void setTemporalClipAccess (bool v)
say whether we are going to do random temporal access on this clip, defaults to false
void setOptional (bool v)
say whether if the clip is optional, defaults to false
void setSupportsTiles (bool v)
say whether this clip supports tiling, defaults to true
void setIsMask (bool v)
say whether this clip is a 'mask', so the host can know to replace with a roto or similar, defaults to false
Protected Member Functions
mDeclareProtectedAssignAndCC (ClipDescriptor)
ClipDescriptor (void)
ClipDescriptor (const std::string &name, OfxPropertySetHandle props)
hidden constructor
Protected Attributes
std::string _clipName
name of the clip
PropertySet _clipProps
properties for this clip
Friends
class ImageEffectDescriptor
Constructor & Destructor Documentation
OFX::ClipDescriptor::ClipDescriptor (void) [inline, protected]
OFX::ClipDescriptor::ClipDescriptor (const std::string & name, OfxPropertySetHandle props) [protected]
hidden constructor
References OFX::Validation::validateClipDescriptorProperties().
Member Function Documentation
OFX::ClipDescriptor::mDeclareProtectedAssignAndCC (ClipDescriptor) [protected]
const PropertySet& OFX::ClipDescriptor::getPropertySet () const [inline]
References _clipProps.
PropertySet& OFX::ClipDescriptor::getPropertySet () [inline]
References _clipProps.
void OFX::ClipDescriptor::setLabels (const std::string & label, const std::string & shortLabel, const std::string & longLabel)
set the label properties
References _clipProps, and OFX::PropertySet::propSetString().
void OFX::ClipDescriptor::setFieldExtraction (FieldExtractionEnum v)
set how fielded images are extracted from the clip defaults to eFieldExtractDoubled
References _clipProps, OFX::eFieldExtractBoth, OFX::eFieldExtractDoubled, OFX::eFieldExtractSingle, and OFX::PropertySet::propSetString().
void OFX::ClipDescriptor::addSupportedComponent (PixelComponentEnum v)
set which components are supported, defaults to none set, this must be called at least once!
References _clipProps, OFX::ePixelComponentAlpha, OFX::ePixelComponentRGBA, OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
void OFX::ClipDescriptor::addSupportedComponent (const std::string & comp)
set which components are supported. This version adds by the raw C-string label, allowing you to add custom component types
set which components are supported, defaults to none set, this must be called at least once!
References _clipProps, OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
void OFX::ClipDescriptor::setTemporalClipAccess (bool v)
say whether we are going to do random temporal access on this clip, defaults to false
References _clipProps, and OFX::PropertySet::propSetInt().
void OFX::ClipDescriptor::setOptional (bool v)
say whether if the clip is optional, defaults to false
References _clipProps, and OFX::PropertySet::propSetInt().
void OFX::ClipDescriptor::setSupportsTiles (bool v)
say whether this clip supports tiling, defaults to true
References _clipProps, and OFX::PropertySet::propSetInt().
void OFX::ClipDescriptor::setIsMask (bool v)
say whether this clip is a 'mask', so the host can know to replace with a roto or similar, defaults to false
References _clipProps, and OFX::PropertySet::propSetInt().
Friends And Related Function Documentation
friend class ImageEffectDescriptor [friend]
Member Data Documentation
std::string OFX::ClipDescriptor::_clipName [protected]
name of the clip
PropertySet OFX::ClipDescriptor::_clipProps [protected]
properties for this clip
Referenced by addSupportedComponent(), getPropertySet(), setFieldExtraction(), setIsMask(), setLabels(), setOptional(), setSupportsTiles(), and setTemporalClipAccess().
The documentation for this class was generated from the following files:
ofxsImageEffect.h
ofxsImageEffect.cpp