OFX Support: OFX::PropertySet Class Reference
OFX::PropertySet Class Reference
#include <ofxsCore.h>
Detailed Description
This class wraps up an OFX property set.
Public Member Functions
PropertySet (OfxPropertySetHandle h=0)
construct a property set
virtual ~PropertySet ()
Virtual destructor.
void propSetHandle (OfxPropertySetHandle h)
set the handle to use for this set
OfxPropertySetHandle propSetHandle (void)
return the handle for this property set
int propGetDimension (const char *property, bool throwOnFailure=true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, returns the dimension of the given property from this property set
void propReset (const char *property) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, resets the property to it's default value
void propSetPointer (const char *property, void *value, int idx, bool throwOnFailure=true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, Set a single dimension pointer property
void propSetString (const char *property, const std::string &value, int idx, bool throwOnFailure=true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, Set a single dimension string property
void propSetDouble (const char *property, double value, int idx, bool throwOnFailure=true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, Set a single dimension double property
void propSetInt (const char *property, int value, int idx, bool throwOnFailure=true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, Set a single dimension int property
void propSetPointer (const char *property, void *value, bool throwOnFailure=true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
void propSetString (const char *property, const std::string &value, bool throwOnFailure=true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
void propSetDouble (const char *property, double value, bool throwOnFailure=true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
void propSetInt (const char *property, int value, bool throwOnFailure=true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
void * propGetPointer (const char *property, int idx, bool throwOnFailure=true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get a pointer property
std::string propGetString (const char *property, int idx, bool throwOnFailure=true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get a string property
double propGetDouble (const char *property, int idx, bool throwOnFailure=true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get a double property
int propGetInt (const char *property, int idx, bool throwOnFailure=true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get an int property
void * propGetPointer (const char *property, bool throwOnFailure=true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get a string property with index 0
std::string propGetString (const char *property, bool throwOnFailure=true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get a string property with index 0
double propGetDouble (const char *property, bool throwOnFailure=true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get a double property with index 0
int propGetInt (const char *property, bool throwOnFailure=true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get an int property with index 0
Static Public Member Functions
static void propEnableLogging (void)
turns on logging of property access functions
static void propDisableLogging (void)
turns off logging of property access functions
static void setThrowOnUnsupportedProperties (bool v)
Do we throw an exception if a host returns 'unsupported' when setting a property. Default is true.
static bool getThrowOnUnsupportedProperties (void)
Do we throw an exception if a host returns 'unsupported' when setting a property. Default is true.
Protected Attributes
OfxPropertySetHandle _propHandle
The raw property handle.
Static Protected Attributes
static int _gPropLogging = 1
Class static, whether we are logging each property action.
static bool _gThrowOnUnsupported = true
Do not throw an exception if a host returns 'unsupported' when setting a property.
Constructor & Destructor Documentation
OFX::PropertySet::PropertySet (OfxPropertySetHandle h = 0) [inline]
construct a property set
OFX::PropertySet::~PropertySet () [virtual]
Virtual destructor.
Member Function Documentation
static void OFX::PropertySet::propEnableLogging (void) [inline, static]
turns on logging of property access functions
References _gPropLogging.
static void OFX::PropertySet::propDisableLogging (void) [inline, static]
turns off logging of property access functions
References _gPropLogging.
static void OFX::PropertySet::setThrowOnUnsupportedProperties (bool v) [inline, static]
Do we throw an exception if a host returns 'unsupported' when setting a property. Default is true.
References _gThrowOnUnsupported.
static bool OFX::PropertySet::getThrowOnUnsupportedProperties (void) [inline, static]
Do we throw an exception if a host returns 'unsupported' when setting a property. Default is true.
References _gThrowOnUnsupported.
Referenced by OFX::throwPropertyException().
void OFX::PropertySet::propSetHandle (OfxPropertySetHandle h) [inline]
set the handle to use for this set
References _propHandle.
Referenced by OFX::ImageEffectDescriptor::ImageEffectDescriptor(), OFX::Interact::Interact(), OFX::Param::Param(), OFX::ParamSet::setParamSetHandle(), OFX::ParamSetDescriptor::setParamSetHandle(), and OFX::Image::~Image().
OfxPropertySetHandle OFX::PropertySet::propSetHandle (void) [inline]
return the handle for this property set
References _propHandle.
int OFX::PropertySet::propGetDimension (const char * property, bool throwOnFailure = true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, returns the dimension of the given property from this property set
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by OFX::PageParamDescriptor::addChild(), OFX::ImageEffectDescriptor::addClipPreferencesSlaveParam(), OFX::Interact::addParamToSlaveTo(), OFX::ImageEffectDescriptor::addSupportedBitDepth(), OFX::ClipDescriptor::addSupportedComponent(), OFX::ImageEffectDescriptor::addSupportedContext(), OFX::ChoiceParam::appendOption(), OFX::ChoiceParamDescriptor::appendOption(), OFX::Private::fetchHostDescription(), OFX::ChoiceParam::getNOptions(), OFX::ChoiceParamDescriptor::getNOptions(), and OFX::ParamSetDescriptor::setPageParamOrder().
void OFX::PropertySet::propReset (const char * property) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, resets the property to it's default value
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by OFX::Interact::removeParamToSlaveTo(), OFX::ChoiceParam::resetOptions(), and OFX::ChoiceParamDescriptor::resetOptions().
void OFX::PropertySet::propSetPointer (const char * property, void * value, int idx, bool throwOnFailure = true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, Set a single dimension pointer property
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by OFX::ImageEffect::ImageEffect(), OFX::Interact::Interact(), propSetPointer(), OFX::ValueParamDescriptor::setInteractDescriptor(), OFX::ImageEffectDescriptor::setOverlayInteractDescriptor(), and OFX::ImageEffect::~ImageEffect().
void OFX::PropertySet::propSetString (const char * property, const std::string & value, int idx, bool throwOnFailure = true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, Set a single dimension string property
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by OFX::PageParamDescriptor::addChild(), OFX::ImageEffectDescriptor::addClipPreferencesSlaveParam(), OFX::Interact::addParamToSlaveTo(), OFX::ImageEffectDescriptor::addSupportedBitDepth(), OFX::ClipDescriptor::addSupportedComponent(), OFX::ImageEffectDescriptor::addSupportedContext(), OFX::ChoiceParam::appendOption(), OFX::ChoiceParamDescriptor::appendOption(), OFX::Private::isIdentityAction(), propSetString(), OFX::Interact::removeParamToSlaveTo(), OFX::ValueParamDescriptor::setCacheInvalidation(), OFX::ClipPreferencesSetter::setClipBitDepth(), OFX::ClipPreferencesSetter::setClipComponents(), OFX::CustomParam::setDefault(), OFX::StringParam::setDefault(), OFX::CustomParamDescriptor::setDefault(), OFX::StringParamDescriptor::setDefault(), OFX::Double3DParamDescriptor::setDimensionLabels(), OFX::Double2DParamDescriptor::setDimensionLabels(), OFX::Int3DParamDescriptor::setDimensionLabels(), OFX::Int2DParamDescriptor::setDimensionLabels(), OFX::BaseDoubleParamDescriptor::setDoubleType(), OFX::ClipDescriptor::setFieldExtraction(), OFX::Param::setHint(), OFX::ParamDescriptor::setHint(), OFX::Param::setLabels(), OFX::ParamDescriptor::setLabels(), OFX::ImageEffectDescriptor::setLabels(), OFX::ClipDescriptor::setLabels(), OFX::ClipPreferencesSetter::setOutputFielding(), OFX::ClipPreferencesSetter::setOutputPremultiplication(), OFX::ParamSetDescriptor::setPageParamOrder(), OFX::ParamDescriptor::setParent(), OFX::ImageEffectDescriptor::setPluginGrouping(), OFX::ImageEffectDescriptor::setRenderThreadSafety(), OFX::ParamDescriptor::setScriptName(), and OFX::StringParamDescriptor::setStringType().
void OFX::PropertySet::propSetDouble (const char * property, double value, int idx, bool throwOnFailure = true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, Set a single dimension double property
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by OFX::Private::getTimeDomainAction(), OFX::Private::isIdentityAction(), propSetDouble(), OFX::Private::regionOfDefinitionAction(), OFX::RGBAParam::setDefault(), OFX::RGBParam::setDefault(), OFX::Double3DParam::setDefault(), OFX::Double2DParam::setDefault(), OFX::DoubleParam::setDefault(), OFX::RGBAParamDescriptor::setDefault(), OFX::RGBParamDescriptor::setDefault(), OFX::Double3DParamDescriptor::setDefault(), OFX::Double2DParamDescriptor::setDefault(), OFX::DoubleParamDescriptor::setDefault(), OFX::Double3DParam::setDisplayRange(), OFX::Double2DParam::setDisplayRange(), OFX::DoubleParam::setDisplayRange(), OFX::Double3DParamDescriptor::setDisplayRange(), OFX::Double2DParamDescriptor::setDisplayRange(), OFX::DoubleParamDescriptor::setDisplayRange(), OFX::BaseDoubleParam::setIncrement(), OFX::BaseDoubleParamDescriptor::setIncrement(), OFX::ParamInteractDescriptor::setInteractSizeAspect(), OFX::ClipPreferencesSetter::setOutputFrameRate(), OFX::ClipPreferencesSetter::setPixelAspectRatio(), OFX::Double3DParam::setRange(), OFX::Double2DParam::setRange(), OFX::DoubleParam::setRange(), OFX::Double3DParamDescriptor::setRange(), OFX::Double2DParamDescriptor::setRange(), and OFX::DoubleParamDescriptor::setRange().
void OFX::PropertySet::propSetInt (const char * property, int value, int idx, bool throwOnFailure = true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
, Set a single dimension int property
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by propSetInt(), OFX::ValueParamDescriptor::setAnimates(), OFX::ValueParamDescriptor::setCanUndo(), OFX::ChoiceParam::setDefault(), OFX::BooleanParam::setDefault(), OFX::Int3DParam::setDefault(), OFX::Int2DParam::setDefault(), OFX::IntParam::setDefault(), OFX::ChoiceParamDescriptor::setDefault(), OFX::BooleanParamDescriptor::setDefault(), OFX::Int3DParamDescriptor::setDefault(), OFX::Int2DParamDescriptor::setDefault(), OFX::IntParamDescriptor::setDefault(), OFX::BaseDoubleParam::setDigits(), OFX::BaseDoubleParamDescriptor::setDigits(), OFX::Int3DParam::setDisplayRange(), OFX::Int2DParam::setDisplayRange(), OFX::IntParam::setDisplayRange(), OFX::Int3DParamDescriptor::setDisplayRange(), OFX::Int2DParamDescriptor::setDisplayRange(), OFX::IntParamDescriptor::setDisplayRange(), OFX::Param::setEnabled(), OFX::ParamDescriptor::setEnabled(), OFX::ValueParam::setEvaluateOnChange(), OFX::ValueParamDescriptor::setEvaluateOnChange(), OFX::StringParamDescriptor::setFilePathExists(), OFX::ImageEffectDescriptor::setHostFrameThreading(), OFX::ParamInteractDescriptor::setInteractMinimumSize(), OFX::ParamInteractDescriptor::setInteractPreferredSize(), OFX::ClipDescriptor::setIsMask(), OFX::ValueParamDescriptor::setIsPersistant(), OFX::Param::setIsSecret(), OFX::ParamDescriptor::setIsSecret(), OFX::ClipDescriptor::setOptional(), OFX::ClipPreferencesSetter::setOutputFrameVarying(), OFX::ClipPreferencesSetter::setOutputHasContinousSamples(), OFX::Int3DParam::setRange(), OFX::Int2DParam::setRange(), OFX::IntParam::setRange(), OFX::Int3DParamDescriptor::setRange(), OFX::Int2DParamDescriptor::setRange(), OFX::IntParamDescriptor::setRange(), OFX::ImageEffectDescriptor::setRenderTwiceAlways(), OFX::ImageEffect::setSequentialRender(), OFX::ImageEffectDescriptor::setSingleInstance(), OFX::ImageEffectDescriptor::setSupportsMultipleClipDepths(), OFX::ImageEffectDescriptor::setSupportsMultipleClipPARs(), OFX::ImageEffectDescriptor::setSupportsMultiResolution(), OFX::ImageEffectDescriptor::setSupportsTiles(), OFX::ClipDescriptor::setSupportsTiles(), OFX::ImageEffectDescriptor::setTemporalClipAccess(), and OFX::ClipDescriptor::setTemporalClipAccess().
void OFX::PropertySet::propSetPointer (const char * property, void * value, bool throwOnFailure = true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite) [inline]
References propSetPointer().
void OFX::PropertySet::propSetString (const char * property, const std::string & value, bool throwOnFailure = true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite) [inline]
References propSetString().
void OFX::PropertySet::propSetDouble (const char * property, double value, bool throwOnFailure = true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite) [inline]
References propSetDouble().
void OFX::PropertySet::propSetInt (const char * property, int value, bool throwOnFailure = true) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite) [inline]
References propSetInt().
void * OFX::PropertySet::propGetPointer (const char * property, int idx, bool throwOnFailure = true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get a pointer property
Get single pointer property.
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by OFX::Image::Image(), propGetPointer(), OFX::retrieveEffectFromInteractHandle(), OFX::Private::retrieveImageEffectPointer(), and OFX::Private::retrieveInteractPointer().
std::string OFX::PropertySet::propGetString (const char * property, int idx, bool throwOnFailure = true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get a string property
Get single string property.
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by OFX::Private::beginInstanceChangedAction(), OFX::Private::endInstanceChangedAction(), OFX::Private::fetchHostDescription(), OFX::ValueParam::getCacheInvalidation(), OFX::CustomParam::getDefault(), OFX::StringParam::getDefault(), OFX::BaseDoubleParam::getDoubleType(), OFX::Clip::getFieldOrder(), OFX::Param::getHint(), OFX::Param::getLabels(), OFX::Clip::getLabels(), OFX::ParamSet::getParam(), OFX::ParamSet::getParamType(), OFX::Param::getParent(), OFX::Clip::getPixelComponents(), OFX::Clip::getPixelComponentsProperty(), OFX::Image::getPixelComponentsProperty(), OFX::Clip::getPixelDepth(), OFX::Clip::getPreMultiplication(), OFX::Private::getRenderActionArguments(), OFX::Param::getScriptName(), OFX::Clip::getUnmappedPixelComponents(), OFX::Clip::getUnmappedPixelComponentsProperty(), OFX::Clip::getUnmappedPixelDepth(), OFX::Image::Image(), OFX::ImageEffect::ImageEffect(), OFX::Private::instanceChangedAction(), OFX::KeyArgs::KeyArgs(), OFX::Private::mainEntryStr(), and propGetString().
double OFX::PropertySet::propGetDouble (const char * property, int idx, bool throwOnFailure = true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get a double property
Get single double property.
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by OFX::Private::beginSequenceRenderAction(), OFX::Private::endSequenceRenderAction(), OFX::Private::framesNeededAction(), OFX::getBackgroundColour(), OFX::RGBAParam::getDefault(), OFX::RGBParam::getDefault(), OFX::Double3DParam::getDefault(), OFX::Double2DParam::getDefault(), OFX::DoubleParam::getDefault(), OFX::Double3DParam::getDisplayRange(), OFX::Double2DParam::getDisplayRange(), OFX::DoubleParam::getDisplayRange(), OFX::ImageEffect::getEffectDuration(), OFX::Clip::getFrameRange(), OFX::ImageEffect::getFrameRate(), OFX::Clip::getFrameRate(), OFX::BaseDoubleParam::getIncrement(), OFX::Clip::getPixelAspectRatio(), OFX::Interact::getPixelScale(), OFX::getPixelScale(), OFX::ImageEffect::getProjectExtent(), OFX::ImageEffect::getProjectOffset(), OFX::ImageEffect::getProjectPixelAspectRatio(), OFX::ImageEffect::getProjectSize(), OFX::Double3DParam::getRange(), OFX::Double2DParam::getRange(), OFX::DoubleParam::getRange(), OFX::Private::getRenderActionArguments(), OFX::getRenderScale(), OFX::Clip::getUnmappedFrameRange(), OFX::Clip::getUnmappedFrameRate(), OFX::Image::Image(), OFX::Private::instanceChangedAction(), OFX::InteractArgs::InteractArgs(), OFX::KeyArgs::KeyArgs(), OFX::PenArgs::PenArgs(), propGetDouble(), OFX::Private::regionOfDefinitionAction(), and OFX::Private::regionsOfInterestAction().
int OFX::PropertySet::propGetInt (const char * property, int idx, bool throwOnFailure = true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
get an int property
Get single int property.
References OFX::Log::error(), OFX::Private::gPropSuite, OFX::mapStatusToString(), OFX::Log::print(), and OFX::throwPropertyException().
Referenced by OFX::Private::beginSequenceRenderAction(), OFX::Private::endSequenceRenderAction(), OFX::Private::fetchHostDescription(), OFX::Interact::getBitDepth(), OFX::ChoiceParam::getDefault(), OFX::BooleanParam::getDefault(), OFX::Int3DParam::getDefault(), OFX::Int2DParam::getDefault(), OFX::IntParam::getDefault(), OFX::BaseDoubleParam::getDigits(), OFX::Int3DParam::getDisplayRange(), OFX::Int2DParam::getDisplayRange(), OFX::IntParam::getDisplayRange(), OFX::ValueParam::getEvaluateOnChange(), OFX::ParamInteract::getInteractSize(), OFX::ValueParam::getIsAnimating(), OFX::ValueParam::getIsAutoKeying(), OFX::Param::getIsEnable(), OFX::ValueParam::getIsPersistant(), OFX::Param::getIsSecret(), OFX::Int3DParam::getRange(), OFX::Int2DParam::getRange(), OFX::IntParam::getRange(), OFX::Private::getRenderActionArguments(), OFX::ImageEffect::getSequentialRender(), OFX::Interact::hasAlpha(), OFX::Clip::hasContinuousSamples(), OFX::Image::Image(), OFX::Clip::isConnected(), OFX::ImageEffect::isInteractive(), and propGetInt().
void* OFX::PropertySet::propGetPointer (const char * property, bool throwOnFailure = true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite) [inline]
get a string property with index 0
References propGetPointer().
std::string OFX::PropertySet::propGetString (const char * property, bool throwOnFailure = true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite) [inline]
get a string property with index 0
References propGetString().
double OFX::PropertySet::propGetDouble (const char * property, bool throwOnFailure = true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite) [inline]
get a double property with index 0
References propGetDouble().
int OFX::PropertySet::propGetInt (const char * property, bool throwOnFailure = true) const throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite) [inline]
get an int property with index 0
References propGetInt().
Member Data Documentation
OfxPropertySetHandle OFX::PropertySet::_propHandle [protected]
The raw property handle.
Referenced by propSetHandle().
int OFX::PropertySet::_gPropLogging = 1 [static, protected]
Class static, whether we are logging each property action.
are we logging property get/set
Referenced by propDisableLogging(), and propEnableLogging().
bool OFX::PropertySet::_gThrowOnUnsupported = true [static, protected]
Do not throw an exception if a host returns 'unsupported' when setting a property.
Do we throw an exception if a host returns 'unsupported' when setting a property.
Referenced by getThrowOnUnsupportedProperties(), and setThrowOnUnsupportedProperties().
The documentation for this class was generated from the following files:
ofxsCore.h
ofxsProperty.cpp