OFX Support: OFX::ParamSet Class Reference
OFX::ParamSet Class Reference
#include <ofxsParam.h>
Detailed Description
A set of parameters in a plugin instance.
Public Member Functions
virtual ~ParamSet ()
dtor
bool paramExists (const std::string &name) const
void beginEditBlock (const std::string &name)
open an undoblock
void endEditBlock ()
close an undoblock
Param * getParam (const std::string &name) const
IntParam * fetchIntParam (const std::string &name) const
Fetch an integer param.
Int2DParam * fetchInt2DParam (const std::string &name) const
Fetch a 2D integer param.
Int3DParam * fetchInt3DParam (const std::string &name) const
Fetch a 3D integer param.
DoubleParam * fetchDoubleParam (const std::string &name) const
Fetch an double param.
Double2DParam * fetchDouble2DParam (const std::string &name) const
Fetch a 2D double param.
Double3DParam * fetchDouble3DParam (const std::string &name) const
Fetch a 3D double param.
StringParam * fetchStringParam (const std::string &name) const
Fetch a string param.
RGBAParam * fetchRGBAParam (const std::string &name) const
Fetch a RGBA param.
RGBParam * fetchRGBParam (const std::string &name) const
Fetch an RGB param.
BooleanParam * fetchBooleanParam (const std::string &name) const
Fetch a Boolean param.
ChoiceParam * fetchChoiceParam (const std::string &name) const
Fetch a Choice param.
GroupParam * fetchGroupParam (const std::string &name) const
Fetch a group param.
PageParam * fetchPageParam (const std::string &name) const
Fetch a page param.
PushButtonParam * fetchPushButtonParam (const std::string &name) const
Fetch a push button param.
CustomParam * fetchCustomParam (const std::string &name) const
Fetch a custom param.
Protected Member Functions
mDeclareProtectedAssignAndCC (ParamSet)
ParamTypeEnum getParamType (const std::string &name) const
ParamSet (void)
Hidden ctor.
void setParamSetHandle (OfxParamSetHandle h)
set the param set handle
Constructor & Destructor Documentation
OFX::ParamSet::ParamSet (void) [protected]
Hidden ctor.
hidden ctor
OFX::ParamSet::~ParamSet () [virtual]
dtor
Member Function Documentation
OFX::ParamSet::mDeclareProtectedAssignAndCC (ParamSet) [protected]
ParamTypeEnum OFX::ParamSet::getParamType (const std::string & name) const [protected]
References OFX::Private::gParamSuite, OFX::mapParamTypeStringToEnum(), OFX::PropertySet::propGetString(), and OFX::throwSuiteStatusException().
void OFX::ParamSet::setParamSetHandle (OfxParamSetHandle h) [protected]
set the param set handle
References OFX::Private::gParamSuite, OFX::PropertySet::propSetHandle(), and OFX::throwSuiteStatusException().
Referenced by OFX::ImageEffect::ImageEffect().
bool OFX::ParamSet::paramExists (const std::string & name) const
References OFX::Private::gParamSuite.
void OFX::ParamSet::beginEditBlock (const std::string & name)
open an undoblock
References OFX::Private::gParamSuite.
void OFX::ParamSet::endEditBlock ()
close an undoblock
References OFX::Private::gParamSuite.
Param * OFX::ParamSet::getParam (const std::string & name) const
References OFX::eBooleanParam, OFX::eChoiceParam, OFX::eCustomParam, OFX::eDouble2DParam, OFX::eDouble3DParam, OFX::eDoubleParam, OFX::eGroupParam, OFX::eInt2DParam, OFX::eInt3DParam, OFX::eIntParam, OFX::ePageParam, OFX::ePushButtonParam, OFX::eRGBAParam, OFX::eRGBParam, OFX::eStringParam, OFX::Private::gParamSuite, OFX::mapParamTypeStringToEnum(), OFX::PropertySet::propGetString(), and OFX::throwSuiteStatusException().
IntParam * OFX::ParamSet::fetchIntParam (const std::string & name) const
Fetch an integer param.
Fetch an integer param, only callable from describe in context.
References OFX::eIntParam.
Int2DParam * OFX::ParamSet::fetchInt2DParam (const std::string & name) const
Fetch a 2D integer param.
References OFX::eInt2DParam.
Int3DParam * OFX::ParamSet::fetchInt3DParam (const std::string & name) const
Fetch a 3D integer param.
References OFX::eInt3DParam.
DoubleParam * OFX::ParamSet::fetchDoubleParam (const std::string & name) const
Fetch an double param.
Fetch an double param, only callable from describe in context.
References OFX::eDoubleParam.
Double2DParam * OFX::ParamSet::fetchDouble2DParam (const std::string & name) const
Fetch a 2D double param.
References OFX::eDouble2DParam.
Double3DParam * OFX::ParamSet::fetchDouble3DParam (const std::string & name) const
Fetch a 3D double param.
References OFX::eDouble3DParam.
StringParam * OFX::ParamSet::fetchStringParam (const std::string & name) const
Fetch a string param.
References OFX::eStringParam.
RGBAParam * OFX::ParamSet::fetchRGBAParam (const std::string & name) const
Fetch a RGBA param.
References OFX::eRGBAParam.
RGBParam * OFX::ParamSet::fetchRGBParam (const std::string & name) const
Fetch an RGB param.
References OFX::eRGBParam.
BooleanParam * OFX::ParamSet::fetchBooleanParam (const std::string & name) const
Fetch a Boolean param.
References OFX::eBooleanParam.
ChoiceParam * OFX::ParamSet::fetchChoiceParam (const std::string & name) const
Fetch a Choice param.
References OFX::eChoiceParam.
GroupParam * OFX::ParamSet::fetchGroupParam (const std::string & name) const
Fetch a group param.
References OFX::eGroupParam.
Referenced by OFX::Param::getParent().
PageParam * OFX::ParamSet::fetchPageParam (const std::string & name) const
Fetch a page param.
Fetch a Page param.
References OFX::ePageParam.
PushButtonParam * OFX::ParamSet::fetchPushButtonParam (const std::string & name) const
Fetch a push button param.
Fetch a push button param.
References OFX::ePushButtonParam.
CustomParam * OFX::ParamSet::fetchCustomParam (const std::string & name) const
Fetch a custom param.
References OFX::eCustomParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp