OFX Support: OFX::Int2DParamDescriptor Class Reference
OFX::Int2DParamDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up an 2d integer param.
Public Member Functions
void setDimensionLabels (const std::string &x, const std::string &y)
set the dimension labels
void setDefault (int x, int y)
set the default value, default is 0
void setRange (int minX, int minY, int maxX, int maxY)
set the hard min/max range, default is INT_MIN, INT_MAX
void setDisplayRange (int minX, int minY, int maxX, int maxY)
set the display min and max, default is to be the same as the range param
Protected Member Functions
mDeclareProtectedAssignAndCC (Int2DParamDescriptor)
Int2DParamDescriptor (void)
Int2DParamDescriptor (const std::string &name, OfxPropertySetHandle props)
hidden constructor
Friends
class ParamSetDescriptor
Constructor & Destructor Documentation
OFX::Int2DParamDescriptor::Int2DParamDescriptor (void) [inline, protected]
OFX::Int2DParamDescriptor::Int2DParamDescriptor (const std::string & name, OfxPropertySetHandle props) [protected]
hidden constructor
ctor
Member Function Documentation
OFX::Int2DParamDescriptor::mDeclareProtectedAssignAndCC (Int2DParamDescriptor) [protected]
void OFX::Int2DParamDescriptor::setDimensionLabels (const std::string & x, const std::string & y)
set the dimension labels
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetString().
void OFX::Int2DParamDescriptor::setDefault (int x, int y)
set the default value, default is 0
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::Int2DParamDescriptor::setRange (int minX, int minY, int maxX, int maxY)
set the hard min/max range, default is INT_MIN, INT_MAX
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::Int2DParamDescriptor::setDisplayRange (int minX, int minY, int maxX, int maxY)
set the display min and max, default is to be the same as the range param
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
Friends And Related Function Documentation
friend class ParamSetDescriptor [friend]
Reimplemented from OFX::ValueParamDescriptor.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp