OFX Support: OFX::MultiThread::Mutex Class Reference
OFX::MultiThread::Mutex Class Reference
#include <ofxsMultiThread.h>
Detailed Description
An OFX mutex.
Public Member Functions
Mutex (int lockCount=0)
ctor
virtual ~Mutex (void)
dtor
void lock ()
lock it, blocks until lock is gained
void unlock ()
unlock it
bool tryLock ()
attempt to lock, non-blocking
Protected Attributes
OfxMutexHandle _handle
The handle.
Constructor & Destructor Documentation
OFX::MultiThread::Mutex::Mutex (int lockCount = 0)
ctor
References _handle, OFX::Private::gThreadSuite, and OFX::throwSuiteStatusException().
OFX::MultiThread::Mutex::~Mutex (void) [virtual]
dtor
References _handle, and OFX::Private::gThreadSuite.
Member Function Documentation
void OFX::MultiThread::Mutex::lock (void)
lock it, blocks until lock is gained
References _handle, OFX::Private::gThreadSuite, and OFX::throwSuiteStatusException().
Referenced by OFX::MultiThread::AutoMutex::AutoMutex().
void OFX::MultiThread::Mutex::unlock (void)
unlock it
References _handle, OFX::Private::gThreadSuite, and OFX::throwSuiteStatusException().
Referenced by OFX::MultiThread::AutoMutex::~AutoMutex().
bool OFX::MultiThread::Mutex::tryLock ()
attempt to lock, non-blocking
returns
true if the lock was achieved
false if it could not
References _handle, and OFX::Private::gThreadSuite.
Member Data Documentation
OfxMutexHandle OFX::MultiThread::Mutex::_handle [protected]
The handle.
Referenced by lock(), Mutex(), tryLock(), unlock(), and ~Mutex().
The documentation for this class was generated from the following files:
ofxsMultiThread.h
ofxsMultiThread.cpp