OFX Support: OFX::IntParamDescriptor Class Reference
OFX::IntParamDescriptor Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up an integer param.
Public Member Functions
void setDefault (int v)
set the default value, default is 0
void setRange (int min, int max)
set the hard min/max range, default is INT_MIN, INT_MAX
void setDisplayRange (int min, int max)
set the display min and max, default is to be the same as the range param
Protected Member Functions
mDeclareProtectedAssignAndCC (IntParamDescriptor)
IntParamDescriptor (void)
IntParamDescriptor (const std::string &name, OfxPropertySetHandle props)
hidden constructor
Friends
class ParamSetDescriptor
Constructor & Destructor Documentation
OFX::IntParamDescriptor::IntParamDescriptor (void) [inline, protected]
OFX::IntParamDescriptor::IntParamDescriptor (const std::string & name, OfxPropertySetHandle props) [protected]
hidden constructor
ctor
Member Function Documentation
OFX::IntParamDescriptor::mDeclareProtectedAssignAndCC (IntParamDescriptor) [protected]
void OFX::IntParamDescriptor::setDefault (int v)
set the default value, default is 0
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::IntParamDescriptor::setRange (int min, int max)
set the hard min/max range, default is INT_MIN, INT_MAX
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
void OFX::IntParamDescriptor::setDisplayRange (int min, int max)
set the display min and max, default is to be the same as the range param
References OFX::ParamDescriptor::_paramProps, and OFX::PropertySet::propSetInt().
Friends And Related Function Documentation
friend class ParamSetDescriptor [friend]
Reimplemented from OFX::ValueParamDescriptor.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp