OFX Support: OFX::Interact Class Reference
OFX::Interact Class Reference
#include <ofxsInteract.h>
Detailed Description
Wraps up an OFX interact object for an Image Effect. It won't work for any other plug-in type at present (it would need to be broken into a hierarchy of classes).
Public Member Functions
Interact (OfxInteractHandle handle)
ctor
virtual ~Interact ()
virtual destructor
PropertySet & getProperties ()
int getBitDepth (void) const
The bitdepth of each component in the openGL frame buffer.
bool hasAlpha (void) const
Does the openGL frame buffer have an alpha.
OfxPointD getPixelScale (void) const
Returns the size of a real screen pixel under the interact's cannonical projection.
OfxRGBColourD getBackgroundColour (void) const
the background colour
void addParamToSlaveTo (Param *p)
Set a param that the interact should be redrawn on if its value changes.
void removeParamToSlaveTo (Param *p)
Remova a param that the interact should be redrawn on if its value changes.
void requestRedraw (void) const
Request a redraw.
void swapBuffers (void) const
Swap a buffer in the case of a double bufferred interact, this is possibly a silly one.
virtual bool draw (const DrawArgs &args)
the function called to draw in the interact
virtual bool penMotion (const PenArgs &args)
the function called to handle pen motion in the interact
virtual bool penDown (const PenArgs &args)
the function called to handle pen down events in the interact
virtual bool penUp (const PenArgs &args)
the function called to handle pen up events in the interact
virtual bool keyDown (const KeyArgs &args)
the function called to handle key down events in the interact
virtual bool keyUp (const KeyArgs &args)
the function called to handle key up events in the interact
virtual bool keyRepeat (const KeyArgs &args)
the function called to handle key down repeat events in the interact
virtual void gainFocus (const FocusArgs &args)
Called when the interact is given input focus.
virtual void loseFocus (const FocusArgs &args)
Called when the interact is loses input focus.
Protected Attributes
OfxInteractHandle _interactHandle
The handle for this interact.
PropertySet _interactProperties
The property set on this interact.
std::list< Param * > _slaveParams
List of params we are currently slaved to.
ImageEffect * _effect
The instance we are associated with.
Constructor & Destructor Documentation
OFX::Interact::Interact (OfxInteractHandle handle)
ctor
References _effect, _interactProperties, OFX::Private::gInteractSuite, OFX::PropertySet::propSetHandle(), OFX::PropertySet::propSetPointer(), OFX::retrieveEffectFromInteractHandle(), and OFX::throwSuiteStatusException().
OFX::Interact::~Interact () [virtual]
virtual destructor
ctor
Member Function Documentation
PropertySet& OFX::Interact::getProperties () [inline]
References _interactProperties.
int OFX::Interact::getBitDepth (void) const
The bitdepth of each component in the openGL frame buffer.
References _interactProperties, and OFX::PropertySet::propGetInt().
bool OFX::Interact::hasAlpha (void) const
Does the openGL frame buffer have an alpha.
References _interactProperties, and OFX::PropertySet::propGetInt().
OfxPointD OFX::Interact::getPixelScale (void) const
Returns the size of a real screen pixel under the interact's cannonical projection.
References _interactProperties, and OFX::PropertySet::propGetDouble().
OfxRGBColourD OFX::Interact::getBackgroundColour (void) const
the background colour
References _interactProperties, and OFX::getBackgroundColour().
void OFX::Interact::addParamToSlaveTo (Param * p)
Set a param that the interact should be redrawn on if its value changes.
References _interactProperties, _slaveParams, OFX::Param::getName(), OFX::PropertySet::propGetDimension(), and OFX::PropertySet::propSetString().
void OFX::Interact::removeParamToSlaveTo (Param * p)
Remova a param that the interact should be redrawn on if its value changes.
References _interactProperties, _slaveParams, OFX::PropertySet::propReset(), and OFX::PropertySet::propSetString().
void OFX::Interact::requestRedraw (void) const
Request a redraw.
References _interactHandle, OFX::Private::gInteractSuite, and OFX::throwSuiteStatusException().
void OFX::Interact::swapBuffers (void) const
Swap a buffer in the case of a double bufferred interact, this is possibly a silly one.
References _interactHandle, OFX::Private::gInteractSuite, and OFX::throwSuiteStatusException().
bool OFX::Interact::draw (const DrawArgs & args) [virtual]
the function called to draw in the interact
Referenced by OFX::Private::interactMainEntry().
bool OFX::Interact::penMotion (const PenArgs & args) [virtual]
the function called to handle pen motion in the interact
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
Referenced by OFX::Private::interactMainEntry().
bool OFX::Interact::penDown (const PenArgs & args) [virtual]
the function called to handle pen down events in the interact
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
Referenced by OFX::Private::interactMainEntry().
bool OFX::Interact::penUp (const PenArgs & args) [virtual]
the function called to handle pen up events in the interact
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
Referenced by OFX::Private::interactMainEntry().
bool OFX::Interact::keyDown (const KeyArgs & args) [virtual]
the function called to handle key down events in the interact
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
Referenced by OFX::Private::interactMainEntry().
bool OFX::Interact::keyUp (const KeyArgs & args) [virtual]
the function called to handle key up events in the interact
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
Referenced by OFX::Private::interactMainEntry().
bool OFX::Interact::keyRepeat (const KeyArgs & args) [virtual]
the function called to handle key down repeat events in the interact
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
returns true if the interact trapped the action in some sense. This will block the action being passed to any other interact that may share the viewer.
Referenced by OFX::Private::interactMainEntry().
void OFX::Interact::gainFocus (const FocusArgs & args) [virtual]
Called when the interact is given input focus.
Referenced by OFX::Private::interactMainEntry().
void OFX::Interact::loseFocus (const FocusArgs & args) [virtual]
Called when the interact is loses input focus.
Referenced by OFX::Private::interactMainEntry().
Member Data Documentation
OfxInteractHandle OFX::Interact::_interactHandle [protected]
The handle for this interact.
Referenced by requestRedraw(), and swapBuffers().
PropertySet OFX::Interact::_interactProperties [protected]
The property set on this interact.
Referenced by addParamToSlaveTo(), getBackgroundColour(), getBitDepth(), OFX::ParamInteract::getInteractSize(), getPixelScale(), getProperties(), hasAlpha(), Interact(), and removeParamToSlaveTo().
std::list<Param *> OFX::Interact::_slaveParams [protected]
List of params we are currently slaved to.
Referenced by addParamToSlaveTo(), and removeParamToSlaveTo().
ImageEffect* OFX::Interact::_effect [protected]
The instance we are associated with.
Reimplemented in OFX::ParamInteract.
Referenced by Interact(), OFX::OverlayInteract::OverlayInteract(), and OFX::OverlayInteract::~OverlayInteract().
The documentation for this class was generated from the following files:
ofxsInteract.h
ofxsInteract.cpp