OFX Support: OFX::StringParam Class Reference
OFX::StringParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a string param.
Public Member Functions
void setDefault (const std::string &v)
set the default value
void getDefault (std::string &v)
get the default value
void getValue (std::string &v)
get value
void getValueAtTime (double t, std::string &v)
get the value at a time
void setValue (const std::string &v)
set value
void setValueAtTime (double t, const std::string &v)
set the value at a time, implicitly adds a keyframe
Protected Member Functions
mDeclareProtectedAssignAndCC (StringParam)
StringParam (void)
StringParam (const ParamSet *paramSet, const std::string &name, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::StringParam::StringParam (void) [inline, protected]
OFX::StringParam::StringParam (const ParamSet * paramSet, const std::string & name, OfxParamHandle handle) [protected]
hidden constructor
Member Function Documentation
OFX::StringParam::mDeclareProtectedAssignAndCC (StringParam) [protected]
void OFX::StringParam::setDefault (const std::string & v)
set the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propSetString().
void OFX::StringParam::getDefault (std::string & v)
get the default value
het the default value
References OFX::Param::_paramProps, and OFX::PropertySet::propGetString().
void OFX::StringParam::getValue (std::string & v)
get value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::StringParam::getValueAtTime (double t, std::string & v)
get the value at a time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::StringParam::setValue (const std::string & v)
set value
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, and OFX::throwSuiteStatusException().
void OFX::StringParam::setValueAtTime (double t, const std::string & v)
set the value at a time, implicitly adds a keyframe
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::ValueParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp