OFX Support: OFX::ValueParam Class Reference
OFX::ValueParam Class Reference
#include <ofxsParam.h>
Detailed Description
Wraps up a value holding param.
Public Member Functions
~ValueParam ()
dtor
void setEvaluateOnChange (bool v)
Set's whether the value of the param is significant (ie: affects the rendered image).
bool getIsAnimating (void) const
is the param animating
bool getIsAutoKeying (void) const
is the param animating
bool getIsPersistant (void) const
is the param animating
bool getEvaluateOnChange (void) const
Get's whether the value of the param is significant (ie: affects the rendered image).
CacheInvalidationEnum getCacheInvalidation (void) const
Get's whether the value of the param is significant (ie: affects the rendered image).
unsigned int getNumKeys (void)
if the param is animating, the number of keys in it, otherwise 0
double getKeyTime (int nthKey) throw (OFX::Exception::Suite, std::out_of_range)
get the time of the nth key, nth must be between 0 and getNumKeys-1
int getKeyIndex (double time, KeySearchEnum searchDir)
find the index of a key by a time
void deleteKeyAtTime (double time)
deletes a key at the given time
void deleteAllKeys (void)
delete all the keys
Protected Member Functions
mDeclareProtectedAssignAndCC (ValueParam)
ValueParam (void)
ValueParam (const ParamSet *paramSet, const std::string &name, ParamTypeEnum type, OfxParamHandle handle)
hidden constructor
Friends
class ParamSet
Constructor & Destructor Documentation
OFX::ValueParam::ValueParam (void) [inline, protected]
OFX::ValueParam::ValueParam (const ParamSet * paramSet, const std::string & name, ParamTypeEnum type, OfxParamHandle handle) [protected]
hidden constructor
Wraps up a value holding param.
hidden constructor
OFX::ValueParam::~ValueParam ()
dtor
Member Function Documentation
OFX::ValueParam::mDeclareProtectedAssignAndCC (ValueParam) [protected]
void OFX::ValueParam::setEvaluateOnChange (bool v)
Set's whether the value of the param is significant (ie: affects the rendered image).
References OFX::Param::_paramProps, and OFX::PropertySet::propSetInt().
bool OFX::ValueParam::getIsAnimating (void) const
is the param animating
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
bool OFX::ValueParam::getIsAutoKeying (void) const
is the param animating
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
bool OFX::ValueParam::getIsPersistant (void) const
is the param animating
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
bool OFX::ValueParam::getEvaluateOnChange (void) const
Get's whether the value of the param is significant (ie: affects the rendered image).
References OFX::Param::_paramProps, and OFX::PropertySet::propGetInt().
CacheInvalidationEnum OFX::ValueParam::getCacheInvalidation (void) const
Get's whether the value of the param is significant (ie: affects the rendered image).
References OFX::Param::_paramProps, OFX::eCacheInvalidateValueAll, OFX::eCacheInvalidateValueChange, OFX::eCacheInvalidateValueChangeToEnd, and OFX::PropertySet::propGetString().
unsigned int OFX::ValueParam::getNumKeys (void)
if the param is animating, the number of keys in it, otherwise 0
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
double OFX::ValueParam::getKeyTime (int nthKey) throw (OFX::Exception::Suite, std::out_of_range)
get the time of the nth key, nth must be between 0 and getNumKeys-1
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
int OFX::ValueParam::getKeyIndex (double time, KeySearchEnum searchDir)
find the index of a key by a time
References OFX::Param::_paramHandle, OFX::eKeySearchBackwards, OFX::eKeySearchNear, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
void OFX::ValueParam::deleteKeyAtTime (double time)
deletes a key at the given time
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
void OFX::ValueParam::deleteAllKeys (void)
delete all the keys
References OFX::Param::_paramHandle, OFX::Private::gParamSuite, OFX::throwHostMissingSuiteException(), and OFX::throwSuiteStatusException().
Friends And Related Function Documentation
friend class ParamSet [friend]
Reimplemented from OFX::Param.
Reimplemented in OFX::IntParam, OFX::Int2DParam, OFX::Int3DParam, OFX::BaseDoubleParam, OFX::DoubleParam, OFX::Double2DParam, OFX::Double3DParam, OFX::RGBParam, OFX::RGBAParam, OFX::StringParam, OFX::ChoiceParam, OFX::BooleanParam, and OFX::CustomParam.
The documentation for this class was generated from the following files:
ofxsParam.h
ofxsParams.cpp