OFX Support: OFX::PluginFactory Class Reference
OFX::PluginFactory Class Reference
#include <ofxsImageEffect.h>
Public Member Functions
virtual void load ()
virtual void unload ()
virtual void describe (OFX::ImageEffectDescriptor &desc)=0
virtual void describeInContext (OFX::ImageEffectDescriptor &desc, ContextEnum context)=0
virtual ImageEffect * createInstance (OfxImageEffectHandle handle, ContextEnum context)=0
virtual const std::string & getID () const =0
virtual const std::string & getUID () const =0
virtual unsigned int getMajorVersion () const =0
virtual unsigned int getMinorVersion () const =0
virtual OfxPluginEntryPoint * getMainEntry ()=0
Member Function Documentation
virtual void OFX::PluginFactory::load () [inline, virtual]
Referenced by OFX::Private::mainEntryStr().
virtual void OFX::PluginFactory::unload () [inline, virtual]
Referenced by OFX::Private::mainEntryStr().
virtual void OFX::PluginFactory::describe (OFX::ImageEffectDescriptor & desc) [pure virtual]
Referenced by OFX::Private::mainEntryStr().
virtual void OFX::PluginFactory::describeInContext (OFX::ImageEffectDescriptor & desc, ContextEnum context) [pure virtual]
Referenced by OFX::Private::mainEntryStr().
virtual ImageEffect* OFX::PluginFactory::createInstance (OfxImageEffectHandle handle, ContextEnum context) [pure virtual]
Referenced by OFX::Private::mainEntryStr().
virtual const std::string& OFX::PluginFactory::getID () const [pure virtual]
Implemented in OFX::PluginFactoryHelper< FACTORY >.
Referenced by generatePlugInfo().
virtual const std::string& OFX::PluginFactory::getUID () const [pure virtual]
Implemented in OFX::PluginFactoryHelper< FACTORY >.
Referenced by generatePlugInfo().
virtual unsigned int OFX::PluginFactory::getMajorVersion () const [pure virtual]
Implemented in OFX::PluginFactoryHelper< FACTORY >.
Referenced by generatePlugInfo().
virtual unsigned int OFX::PluginFactory::getMinorVersion () const [pure virtual]
Implemented in OFX::PluginFactoryHelper< FACTORY >.
Referenced by generatePlugInfo().
virtual OfxPluginEntryPoint* OFX::PluginFactory::getMainEntry () [pure virtual]
Implemented in OFX::PluginFactoryHelper< FACTORY >.
Referenced by generatePlugInfo().
The documentation for this class was generated from the following file:
ofxsImageEffect.h