OFX Support: OFX::Validation Namespace Reference
OFX::Validation Namespace Reference
Detailed Description
The validation code has its own namespace.
Classes
struct ValueHolder
This is uses to hold a property value, used by the property checking classes.
class PropertyDescription
class to describe properties, check their default and set their values
class PropertySetDescription
Describes a set of properties.
Enumerations
enum DescriptionTag { eDescDefault, eDescFinished }
Enum used in the varargs list of the PropertyDescription constructor.
Functions
void validateHostProperties (OfxHost *host)
Validates the host structure and property handle.
void validatePluginDescriptorProperties (PropertySet props)
Validates the effect descriptor properties.
void validatePluginInstanceProperties (PropertySet props)
Validates the effect instance properties.
void validateClipDescriptorProperties (PropertySet props)
validates a clip descriptor
void validateClipInstanceProperties (PropertySet props)
validates a clip instance
void validateImageProperties (PropertySet props)
validates a clip descriptor
void validateActionArgumentsProperties (const std::string &action, PropertySet inArgs, PropertySet outArgs)
Validates action in/out arguments.
void validateParameterProperties (ParamTypeEnum paramType, OFX::PropertySet paramProps, bool checkDefaults)
Validates parameter properties.
void initialise (void)
Initialises validation stuff that needs to be done once we know how the host behaves, called during the onload action.
Enumeration Type Documentation
enum OFX::Validation::DescriptionTag
Enum used in the varargs list of the PropertyDescription constructor.
Enumerator:
eDescDefault
eDescFinished following values are the default to check against
we have finished the description
Function Documentation
void OFX::Validation::initialise (void)
Initialises validation stuff that needs to be done once we know how the host behaves, called during the onload action.
initialises the validation code, call this in on load
References OFX::Validation::PropertySetDescription::addProperty(), eDescDefault, eDescFinished, OFX::eInt, and OFX::getImageEffectHostDescription().
Referenced by OFX::Private::loadAction().
void OFX::Validation::validateActionArgumentsProperties (const std::string & action, PropertySet inArgs, PropertySet outArgs)
Validates action in/out arguments.
References OFX::Validation::PropertySetDescription::validate().
Referenced by OFX::Private::checkMainHandles().
void OFX::Validation::validateClipDescriptorProperties (PropertySet props)
validates a clip descriptor
References OFX::Validation::PropertySetDescription::validate().
Referenced by OFX::ClipDescriptor::ClipDescriptor().
void OFX::Validation::validateClipInstanceProperties (PropertySet props)
validates a clip instance
References OFX::Validation::PropertySetDescription::validate().
Referenced by OFX::Clip::Clip().
void OFX::Validation::validateHostProperties (OfxHost * host)
Validates the host structure and property handle.
References OFX::Validation::PropertySetDescription::validate().
Referenced by OFX::Private::loadAction().
void OFX::Validation::validateImageProperties (PropertySet props)
validates a clip descriptor
References OFX::Validation::PropertySetDescription::validate().
Referenced by OFX::Image::Image().
void OFX::Validation::validateParameterProperties (ParamTypeEnum paramType, OFX::PropertySet paramProps, bool checkDefaults)
Validates parameter properties.
References OFX::eBooleanParam, OFX::eChoiceParam, OFX::eCustomParam, OFX::eDouble2DParam, OFX::eDouble3DParam, OFX::eDoubleParam, OFX::eGroupParam, OFX::eInt2DParam, OFX::eInt3DParam, OFX::eIntParam, OFX::ePageParam, OFX::ePushButtonParam, OFX::eRGBAParam, OFX::eRGBParam, OFX::eStringParam, and OFX::Validation::PropertySetDescription::validate().
Referenced by OFX::Param::Param(), and OFX::ParamDescriptor::ParamDescriptor().
void OFX::Validation::validatePluginDescriptorProperties (PropertySet props)
Validates the effect descriptor properties.
References OFX::Validation::PropertySetDescription::validate().
Referenced by OFX::ImageEffectDescriptor::ImageEffectDescriptor(), and OFX::Private::mainEntryStr().
void OFX::Validation::validatePluginInstanceProperties (PropertySet props)
Validates the effect instance properties.
References OFX::Validation::PropertySetDescription::validate().
Referenced by OFX::ImageEffect::ImageEffect(), and OFX::Private::mainEntryStr().