OFX Support: OFX::Private Namespace Reference
OFX::Private Namespace Reference
Detailed Description
OFX::Private namespace, for things private to the support library code here generally calls image effect class members.
Typedefs
typedef std::map< ContextEnum,
ImageEffectDescriptor * > EffectContextMap
the set of descriptors, one per context used by kOfxActionDescribeInContext, 'eContextNone' is the one used by the kOfxActionDescribe
typedef std::map< std::string,
EffectContextMap > EffectDescriptorMap
Functions
OfxStatus mainEntryStr (const char *actionRaw, const void *handleRaw, OfxPropertySetHandle inArgsRaw, OfxPropertySetHandle outArgsRaw, const char *plugname)
The main entry point for the plugin.
OfxStatus interactMainEntry (const char *actionRaw, const void *handleRaw, OfxPropertySetHandle inArgsRaw, OfxPropertySetHandle outArgsRaw, InteractDescriptor &desc)
The main entry for image effect overlays.
void fetchHostDescription (OfxHost *host)
Creates the global host description and sets its properties.
OFX::PropertySet fetchEffectProps (OfxImageEffectHandle handle)
fetch the effect property set from the ImageEffectHandle
void loadAction (void)
Library side load action, this fetches all the suite pointers.
void unloadAction (const char *id)
Library side unload action, this fetches all the suite pointers.
ImageEffect * retrieveImageEffectPointer (OfxImageEffectHandle handle)
fetches our pointer out of the props on the handle
void checkMainHandles (const std::string &action, const void *handle, OfxPropertySetHandle inArgsHandle, OfxPropertySetHandle outArgsHandle, bool handleCanBeNull, bool inArgsCanBeNull, bool outArgsCanBeNull)
Checks the handles passed into the plugin's main entry point.
static void getRenderActionArguments (RenderArguments &args, OFX::PropertySet inArgs)
Fetches the arguments used in a render action 'inargs' property set into a POD struct.
void renderAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side render action, fetches relevant properties and calls the client code.
void beginSequenceRenderAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side render begin sequence render action, fetches relevant properties and calls the client code.
void endSequenceRenderAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side render begin sequence render action, fetches relevant properties and calls the client code.
bool isIdentityAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet &outArgs)
Library side render begin sequence render action, fetches relevant properties and calls the client code.
bool regionOfDefinitionAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet &outArgs)
Library side get region of definition function.
bool regionsOfInterestAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet &outArgs, const char *plugname)
Library side get regions of interest function.
bool framesNeededAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet &outArgs, const char *plugname)
Library side frames needed action.
bool getTimeDomainAction (OfxImageEffectHandle handle, OFX::PropertySet &outArgs)
Library side get regions of interest function.
bool clipPreferencesAction (OfxImageEffectHandle handle, OFX::PropertySet &outArgs, const char *plugname)
Library side get regions of interest function.
void beginInstanceChangedAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side begin instance changed action.
void instanceChangedAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side instance changed action.
void endInstanceChangedAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side end instance changed action.
void setHost (OfxHost *host)
The plugin function that gets passed the host structure.
Interact * retrieveInteractPointer (OfxInteractHandle handle)
fetches our pointer out of the props on the handle
OfxStatus interactMainEntry (const std::string &action, OfxInteractHandle handle, PropertySet inArgs, PropertySet outArgs)
The common entry point used by all interacts.
void unloadAction (void)
Support lib function called on an ofx unload action.
Variables
OfxHost * gHost = 0
Pointer to the host.
OfxImageEffectSuiteV1 * gEffectSuite = 0
Pointer to the effect suite.
OfxPropertySuiteV1 * gPropSuite = 0
Pointer to the property suite.
OfxInteractSuiteV1 * gInteractSuite = 0
Pointer to the interact suite.
OfxParameterSuiteV1 * gParamSuite = 0
Pointer to the parameter suite.
OfxMemorySuiteV1 * gMemorySuite = 0
Pointer to the general memory suite.
OfxMultiThreadSuiteV1 * gThreadSuite = 0
Pointer to the threading suite.
OfxMessageSuiteV1 * gMessageSuite = 0
Pointer to the message suite.
OfxProgressSuiteV1 * gProgressSuite = 0
Pointer to the optional progress suite.
OfxTimeLineSuiteV1 * gTimeLineSuite = 0
Pointer to the optional progress suite.
EffectDescriptorMap gEffectDescriptors
int gLoadCount = 0
Keeps count of how many times load/unload have been called.
Typedef Documentation
typedef std::map<ContextEnum, ImageEffectDescriptor*> OFX::Private::EffectContextMap
the set of descriptors, one per context used by kOfxActionDescribeInContext, 'eContextNone' is the one used by the kOfxActionDescribe
typedef std::map<std::string, EffectContextMap> OFX::Private::EffectDescriptorMap
Function Documentation
void OFX::Private::beginInstanceChangedAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side begin instance changed action.
References OFX::ImageEffect::beginChanged(), OFX::mapToInstanceChangedReason(), OFX::PropertySet::propGetString(), and retrieveImageEffectPointer().
Referenced by mainEntryStr().
void OFX::Private::beginSequenceRenderAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side render begin sequence render action, fetches relevant properties and calls the client code.
References OFX::ImageEffect::beginSequenceRender(), OFX::BeginSequenceRenderArguments::frameRange, OFX::BeginSequenceRenderArguments::frameStep, OFX::BeginSequenceRenderArguments::isInteractive, OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetInt(), OFX::BeginSequenceRenderArguments::renderScale, and retrieveImageEffectPointer().
Referenced by mainEntryStr().
void OFX::Private::checkMainHandles (const std::string & action, const void * handle, OfxPropertySetHandle inArgsHandle, OfxPropertySetHandle outArgsHandle, bool handleCanBeNull, bool inArgsCanBeNull, bool outArgsCanBeNull)
Checks the handles passed into the plugin's main entry point.
References OFX::Log::error(), OFX::throwSuiteStatusException(), OFX::Validation::validateActionArgumentsProperties(), and OFX::Log::warning().
Referenced by mainEntryStr().
bool OFX::Private::clipPreferencesAction (OfxImageEffectHandle handle, OFX::PropertySet & outArgs, const char * plugname)
Library side get regions of interest function.
References gEffectDescriptors, OFX::ImageEffectDescriptor::getClipComponentPropNames(), OFX::ImageEffectDescriptor::getClipDepthPropNames(), OFX::ImageEffectDescriptor::getClipPARPropNames(), OFX::ImageEffect::getClipPreferences(), OFX::ImageEffect::getContext(), and retrieveImageEffectPointer().
Referenced by mainEntryStr().
void OFX::Private::endInstanceChangedAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side end instance changed action.
References OFX::ImageEffect::endChanged(), OFX::mapToInstanceChangedReason(), OFX::PropertySet::propGetString(), and retrieveImageEffectPointer().
Referenced by mainEntryStr().
void OFX::Private::endSequenceRenderAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side render begin sequence render action, fetches relevant properties and calls the client code.
References OFX::ImageEffect::endSequenceRender(), OFX::EndSequenceRenderArguments::isInteractive, OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetInt(), OFX::EndSequenceRenderArguments::renderScale, and retrieveImageEffectPointer().
Referenced by mainEntryStr().
OFX::PropertySet OFX::Private::fetchEffectProps (OfxImageEffectHandle handle)
fetch the effect property set from the ImageEffectHandle
fetch the prop set from the effect handle
References gEffectSuite, and OFX::throwSuiteStatusException().
Referenced by OFX::ImageEffect::ImageEffect(), and mainEntryStr().
void OFX::Private::fetchHostDescription (OfxHost * host)
Creates the global host description and sets its properties.
References OFX::ImageEffectHostDescription::_supportedComponents, OFX::ImageEffectHostDescription::_supportedContexts, OFX::ImageEffectHostDescription::_supportedPixelDepths, OFX::Log::error(), OFX::gHostDescription, OFX::gHostDescriptionHasInit, OFX::ImageEffectHostDescription::hostIsBackground, OFX::ImageEffectHostDescription::hostName, OFX::mapStrToBitDepthEnum(), OFX::mapStrToPixelComponentEnum(), OFX::mapToContextEnum(), OFX::ImageEffectHostDescription::maxPages, OFX::ImageEffectHostDescription::maxParameters, OFX::ImageEffectHostDescription::pageColumnCount, OFX::ImageEffectHostDescription::pageRowCount, OFX::PropertySet::propGetDimension(), OFX::PropertySet::propGetInt(), OFX::PropertySet::propGetString(), OFX::ImageEffectHostDescription::supportsBooleanAnimation, OFX::ImageEffectHostDescription::supportsChoiceAnimation, OFX::ImageEffectHostDescription::supportsCustomAnimation, OFX::ImageEffectHostDescription::supportsCustomInteract, OFX::ImageEffectHostDescription::supportsMultipleClipDepths, OFX::ImageEffectHostDescription::supportsMultipleClipPARs, OFX::ImageEffectHostDescription::supportsMultiResolution, OFX::ImageEffectHostDescription::supportsOverlays, OFX::ImageEffectHostDescription::supportsSetableFielding, OFX::ImageEffectHostDescription::supportsSetableFrameRate, OFX::ImageEffectHostDescription::supportsStringAnimation, OFX::ImageEffectHostDescription::supportsTiles, and OFX::ImageEffectHostDescription::temporalClipAccess.
Referenced by loadAction().
bool OFX::Private::framesNeededAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet & outArgs, const char * plugname)
Library side frames needed action.
References gEffectDescriptors, OFX::ImageEffect::getContext(), OFX::ImageEffect::getFramesNeeded(), OFX::Clip::name(), OFX::PropertySet::propGetDouble(), retrieveImageEffectPointer(), and OFX::FramesNeededArguments::time.
Referenced by mainEntryStr().
static void OFX::Private::getRenderActionArguments (RenderArguments & args, OFX::PropertySet inArgs) [static]
Fetches the arguments used in a render action 'inargs' property set into a POD struct.
References OFX::Log::error(), OFX::RenderArguments::fieldToRender, OFX::mapStrToFieldEnum(), OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetInt(), OFX::PropertySet::propGetString(), OFX::RenderArguments::renderScale, OFX::RenderArguments::renderWindow, and OFX::RenderArguments::time.
Referenced by isIdentityAction(), and renderAction().
bool OFX::Private::getTimeDomainAction (OfxImageEffectHandle handle, OFX::PropertySet & outArgs)
Library side get regions of interest function.
References OFX::eContextGeneral, OFX::Log::error(), OFX::ImageEffect::getContext(), OFX::ImageEffect::getTimeDomain(), OFX::PropertySet::propSetDouble(), and retrieveImageEffectPointer().
Referenced by mainEntryStr().
void OFX::Private::instanceChangedAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side instance changed action.
References OFX::ImageEffect::changedClip(), OFX::ImageEffect::changedParam(), OFX::Log::error(), OFX::mapToInstanceChangedReason(), OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetString(), OFX::InstanceChangedArgs::reason, OFX::InstanceChangedArgs::renderScale, retrieveImageEffectPointer(), and OFX::InstanceChangedArgs::time.
Referenced by mainEntryStr().
OfxStatus OFX::Private::interactMainEntry (const std::string & action, OfxInteractHandle handle, PropertySet inArgs, PropertySet outArgs)
The common entry point used by all interacts.
References OFX::Interact::draw(), OFX::Interact::gainFocus(), OFX::Interact::keyDown(), OFX::Interact::keyRepeat(), OFX::Interact::keyUp(), OFX::Interact::loseFocus(), OFX::Interact::penDown(), OFX::Interact::penMotion(), OFX::Interact::penUp(), and retrieveInteractPointer().
Referenced by interactMainEntry().
OfxStatus OFX::Private::interactMainEntry (const char * actionRaw, const void * handleRaw, OfxPropertySetHandle inArgsRaw, OfxPropertySetHandle outArgsRaw, InteractDescriptor & desc)
The main entry for image effect overlays.
References OFX::InteractDescriptor::createInstance(), OFX::InteractDescriptor::describe(), gInteractSuite, OFX::Log::indent(), interactMainEntry(), OFX::Log::outdent(), OFX::Log::print(), OFX::retrieveEffectFromInteractHandle(), OFX::InteractDescriptor::setPropertySet(), and OFX::throwSuiteStatusException().
Referenced by OFX::InteractMainEntry< DESC >::overlayInteractMainEntry().
bool OFX::Private::isIdentityAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet & outArgs)
Library side render begin sequence render action, fetches relevant properties and calls the client code.
References getRenderActionArguments(), OFX::ImageEffect::isIdentity(), OFX::Clip::name(), OFX::PropertySet::propSetDouble(), OFX::PropertySet::propSetString(), retrieveImageEffectPointer(), and OFX::RenderArguments::time.
Referenced by mainEntryStr().
void OFX::Private::loadAction (void)
Library side load action, this fetches all the suite pointers.
Support lib function called on an ofx load action.
References OFX::Log::error(), fetchHostDescription(), OFX::fetchSuite(), gEffectSuite, gHost, OFX::gHostDescription, gInteractSuite, gLoadCount, gMemorySuite, gMessageSuite, gParamSuite, gProgressSuite, gPropSuite, gThreadSuite, gTimeLineSuite, OFX::Validation::initialise(), OFX::ImageEffectHostDescription::supportsProgressSuite, OFX::ImageEffectHostDescription::supportsTimeLineSuite, and OFX::Validation::validateHostProperties().
Referenced by mainEntryStr().
OfxStatus OFX::Private::mainEntryStr (const char * actionRaw, const void * handleRaw, OfxPropertySetHandle inArgsRaw, OfxPropertySetHandle outArgsRaw, const char * plugname)
The main entry point for the plugin.
References OFX::ImageEffect::beginEdit(), beginInstanceChangedAction(), beginSequenceRenderAction(), checkMainHandles(), clipPreferencesAction(), OFX::PluginFactory::createInstance(), OFX::PluginFactory::describe(), OFX::PluginFactory::describeInContext(), OFX::eContextNone, OFX::ImageEffect::endEdit(), endInstanceChangedAction(), endSequenceRenderAction(), OFX::Log::error(), fetchEffectProps(), framesNeededAction(), gEffectDescriptors, getTimeDomainAction(), OFX::Log::indent(), instanceChangedAction(), isIdentityAction(), OFX::PluginFactory::load(), loadAction(), OFX::mapToContextEnum(), OFX::Log::outdent(), OFX::plugInfoMap, OFX::Log::print(), OFX::PropertySet::propGetString(), OFX::ImageEffect::purgeCaches(), regionOfDefinitionAction(), regionsOfInterestAction(), renderAction(), retrieveImageEffectPointer(), OFX::Exception::Suite::status(), OFX::ImageEffect::syncPrivateData(), OFX::PluginFactory::unload(), unloadAction(), OFX::Validation::validatePluginDescriptorProperties(), and OFX::Validation::validatePluginInstanceProperties().
Referenced by OFX::FactoryMainEntryHelper< FACTORY >::mainEntry().
bool OFX::Private::regionOfDefinitionAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet & outArgs)
Library side get region of definition function.
References OFX::ImageEffect::getRegionOfDefinition(), OFX::PropertySet::propGetDouble(), OFX::PropertySet::propSetDouble(), OFX::RegionOfDefinitionArguments::renderScale, retrieveImageEffectPointer(), and OFX::RegionOfDefinitionArguments::time.
Referenced by mainEntryStr().
bool OFX::Private::regionsOfInterestAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet & outArgs, const char * plugname)
Library side get regions of interest function.
References gEffectDescriptors, OFX::ImageEffect::getContext(), OFX::ImageEffect::getRegionsOfInterest(), OFX::Clip::name(), OFX::PropertySet::propGetDouble(), OFX::RegionsOfInterestArguments::regionOfInterest, OFX::RegionsOfInterestArguments::renderScale, retrieveImageEffectPointer(), and OFX::RegionsOfInterestArguments::time.
Referenced by mainEntryStr().
void OFX::Private::renderAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side render action, fetches relevant properties and calls the client code.
References getRenderActionArguments(), OFX::ImageEffect::render(), and retrieveImageEffectPointer().
Referenced by mainEntryStr().
ImageEffect * OFX::Private::retrieveImageEffectPointer (OfxImageEffectHandle handle)
fetches our pointer out of the props on the handle
References OFX::Log::error(), gEffectSuite, OFX::PropertySet::propGetPointer(), and OFX::throwSuiteStatusException().
Referenced by beginInstanceChangedAction(), beginSequenceRenderAction(), clipPreferencesAction(), endInstanceChangedAction(), endSequenceRenderAction(), framesNeededAction(), getTimeDomainAction(), instanceChangedAction(), isIdentityAction(), mainEntryStr(), regionOfDefinitionAction(), regionsOfInterestAction(), renderAction(), and OFX::retrieveEffectFromInteractHandle().
Interact* OFX::Private::retrieveInteractPointer (OfxInteractHandle handle)
fetches our pointer out of the props on the handle
References OFX::Log::error(), gInteractSuite, OFX::PropertySet::propGetPointer(), and OFX::throwSuiteStatusException().
Referenced by interactMainEntry().
void OFX::Private::setHost (OfxHost * host)
The plugin function that gets passed the host structure.
References gHost.
Referenced by generatePlugInfo().
void OFX::Private::unloadAction (void)
Support lib function called on an ofx unload action.
void OFX::Private::unloadAction (const char * id)
Library side unload action, this fetches all the suite pointers.
References gEffectDescriptors, gEffectSuite, gInteractSuite, gLoadCount, gMemorySuite, gMessageSuite, gParamSuite, gPropSuite, gThreadSuite, OFX::ofxPlugs, and OFX::plugInfoMap.
Referenced by mainEntryStr().
Variable Documentation
EffectDescriptorMap OFX::Private::gEffectDescriptors
Referenced by clipPreferencesAction(), framesNeededAction(), mainEntryStr(), regionsOfInterestAction(), and unloadAction().
OfxImageEffectSuiteV1 * OFX::Private::gEffectSuite = 0
Pointer to the effect suite.
Referenced by OFX::ImageEffect::abort(), OFX::ImageEffectDescriptor::defineClip(), OFX::ImageEffect::fetchClip(), fetchEffectProps(), OFX::Clip::fetchImage(), OFX::Clip::getRegionOfDefinition(), OFX::ImageEffect::ImageEffect(), OFX::ImageEffectDescriptor::ImageEffectDescriptor(), OFX::ImageMemory::ImageMemory(), loadAction(), OFX::ImageMemory::lock(), retrieveImageEffectPointer(), unloadAction(), OFX::ImageMemory::unlock(), OFX::Image::~Image(), and OFX::ImageMemory::~ImageMemory().
OfxHost * OFX::Private::gHost = 0
Pointer to the host.
Referenced by OFX::fetchSuite(), loadAction(), and setHost().
OfxInteractSuiteV1 * OFX::Private::gInteractSuite = 0
Pointer to the interact suite.
Referenced by OFX::Interact::Interact(), interactMainEntry(), loadAction(), OFX::Interact::requestRedraw(), OFX::retrieveEffectFromInteractHandle(), retrieveInteractPointer(), OFX::Interact::swapBuffers(), and unloadAction().
int OFX::Private::gLoadCount = 0
Keeps count of how many times load/unload have been called.
Referenced by loadAction(), and unloadAction().
OfxMemorySuiteV1 * OFX::Private::gMemorySuite = 0
Pointer to the general memory suite.
Referenced by OFX::Memory::allocate(), OFX::Memory::free(), loadAction(), and unloadAction().
OfxMessageSuiteV1 * OFX::Private::gMessageSuite = 0
Pointer to the message suite.
Referenced by loadAction(), OFX::ImageEffect::sendMessage(), and unloadAction().
OfxParameterSuiteV1 * OFX::Private::gParamSuite = 0
Pointer to the parameter suite.
Referenced by OFX::ParamSet::beginEditBlock(), OFX::ParamSetDescriptor::defineRawParam(), OFX::ValueParam::deleteAllKeys(), OFX::ValueParam::deleteKeyAtTime(), OFX::Double3DParam::differentiate(), OFX::Double2DParam::differentiate(), OFX::DoubleParam::differentiate(), OFX::ParamSet::endEditBlock(), OFX::ValueParam::getKeyIndex(), OFX::ValueParam::getKeyTime(), OFX::ValueParam::getNumKeys(), OFX::ParamSet::getParam(), OFX::ParamSet::getParamType(), OFX::CustomParam::getValue(), OFX::ChoiceParam::getValue(), OFX::BooleanParam::getValue(), OFX::StringParam::getValue(), OFX::RGBAParam::getValue(), OFX::RGBParam::getValue(), OFX::Double3DParam::getValue(), OFX::Double2DParam::getValue(), OFX::DoubleParam::getValue(), OFX::Int3DParam::getValue(), OFX::Int2DParam::getValue(), OFX::IntParam::getValue(), OFX::CustomParam::getValueAtTime(), OFX::ChoiceParam::getValueAtTime(), OFX::BooleanParam::getValueAtTime(), OFX::StringParam::getValueAtTime(), OFX::RGBAParam::getValueAtTime(), OFX::RGBParam::getValueAtTime(), OFX::Double3DParam::getValueAtTime(), OFX::Double2DParam::getValueAtTime(), OFX::DoubleParam::getValueAtTime(), OFX::Int3DParam::getValueAtTime(), OFX::Int2DParam::getValueAtTime(), OFX::IntParam::getValueAtTime(), OFX::Double3DParam::integrate(), OFX::Double2DParam::integrate(), OFX::DoubleParam::integrate(), loadAction(), OFX::Param::Param(), OFX::ParamSet::paramExists(), OFX::ParamSet::setParamSetHandle(), OFX::ParamSetDescriptor::setParamSetHandle(), OFX::CustomParam::setValue(), OFX::ChoiceParam::setValue(), OFX::BooleanParam::setValue(), OFX::StringParam::setValue(), OFX::RGBAParam::setValue(), OFX::RGBParam::setValue(), OFX::Double3DParam::setValue(), OFX::Double2DParam::setValue(), OFX::DoubleParam::setValue(), OFX::Int3DParam::setValue(), OFX::Int2DParam::setValue(), OFX::IntParam::setValue(), OFX::CustomParam::setValueAtTime(), OFX::ChoiceParam::setValueAtTime(), OFX::BooleanParam::setValueAtTime(), OFX::StringParam::setValueAtTime(), OFX::RGBAParam::setValueAtTime(), OFX::RGBParam::setValueAtTime(), OFX::Double3DParam::setValueAtTime(), OFX::Double2DParam::setValueAtTime(), OFX::DoubleParam::setValueAtTime(), OFX::Int3DParam::setValueAtTime(), OFX::Int2DParam::setValueAtTime(), OFX::IntParam::setValueAtTime(), and unloadAction().
OfxProgressSuiteV1 * OFX::Private::gProgressSuite = 0
Pointer to the optional progress suite.
Referenced by loadAction(), OFX::ImageEffect::progressEnd(), OFX::ImageEffect::progressStart(), and OFX::ImageEffect::progressUpdate().
OfxPropertySuiteV1 * OFX::Private::gPropSuite = 0
Pointer to the property suite.
Referenced by loadAction(), OFX::PropertySet::propGetDimension(), OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetInt(), OFX::PropertySet::propGetPointer(), OFX::PropertySet::propGetString(), OFX::PropertySet::propReset(), OFX::PropertySet::propSetDouble(), OFX::PropertySet::propSetInt(), OFX::PropertySet::propSetPointer(), OFX::PropertySet::propSetString(), and unloadAction().
OfxMultiThreadSuiteV1 * OFX::Private::gThreadSuite = 0
Pointer to the threading suite.
Referenced by OFX::MultiThread::getNumCPUs(), OFX::MultiThread::getThreadIndex(), OFX::MultiThread::isSpawnedThread(), loadAction(), OFX::MultiThread::Mutex::lock(), OFX::MultiThread::Processor::multiThread(), OFX::MultiThread::Mutex::Mutex(), OFX::MultiThread::Mutex::tryLock(), unloadAction(), OFX::MultiThread::Mutex::unlock(), and OFX::MultiThread::Mutex::~Mutex().
OfxTimeLineSuiteV1 * OFX::Private::gTimeLineSuite = 0
Pointer to the optional progress suite.
Referenced by loadAction(), OFX::ImageEffect::timeLineGetBounds(), OFX::ImageEffect::timeLineGetTime(), and OFX::ImageEffect::timeLineGotoTime().