OFX Support: OFX::Log Namespace Reference
OFX::Log Namespace Reference
Detailed Description
this namespace wraps up logging functionality
Functions
void indent (void)
Indent it, not MP sane at the moment.
void outdent (void)
Outdent it, not MP sane at the moment.
void setFileName (const std::string &value)
Sets the name of the log file.
bool open (void)
Opens the log file, returns whether this was sucessful or not.
void close (void)
Closes the log file.
void print (const char *format,...)
Prints to the log file.
void warning (bool condition, const char *format,...)
Prints to the log file only if the condition is true and prepends a warning notice.
void error (bool condition, const char *format,...)
Prints to the log file only if the condition is true and prepends an error notice.
static std::string gLogFileName (getenv(kLogFileEnvVar)?getenv(kLogFileEnvVar):"ofxTestLog.txt")
the global logfile name
static void doIndent (void)
do the indenting
Variables
static FILE * gLogFP = 0
log file
static int gIndent = 0
global indent level, not MP sane
Function Documentation
void OFX::Log::close (void)
Closes the log file.
References gLogFP.
static void OFX::Log::doIndent (void) [static]
do the indenting
References gIndent, gLogFP, and open().
Referenced by error(), print(), and warning().
void OFX::Log::error (bool condition, const char * format, ...)
Prints to the log file only if the condition is true and prepends an error notice.
References doIndent(), gLogFP, and open().
Referenced by OFX::Private::checkMainHandles(), OFX::Private::fetchHostDescription(), OFX::fetchSuite(), OFX::Clip::getFieldOrder(), OFX::Clip::getPixelComponents(), OFX::Clip::getPixelDepth(), OFX::Clip::getPreMultiplication(), OFX::Private::getRenderActionArguments(), OFX::Private::getTimeDomainAction(), OFX::Clip::getUnmappedPixelComponents(), OFX::Clip::getUnmappedPixelDepth(), OFX::Image::Image(), OFX::Private::instanceChangedAction(), OFX::Private::loadAction(), OFX::Private::mainEntryStr(), OFX::mapToContextEnum(), OFX::mapToInstanceChangedReason(), OFX::mapToMessageReplyEnum(), OFX::mapToMessageTypeEnum(), OfxGetPlugin(), OFX::PropertySet::propGetDimension(), OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetInt(), OFX::PropertySet::propGetPointer(), OFX::PropertySet::propGetString(), OFX::PropertySet::propReset(), OFX::PropertySet::propSetDouble(), OFX::PropertySet::propSetInt(), OFX::PropertySet::propSetPointer(), OFX::PropertySet::propSetString(), OFX::Private::retrieveImageEffectPointer(), and OFX::Private::retrieveInteractPointer().
static std::string OFX::Log::gLogFileName (getenv(kLogFileEnvVar)?getenv(kLogFileEnvVar):"ofxTestLog.txt") [static]
the global logfile name
Referenced by open(), and setFileName().
void OFX::Log::indent (void)
Indent it, not MP sane at the moment.
References gIndent.
Referenced by OFX::Private::interactMainEntry(), and OFX::Private::mainEntryStr().
bool OFX::Log::open (void)
Opens the log file, returns whether this was sucessful or not.
References gLogFileName(), and gLogFP.
Referenced by doIndent(), error(), print(), and warning().
void OFX::Log::outdent (void)
Outdent it, not MP sane at the moment.
References gIndent.
Referenced by OFX::Private::interactMainEntry(), and OFX::Private::mainEntryStr().
void OFX::Log::print (const char * format, ...)
Prints to the log file.
References doIndent(), gLogFP, and open().
Referenced by OFX::Private::interactMainEntry(), OFX::Private::mainEntryStr(), OFX::PropertySet::propGetDimension(), OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetInt(), OFX::PropertySet::propGetPointer(), OFX::PropertySet::propGetString(), OFX::PropertySet::propReset(), OFX::PropertySet::propSetDouble(), OFX::PropertySet::propSetInt(), OFX::PropertySet::propSetPointer(), and OFX::PropertySet::propSetString().
void OFX::Log::setFileName (const std::string & value)
Sets the name of the log file.
References gLogFileName().
void OFX::Log::warning (bool condition, const char * format, ...)
Prints to the log file only if the condition is true and prepends a warning notice.
References doIndent(), gLogFP, and open().
Referenced by OFX::Private::checkMainHandles(), and OFX::fetchSuite().
Variable Documentation
int OFX::Log::gIndent = 0 [static]
global indent level, not MP sane
Referenced by doIndent(), indent(), and outdent().
FILE* OFX::Log::gLogFP = 0 [static]
log file
Referenced by close(), doIndent(), error(), open(), print(), and warning().