OFX Support: OFX Namespace Reference
OFX Namespace Reference
Detailed Description
The core 'OFX Support' namespace, used by plugin implementations. All code for these are defined in the common support libraries.
Namespace private to the ofx support library.
OFX namespace.
This file contains code that skins the ofx param suite.
This file contains code that skins the ofx interact suite (for image effects).
This file contains code that skins the ofx effect suite.
The core 'OFX Support' namespace, used by plugin implementations. All code for these are defined in the common support libraries.
Classes
class PropertySet
This class wraps up an OFX property set.
class PluginFactory
class FactoryMainEntryHelper
class PluginFactoryHelper
struct ImageEffectHostDescription
A class that lists all the properties of a host.
class ClipDescriptor
Wraps up a clip.
class ImageEffectDescriptor
Wraps up an effect descriptor, used in the describe actions.
class Image
Wraps up an image.
class Clip
Wraps up a clip instance.
class ImageMemory
Class that skins image memory allocation.
struct RenderArguments
POD struct to pass rendering arguments into ImageEffect::render and OFX::ImageEffect::isIdentity.
struct BeginSequenceRenderArguments
POD struct to pass arguments into OFX::ImageEffect::render.
struct EndSequenceRenderArguments
POD struct to pass arguments into OFX::ImageEffect::beginSequenceRender.
struct RegionOfDefinitionArguments
POD struct to pass arguments into OFX::ImageEffect::getRegionOfDefinition.
struct RegionsOfInterestArguments
POD struct to pass arguments into OFX::ImageEffect::getRegionsOfInterest.
class RegionOfInterestSetter
Class used to set regions of interest on a clip in OFX::ImageEffect::getRegionsOfInterest.
struct FramesNeededArguments
POD struct to pass arguments into OFX::ImageEffect::getFramesNeeded.
class FramesNeededSetter
Class used to set the frames needed to render a single frame of a clip in OFX::ImageEffect::getFramesNeeded.
class ClipPreferencesSetter
Class used to set the clip preferences of the effect.
struct InstanceChangedArgs
POD data structure passing in the instance changed args.
class ImageEffect
Wraps up an effect instance, plugin implementations need to inherit from this.
struct InteractArgs
all image effect interacts have these argumens
struct DrawArgs
struct to pass arguments into OFX::Interact::draw
struct PenArgs
POD to pass arguments into OFX::Interact pen actions.
struct KeyArgs
struct to pass arguments into OFX::Interact key actions
struct FocusArgs
struct to pass arguments into OFX::Interact focus actions
class Interact
Wraps up an OFX interact object for an Image Effect. It won't work for any other plug-in type at present (it would need to be broken into a hierarchy of classes).
class OverlayInteract
an interact for an image effect overlay
class InteractDescriptor
class ParamInteractDescriptor
class ParamInteract
class InteractMainEntry
class DefaultEffectOverlayDescriptor
class DefaultParamInteractDescriptor
class ParamDescriptor
Base class for all param descriptors.
class DummyParamDescriptor
Used to implement dummy parameters for page positioning commands.
class ValueParamDescriptor
Wraps up a value holding param.
class StringParamDescriptor
Wraps up a string param.
class IntParamDescriptor
Wraps up an integer param.
class Int2DParamDescriptor
Wraps up an 2d integer param.
class Int3DParamDescriptor
Wraps up an 3d integer param.
class BaseDoubleParamDescriptor
Common base to all double param types.
class DoubleParamDescriptor
Wraps up a double param.
class Double2DParamDescriptor
Wraps up a 2D double param.
class Double3DParamDescriptor
Wraps up a 3D double param.
class RGBParamDescriptor
Wraps up an RGB colour param.
class RGBAParamDescriptor
Wraps up an RGBA colour param.
class BooleanParamDescriptor
Wraps up a boolean param.
class ChoiceParamDescriptor
Wraps up a choice param.
class GroupParamDescriptor
Wraps up a group param, not much to it really.
class PageParamDescriptor
Wraps up a page param, not much to it really.
class PushButtonParamDescriptor
Wraps up a push button param, not much to it at all.
class CustomParamDescriptor
Wraps up a custom param, haven't added animation support yet.
class ParamSetDescriptor
Describes a set of properties.
class Param
Base class for all param instances.
class ValueParam
Wraps up a value holding param.
class IntParam
Wraps up an integer param.
class Int2DParam
Wraps up an integer param.
class Int3DParam
Wraps up an integer param.
class BaseDoubleParam
Common base to all double param types.
class DoubleParam
Wraps up an doubleeger param.
class Double2DParam
Wraps up an doubleeger param.
class Double3DParam
Wraps up an doubleeger param.
class RGBParam
Wraps up an RGB param.
class RGBAParam
Wraps up an RGB param.
class StringParam
Wraps up a string param.
class ChoiceParam
Wraps up a choice param.
class BooleanParam
Wraps up a boolean param.
class GroupParam
Wraps up a group param.
class PageParam
Wraps up a group param.
class CustomParam
Wraps up a custom param, not animation support yet.
class PushButtonParam
Wraps up a push button param, not much to it at all.
class ParamSet
A set of parameters in a plugin instance.
struct OfxPlugInfo
Namespaces
namespace Exception
namespace for OFX support lib exceptions, all derive from std::exception, calling it
namespace Log
this namespace wraps up logging functionality
namespace Memory
namespace for memory allocation that is done via wrapping the ofx memory suite
namespace Message
namespace MultiThread
Multi thread namespace.
namespace Plugin
The OFX::Plugin namespace. All the functions in here needs to be defined by each plugin that uses the support libs.
namespace Private
OFX::Private namespace, for things private to the support library code here generally calls image effect class members.
namespace Validation
The validation code has its own namespace.
Typedefs
typedef std::vector
< PluginFactory * > PluginFactoryArray
typedef InteractDescriptor EffectOverlayDescriptor
typedef std::map< std::string,
OfxPlugInfo > OfxPlugInfoMap
typedef std::vector< OfxPlugin * > OfxPluginArray
Enumerations
enum PropertyTypeEnum { ePointer, eInt, eString, eDouble }
Enumerates the different types a property can be.
enum InstanceChangeReason { eChangeUserEdit, eChangePluginEdit, eChangeTime }
Enumerates the reasons a plug-in instance may have had one of its values changed.
enum ContextEnum {
eContextNone, eContextGenerator, eContextFilter, eContextTransition,
eContextPaint, eContextGeneral, eContextRetimer
}
Enumerates the contexts a plugin can be used in.
enum BitDepthEnum {
eBitDepthNone, eBitDepthUByte, eBitDepthUShort, eBitDepthFloat,
eBitDepthCustom
}
Enumerates the pixel depths supported.
enum PixelComponentEnum { ePixelComponentNone, ePixelComponentRGBA, ePixelComponentAlpha, ePixelComponentCustom }
Enumerates the component types supported.
enum FieldExtractionEnum { eFieldExtractBoth, eFieldExtractSingle, eFieldExtractDoubled }
Enumerates the ways a fielded image can be extracted from a clip.
enum RenderSafetyEnum { eRenderUnsafe, eRenderInstanceSafe, eRenderFullySafe }
Enumerates the kind of render thread safety a plugin has.
enum FieldEnum { eFieldNone, eFieldBoth, eFieldLower, eFieldUpper }
Enumerates the fields present in an image.
enum PreMultiplicationEnum { eImageOpaque, eImagePreMultiplied, eImageUnPreMultiplied }
enum ParamTypeEnum {
eDummyParam, eStringParam, eIntParam, eInt2DParam,
eInt3DParam, eDoubleParam, eDouble2DParam, eDouble3DParam,
eRGBParam, eRGBAParam, eBooleanParam, eChoiceParam,
eCustomParam, eGroupParam, ePageParam, ePushButtonParam
}
Enumerates the different types of parameter.
enum CacheInvalidationEnum { eCacheInvalidateValueChange, eCacheInvalidateValueChangeToEnd, eCacheInvalidateValueAll }
Enumerates the different types of cache invalidation.
enum KeySearchEnum { eKeySearchBackwards, eKeySearchNear, eKeySearchForwards }
Enumerates how we search for keys in an animating parameter.
enum StringTypeEnum {
eStringTypeSingleLine, eStringTypeMultiLine, eStringTypeFilePath, eStringTypeDirectoryPath,
eStringTypeLabel
}
Enumerates the differing types of string params.
enum DoubleTypeEnum {
eDoubleTypePlain, eDoubleTypeAngle, eDoubleTypeScale, eDoubleTypeTime,
eDoubleTypeAbsoluteTime, eDoubleTypeNormalisedX, eDoubleTypeNormalisedY, eDoubleTypeNormalisedXAbsolute,
eDoubleTypeNormalisedYAbsolute, eDoubleTypeNormalisedXY, eDoubleTypeNormalisedXYAbsolute
}
Enumerates the differing types of double params.
Functions
char * mapStatusToString (OfxStatus stat)
maps a status to a string for debugging purposes, note a c-str for printf
void throwSuiteStatusException (OfxStatus stat) throw (OFX::Exception::Suite, std::bad_alloc)
Throws an OFX::Exception::Suite depending on the status flag passed in.
void throwHostMissingSuiteException (std::string name) throw (OFX::Exception::Suite)
void * fetchSuite (char *suiteName, int suiteVersion, bool optional=false)
Fetch's a suite from the host and logs errors.
ImageEffectHostDescription * getImageEffectHostDescription ()
retrieve the host description
const char * mapParamTypeEnumToString (ParamTypeEnum v)
turns a ParamTypeEnum into the char * that raw OFX uses
ContextEnum mapToContextEnum (const std::string &s) throw (std::invalid_argument)
map a std::string to a context
const char * mapToMessageTypeEnum (OFX::Message::MessageTypeEnum type)
OFX::Message::MessageReplyEnum mapToMessageReplyEnum (OfxStatus stat)
InstanceChangeReason mapToInstanceChangedReason (const std::string &s) throw (std::invalid_argument)
map a std::string to a context
static BitDepthEnum mapStrToBitDepthEnum (const std::string &str) throw (std::invalid_argument)
turns a bit depth string into and enum
static PixelComponentEnum mapStrToPixelComponentEnum (const std::string &str) throw (std::invalid_argument)
turns a pixel component string into and enum
static PreMultiplicationEnum mapStrToPreMultiplicationEnum (const std::string &str) throw (std::invalid_argument)
turns a premultiplication string into and enum
FieldEnum mapStrToFieldEnum (const std::string &str) throw (std::invalid_argument)
turns a field string into and enum
static OfxPointD getPixelScale (const PropertySet &props)
fetch a pixel scale out of the property set
static OfxPointD getRenderScale (const PropertySet &props)
fetch a render scale out of the property set
static OfxRGBColourD getBackgroundColour (const PropertySet &props)
fetch a background colour out of the property set
static ImageEffect * retrieveEffectFromInteractHandle (OfxInteractHandle handle)
retrieves the image effect pointer from the interact handle
bool isEqual (const char *t1, const char *t2)
ParamTypeEnum mapParamTypeStringToEnum (const char *v)
void throwPropertyException (OfxStatus stat, const std::string &propName) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
Variables
OFX::PluginFactoryArray plugIDs
OfxPlugInfoMap plugInfoMap
OfxPluginArray ofxPlugs
ImageEffectHostDescription gHostDescription
the global host description
bool gHostDescriptionHasInit = false
Typedef Documentation
typedef InteractDescriptor OFX::EffectOverlayDescriptor
typedef std::vector<OfxPlugin*> OFX::OfxPluginArray
typedef std::map<std::string, OfxPlugInfo> OFX::OfxPlugInfoMap
typedef std::vector<PluginFactory*> OFX::PluginFactoryArray
Enumeration Type Documentation
enum OFX::BitDepthEnum
Enumerates the pixel depths supported.
Enumerator:
eBitDepthNone bit depth that indicates no data is present
eBitDepthUByte
eBitDepthUShort
eBitDepthFloat
eBitDepthCustom some non standard bit depth
enum OFX::CacheInvalidationEnum
Enumerates the different types of cache invalidation.
Enumerator:
eCacheInvalidateValueChange
eCacheInvalidateValueChangeToEnd
eCacheInvalidateValueAll
enum OFX::ContextEnum
Enumerates the contexts a plugin can be used in.
Enumerator:
eContextNone
eContextGenerator
eContextFilter
eContextTransition
eContextPaint
eContextGeneral
eContextRetimer
enum OFX::DoubleTypeEnum
Enumerates the differing types of double params.
Enumerator:
eDoubleTypePlain
eDoubleTypeAngle
eDoubleTypeScale
eDoubleTypeTime
eDoubleTypeAbsoluteTime
eDoubleTypeNormalisedX
eDoubleTypeNormalisedY
eDoubleTypeNormalisedXAbsolute
eDoubleTypeNormalisedYAbsolute
eDoubleTypeNormalisedXY
eDoubleTypeNormalisedXYAbsolute
enum OFX::FieldEnum
Enumerates the fields present in an image.
Enumerator:
eFieldNone unfielded image
eFieldBoth fielded image with both fields present
eFieldLower only the spatially lower field is present
eFieldUpper only the spatially upper field is present
enum OFX::FieldExtractionEnum
Enumerates the ways a fielded image can be extracted from a clip.
Enumerator:
eFieldExtractBoth extract both fields
eFieldExtractSingle extracts a single field, so you have a half height image
eFieldExtractDoubled extracts a single field, but doubles up the field, so you have a full height image
enum OFX::InstanceChangeReason
Enumerates the reasons a plug-in instance may have had one of its values changed.
Enumerator:
eChangeUserEdit A user actively editted something in the plugin, eg: changed the value of an integer param on an interface.
eChangePluginEdit The plugin's own code changed something in the instance, eg: a callback on on param settting the value of another.
eChangeTime The current value of a parameter has changed because the param animates and the current time has changed.
enum OFX::KeySearchEnum
Enumerates how we search for keys in an animating parameter.
Enumerator:
eKeySearchBackwards
eKeySearchNear
eKeySearchForwards
enum OFX::ParamTypeEnum
Enumerates the different types of parameter.
Enumerator:
eDummyParam
eStringParam
eIntParam
eInt2DParam
eInt3DParam
eDoubleParam
eDouble2DParam
eDouble3DParam
eRGBParam
eRGBAParam
eBooleanParam
eChoiceParam
eCustomParam
eGroupParam
ePageParam
ePushButtonParam
enum OFX::PixelComponentEnum
Enumerates the component types supported.
Enumerator:
ePixelComponentNone
ePixelComponentRGBA
ePixelComponentAlpha
ePixelComponentCustom some non standard pixel type
enum OFX::PreMultiplicationEnum
Enumerator:
eImageOpaque the image is opaque and so has no premultiplication state
eImagePreMultiplied the image is premultiplied by it's alpha
eImageUnPreMultiplied the image is unpremultiplied
enum OFX::PropertyTypeEnum
Enumerates the different types a property can be.
Enumerator:
ePointer
eInt
eString
eDouble
enum OFX::RenderSafetyEnum
Enumerates the kind of render thread safety a plugin has.
Enumerator:
eRenderUnsafe can only render a single instance at any one time
eRenderInstanceSafe can call a single render on an instance, but can render multiple instances simultaneously
eRenderFullySafe can call render any number of times on an instance, and render multiple instances simultaneously
enum OFX::StringTypeEnum
Enumerates the differing types of string params.
Enumerator:
eStringTypeSingleLine
eStringTypeMultiLine
eStringTypeFilePath
eStringTypeDirectoryPath
eStringTypeLabel
Function Documentation
void * OFX::fetchSuite (char * suiteName, int suiteVersion, bool optional = false)
Fetch's a suite from the host and logs errors.
All the standard suites are fetched by the support code, you should use this to fetch any extra non-standard suites.
References OFX::Log::error(), OFX::Private::gHost, and OFX::Log::warning().
Referenced by OFX::Private::loadAction().
static OfxRGBColourD OFX::getBackgroundColour (const PropertySet & props) [static]
fetch a background colour out of the property set
References OfxRGBColourD::b, OfxRGBColourD::g, OFX::PropertySet::propGetDouble(), and OfxRGBColourD::r.
Referenced by OFX::DrawArgs::DrawArgs(), OFX::FocusArgs::FocusArgs(), and OFX::Interact::getBackgroundColour().
ImageEffectHostDescription * OFX::getImageEffectHostDescription ()
retrieve the host description
References gHostDescription, and gHostDescriptionHasInit.
Referenced by OFX::Validation::initialise().
static OfxPointD OFX::getPixelScale (const PropertySet & props) [static]
fetch a pixel scale out of the property set
References OFX::PropertySet::propGetDouble().
Referenced by OFX::DrawArgs::DrawArgs(), OFX::FocusArgs::FocusArgs(), and OFX::PenArgs::PenArgs().
static OfxPointD OFX::getRenderScale (const PropertySet & props) [static]
fetch a render scale out of the property set
References OFX::PropertySet::propGetDouble().
Referenced by OFX::InteractArgs::InteractArgs(), and OFX::KeyArgs::KeyArgs().
bool OFX::isEqual (const char * t1, const char * t2)
Referenced by mapParamTypeStringToEnum().
const char * OFX::mapParamTypeEnumToString (ParamTypeEnum v)
turns a ParamTypeEnum into the char * that raw OFX uses
References eBooleanParam, eChoiceParam, eCustomParam, eDouble2DParam, eDouble3DParam, eDoubleParam, eGroupParam, eInt2DParam, eInt3DParam, eIntParam, ePageParam, ePushButtonParam, eRGBAParam, eRGBParam, and eStringParam.
Referenced by OFX::ParamSetDescriptor::defineRawParam().
ParamTypeEnum OFX::mapParamTypeStringToEnum (const char * v)
References eBooleanParam, eChoiceParam, eCustomParam, eDouble2DParam, eDouble3DParam, eDoubleParam, eGroupParam, eInt2DParam, eInt3DParam, eIntParam, ePageParam, ePushButtonParam, eRGBAParam, eRGBParam, eStringParam, and isEqual().
Referenced by OFX::ParamSet::getParam(), and OFX::ParamSet::getParamType().
char * OFX::mapStatusToString (OfxStatus stat)
maps a status to a string for debugging purposes, note a c-str for printf
maps status to a string
Referenced by OFX::PropertySet::propGetDimension(), OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetInt(), OFX::PropertySet::propGetPointer(), OFX::PropertySet::propGetString(), OFX::PropertySet::propReset(), OFX::PropertySet::propSetDouble(), OFX::PropertySet::propSetInt(), OFX::PropertySet::propSetPointer(), OFX::PropertySet::propSetString(), and OFX::Exception::Suite::what().
static BitDepthEnum OFX::mapStrToBitDepthEnum (const std::string & str) throw (std::invalid_argument) [static]
turns a bit depth string into and enum
References eBitDepthCustom, eBitDepthFloat, eBitDepthNone, eBitDepthUByte, and eBitDepthUShort.
Referenced by OFX::Private::fetchHostDescription(), OFX::Clip::getPixelDepth(), OFX::Clip::getUnmappedPixelDepth(), and OFX::Image::Image().
FieldEnum OFX::mapStrToFieldEnum (const std::string & str) throw (std::invalid_argument)
turns a field string into and enum
References eFieldBoth, eFieldLower, eFieldNone, and eFieldUpper.
Referenced by OFX::Clip::getFieldOrder(), and OFX::Private::getRenderActionArguments().
static PixelComponentEnum OFX::mapStrToPixelComponentEnum (const std::string & str) throw (std::invalid_argument) [static]
turns a pixel component string into and enum
References ePixelComponentAlpha, ePixelComponentCustom, ePixelComponentNone, and ePixelComponentRGBA.
Referenced by OFX::Private::fetchHostDescription(), OFX::Clip::getPixelComponents(), OFX::Clip::getUnmappedPixelComponents(), and OFX::Image::Image().
static PreMultiplicationEnum OFX::mapStrToPreMultiplicationEnum (const std::string & str) throw (std::invalid_argument) [static]
turns a premultiplication string into and enum
References eImageOpaque, eImagePreMultiplied, and eImageUnPreMultiplied.
Referenced by OFX::Clip::getPreMultiplication(), and OFX::Image::Image().
ContextEnum OFX::mapToContextEnum (const std::string & s) throw (std::invalid_argument)
map a std::string to a context
map a std::string to a context enum
References eContextFilter, eContextGeneral, eContextGenerator, eContextPaint, eContextRetimer, eContextTransition, and OFX::Log::error().
Referenced by OFX::Private::fetchHostDescription(), OFX::ImageEffect::ImageEffect(), and OFX::Private::mainEntryStr().
InstanceChangeReason OFX::mapToInstanceChangedReason (const std::string & s) throw (std::invalid_argument)
map a std::string to a context
References eChangePluginEdit, eChangeTime, eChangeUserEdit, and OFX::Log::error().
Referenced by OFX::Private::beginInstanceChangedAction(), OFX::Private::endInstanceChangedAction(), and OFX::Private::instanceChangedAction().
OFX::Message::MessageReplyEnum OFX::mapToMessageReplyEnum (OfxStatus stat)
References OFX::Message::eMessageReplyFailed, OFX::Message::eMessageReplyNo, OFX::Message::eMessageReplyOK, OFX::Message::eMessageReplyYes, and OFX::Log::error().
Referenced by OFX::ImageEffect::sendMessage().
const char* OFX::mapToMessageTypeEnum (OFX::Message::MessageTypeEnum type)
References OFX::Message::eMessageError, OFX::Message::eMessageFatal, OFX::Message::eMessageLog, OFX::Message::eMessageMessage, OFX::Message::eMessageQuestion, and OFX::Log::error().
Referenced by OFX::ImageEffect::sendMessage().
static ImageEffect* OFX::retrieveEffectFromInteractHandle (OfxInteractHandle handle) [static]
retrieves the image effect pointer from the interact handle
References OFX::Private::gInteractSuite, OFX::PropertySet::propGetPointer(), OFX::Private::retrieveImageEffectPointer(), and throwSuiteStatusException().
Referenced by OFX::Interact::Interact(), and OFX::Private::interactMainEntry().
void OFX::throwHostMissingSuiteException (std::string name) throw (OFX::Exception::Suite)
Referenced by OFX::ValueParam::deleteAllKeys(), OFX::ValueParam::deleteKeyAtTime(), OFX::Double3DParam::differentiate(), OFX::Double2DParam::differentiate(), OFX::DoubleParam::differentiate(), OFX::ValueParam::getKeyIndex(), OFX::ValueParam::getKeyTime(), OFX::ValueParam::getNumKeys(), OFX::Double3DParam::integrate(), OFX::Double2DParam::integrate(), OFX::DoubleParam::integrate(), OFX::ImageEffect::sendMessage(), OFX::CustomParam::setValueAtTime(), OFX::ChoiceParam::setValueAtTime(), OFX::BooleanParam::setValueAtTime(), OFX::StringParam::setValueAtTime(), OFX::RGBAParam::setValueAtTime(), OFX::RGBParam::setValueAtTime(), OFX::Double3DParam::setValueAtTime(), OFX::Double2DParam::setValueAtTime(), OFX::DoubleParam::setValueAtTime(), OFX::Int3DParam::setValueAtTime(), OFX::Int2DParam::setValueAtTime(), and OFX::IntParam::setValueAtTime().
void OFX::throwPropertyException (OfxStatus stat, const std::string & propName) throw (std::bad_alloc, OFX::Exception::PropertyUnknownToHost, OFX::Exception::PropertyValueIllegalToHost, OFX::Exception::Suite)
References OFX::PropertySet::getThrowOnUnsupportedProperties(), and throwSuiteStatusException().
Referenced by OFX::PropertySet::propGetDimension(), OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetInt(), OFX::PropertySet::propGetPointer(), OFX::PropertySet::propGetString(), OFX::PropertySet::propReset(), OFX::PropertySet::propSetDouble(), OFX::PropertySet::propSetInt(), OFX::PropertySet::propSetPointer(), and OFX::PropertySet::propSetString().
void OFX::throwSuiteStatusException (OfxStatus stat) throw (OFX::Exception::Suite, std::bad_alloc)
Throws an OFX::Exception::Suite depending on the status flag passed in.
Throws an OFX::Exception depending on the status flag passed in.
Referenced by OFX::Private::checkMainHandles(), OFX::ParamSetDescriptor::defineRawParam(), OFX::ValueParam::deleteAllKeys(), OFX::ValueParam::deleteKeyAtTime(), OFX::Double3DParam::differentiate(), OFX::Double2DParam::differentiate(), OFX::DoubleParam::differentiate(), OFX::ImageEffect::fetchClip(), OFX::Private::fetchEffectProps(), OFX::Clip::fetchImage(), OFX::ValueParam::getKeyIndex(), OFX::ValueParam::getKeyTime(), OFX::ValueParam::getNumKeys(), OFX::ParamSet::getParam(), OFX::ParamSet::getParamType(), OFX::Clip::getRegionOfDefinition(), OFX::CustomParam::getValue(), OFX::ChoiceParam::getValue(), OFX::BooleanParam::getValue(), OFX::StringParam::getValue(), OFX::RGBAParam::getValue(), OFX::RGBParam::getValue(), OFX::Double3DParam::getValue(), OFX::Double2DParam::getValue(), OFX::DoubleParam::getValue(), OFX::Int3DParam::getValue(), OFX::Int2DParam::getValue(), OFX::IntParam::getValue(), OFX::CustomParam::getValueAtTime(), OFX::ChoiceParam::getValueAtTime(), OFX::BooleanParam::getValueAtTime(), OFX::StringParam::getValueAtTime(), OFX::RGBAParam::getValueAtTime(), OFX::RGBParam::getValueAtTime(), OFX::Double3DParam::getValueAtTime(), OFX::Double2DParam::getValueAtTime(), OFX::DoubleParam::getValueAtTime(), OFX::Int3DParam::getValueAtTime(), OFX::Int2DParam::getValueAtTime(), OFX::IntParam::getValueAtTime(), OFX::ImageEffect::ImageEffect(), OFX::ImageEffectDescriptor::ImageEffectDescriptor(), OFX::ImageMemory::ImageMemory(), OFX::Double3DParam::integrate(), OFX::Double2DParam::integrate(), OFX::DoubleParam::integrate(), OFX::Interact::Interact(), OFX::Private::interactMainEntry(), OFX::MultiThread::Mutex::lock(), OFX::ImageMemory::lock(), OFX::MultiThread::Processor::multiThread(), OFX::MultiThread::Mutex::Mutex(), OFX::Param::Param(), OFX::Interact::requestRedraw(), retrieveEffectFromInteractHandle(), OFX::Private::retrieveImageEffectPointer(), OFX::Private::retrieveInteractPointer(), OFX::ParamSet::setParamSetHandle(), OFX::ParamSetDescriptor::setParamSetHandle(), OFX::CustomParam::setValue(), OFX::ChoiceParam::setValue(), OFX::BooleanParam::setValue(), OFX::StringParam::setValue(), OFX::RGBAParam::setValue(), OFX::RGBParam::setValue(), OFX::Double3DParam::setValue(), OFX::Double2DParam::setValue(), OFX::DoubleParam::setValue(), OFX::Int3DParam::setValue(), OFX::Int2DParam::setValue(), OFX::IntParam::setValue(), OFX::CustomParam::setValueAtTime(), OFX::ChoiceParam::setValueAtTime(), OFX::BooleanParam::setValueAtTime(), OFX::StringParam::setValueAtTime(), OFX::RGBAParam::setValueAtTime(), OFX::RGBParam::setValueAtTime(), OFX::Double3DParam::setValueAtTime(), OFX::Double2DParam::setValueAtTime(), OFX::DoubleParam::setValueAtTime(), OFX::Int3DParam::setValueAtTime(), OFX::Int2DParam::setValueAtTime(), OFX::IntParam::setValueAtTime(), OFX::Interact::swapBuffers(), throwPropertyException(), and OFX::MultiThread::Mutex::unlock().
Variable Documentation
ImageEffectHostDescription OFX::gHostDescription
the global host description
Referenced by OFX::Private::fetchHostDescription(), getImageEffectHostDescription(), OFX::Private::loadAction(), and OFX::ImageEffectDescriptor::setOverlayInteractDescriptor().
bool OFX::gHostDescriptionHasInit = false
Referenced by OFX::Private::fetchHostDescription(), and getImageEffectHostDescription().
OfxPluginArray OFX::ofxPlugs
Referenced by init(), OfxGetPlugin(), and OFX::Private::unloadAction().
OFX::PluginFactoryArray OFX::plugIDs
Referenced by init(), OfxGetNumberOfPlugins(), and OfxGetPlugin().
OfxPlugInfoMap OFX::plugInfoMap
Referenced by init(), OFX::Private::mainEntryStr(), OfxGetPlugin(), and OFX::Private::unloadAction().