OFX Support: ofxsImageEffect.cpp File Reference
ofxsImageEffect.cpp File Reference
#include "ofxsSupportPrivate.h"
#include <algorithm>
#include <iostream>
#include <sstream>
Namespaces
namespace OFX
namespace OFX::Private
namespace OFX::Plugin
Classes
struct OFX::OfxPlugInfo
Typedefs
typedef std::map< std::string,
OfxPlugInfo > OFX::OfxPlugInfoMap
typedef std::vector< OfxPlugin * > OFX::OfxPluginArray
Functions
ImageEffectHostDescription * OFX::getImageEffectHostDescription ()
retrieve the host description
ContextEnum OFX::mapToContextEnum (const std::string &s) throw (std::invalid_argument)
map a std::string to a context
const char * OFX::mapToMessageTypeEnum (OFX::Message::MessageTypeEnum type)
OFX::Message::MessageReplyEnum OFX::mapToMessageReplyEnum (OfxStatus stat)
InstanceChangeReason OFX::mapToInstanceChangedReason (const std::string &s) throw (std::invalid_argument)
map a std::string to a context
static BitDepthEnum OFX::mapStrToBitDepthEnum (const std::string &str) throw (std::invalid_argument)
turns a bit depth string into and enum
static PixelComponentEnum OFX::mapStrToPixelComponentEnum (const std::string &str) throw (std::invalid_argument)
turns a pixel component string into and enum
static PreMultiplicationEnum OFX::mapStrToPreMultiplicationEnum (const std::string &str) throw (std::invalid_argument)
turns a premultiplication string into and enum
FieldEnum OFX::mapStrToFieldEnum (const std::string &str) throw (std::invalid_argument)
turns a field string into and enum
void OFX::Private::fetchHostDescription (OfxHost *host)
Creates the global host description and sets its properties.
OFX::PropertySet OFX::Private::fetchEffectProps (OfxImageEffectHandle handle)
fetch the effect property set from the ImageEffectHandle
void OFX::Private::loadAction (void)
Library side load action, this fetches all the suite pointers.
void OFX::Private::unloadAction (const char *id)
Library side unload action, this fetches all the suite pointers.
ImageEffect * OFX::Private::retrieveImageEffectPointer (OfxImageEffectHandle handle)
fetches our pointer out of the props on the handle
void OFX::Private::checkMainHandles (const std::string &action, const void *handle, OfxPropertySetHandle inArgsHandle, OfxPropertySetHandle outArgsHandle, bool handleCanBeNull, bool inArgsCanBeNull, bool outArgsCanBeNull)
Checks the handles passed into the plugin's main entry point.
static void OFX::Private::getRenderActionArguments (RenderArguments &args, OFX::PropertySet inArgs)
Fetches the arguments used in a render action 'inargs' property set into a POD struct.
void OFX::Private::renderAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side render action, fetches relevant properties and calls the client code.
void OFX::Private::beginSequenceRenderAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side render begin sequence render action, fetches relevant properties and calls the client code.
void OFX::Private::endSequenceRenderAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side render begin sequence render action, fetches relevant properties and calls the client code.
bool OFX::Private::isIdentityAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet &outArgs)
Library side render begin sequence render action, fetches relevant properties and calls the client code.
bool OFX::Private::regionOfDefinitionAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet &outArgs)
Library side get region of definition function.
bool OFX::Private::regionsOfInterestAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet &outArgs, const char *plugname)
Library side get regions of interest function.
bool OFX::Private::framesNeededAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs, OFX::PropertySet &outArgs, const char *plugname)
Library side frames needed action.
bool OFX::Private::getTimeDomainAction (OfxImageEffectHandle handle, OFX::PropertySet &outArgs)
Library side get regions of interest function.
bool OFX::Private::clipPreferencesAction (OfxImageEffectHandle handle, OFX::PropertySet &outArgs, const char *plugname)
Library side get regions of interest function.
void OFX::Private::beginInstanceChangedAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side begin instance changed action.
void OFX::Private::instanceChangedAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side instance changed action.
void OFX::Private::endInstanceChangedAction (OfxImageEffectHandle handle, OFX::PropertySet inArgs)
Library side end instance changed action.
OfxStatus OFX::Private::mainEntryStr (const char *actionRaw, const void *handleRaw, OfxPropertySetHandle inArgsRaw, OfxPropertySetHandle outArgsRaw, const char *plugname)
The main entry point for the plugin.
void OFX::Private::setHost (OfxHost *host)
The plugin function that gets passed the host structure.
void * OFX::fetchSuite (char *suiteName, int suiteVersion, bool optional=false)
Fetch's a suite from the host and logs errors.
void OFX::Plugin::getPluginIDs (OFX::PluginFactoryArray &ids)
OFX::OfxPlugInfo generatePlugInfo (OFX::PluginFactory *factory, std::string &newID)
void init ()
OfxExport int OfxGetNumberOfPlugins (void)
, mandated function returning the number of plugins, which is always 1
OfxExport OfxPlugin * OfxGetPlugin (int nth)
, mandated function returning the nth plugin
Variables
OFX::PluginFactoryArray OFX::plugIDs
OfxPlugInfoMap OFX::plugInfoMap
OfxPluginArray OFX::ofxPlugs
ImageEffectHostDescription OFX::gHostDescription
the global host description
bool OFX::gHostDescriptionHasInit = false
OfxHost * OFX::Private::gHost = 0
Pointer to the host.
OfxImageEffectSuiteV1 * OFX::Private::gEffectSuite = 0
Pointer to the effect suite.
OfxPropertySuiteV1 * OFX::Private::gPropSuite = 0
Pointer to the property suite.
OfxInteractSuiteV1 * OFX::Private::gInteractSuite = 0
Pointer to the interact suite.
OfxParameterSuiteV1 * OFX::Private::gParamSuite = 0
Pointer to the parameter suite.
OfxMemorySuiteV1 * OFX::Private::gMemorySuite = 0
Pointer to the general memory suite.
OfxMultiThreadSuiteV1 * OFX::Private::gThreadSuite = 0
Pointer to the threading suite.
OfxMessageSuiteV1 * OFX::Private::gMessageSuite = 0
Pointer to the message suite.
OfxProgressSuiteV1 * OFX::Private::gProgressSuite = 0
Pointer to the optional progress suite.
OfxTimeLineSuiteV1 * OFX::Private::gTimeLineSuite = 0
Pointer to the optional progress suite.
EffectDescriptorMap OFX::Private::gEffectDescriptors
int OFX::Private::gLoadCount = 0
Keeps count of how many times load/unload have been called.
bool gHasInit = false
Function Documentation
OFX::OfxPlugInfo generatePlugInfo (OFX::PluginFactory * factory, std::string & newID)
References OFX::PluginFactory::getID(), OFX::PluginFactory::getMainEntry(), OFX::PluginFactory::getMajorVersion(), OFX::PluginFactory::getMinorVersion(), OFX::PluginFactory::getUID(), and OFX::Private::setHost().
Referenced by init(), and OfxGetPlugin().
void init ()
References OFX::OfxPlugInfo::_plug, generatePlugInfo(), OFX::Plugin::getPluginIDs(), OFX::ofxPlugs, OFX::plugIDs, and OFX::plugInfoMap.
Referenced by OfxGetNumberOfPlugins(), and OfxGetPlugin().
OfxExport int OfxGetNumberOfPlugins (void)
, mandated function returning the number of plugins, which is always 1
References init(), and OFX::plugIDs.
OfxExport OfxPlugin* OfxGetPlugin (int nth)
, mandated function returning the nth plugin
We call the plugin side defined OFX::Plugin::getPluginID function to find out what to set.
References OFX::OfxPlugInfo::_plug, OFX::Log::error(), generatePlugInfo(), init(), OFX::ofxPlugs, OFX::plugIDs, and OFX::plugInfoMap.
Variable Documentation
bool gHasInit = false