OFX Support: OFX::KeyArgs Struct Reference
OFX::KeyArgs Struct Reference
#include <ofxsInteract.h>
Detailed Description
struct to pass arguments into OFX::Interact key actions
Note
some keys cannot be represented as UTF8 strings (eg: the key pad page down key kOfxKey_KP_Page_Up), in which case the key string will be set to "".
some UTF8 symbols (generally non-English language ones) cannot be represented by one of the keySymbols, in which case the UTF8 string will be set to some non empty value, but the keySymbol will be set to kOfxKey_Unknown.
in no case will keyString be set to "" and keySymbol be set to kOfxKey_Unknown.
Public Member Functions
KeyArgs (const PropertySet &props)
ctor
Public Attributes
int keySymbol
The key represented as one of the entries in ofxKeySyms.h, see note in OFX::KeyArgs.
std::string keyString
That key as a UTF8 string, see note in OFX::KeyArgs.
Constructor & Destructor Documentation
OFX::KeyArgs::KeyArgs (const PropertySet & props)
ctor
References OFX::getRenderScale(), keyString, OFX::PropertySet::propGetDouble(), OFX::PropertySet::propGetString(), OFX::InteractArgs::renderScale, and OFX::InteractArgs::time.
Member Data Documentation
int OFX::KeyArgs::keySymbol
The key represented as one of the entries in ofxKeySyms.h, see note in OFX::KeyArgs.
std::string OFX::KeyArgs::keyString
That key as a UTF8 string, see note in OFX::KeyArgs.
Referenced by KeyArgs().
The documentation for this struct was generated from the following files:
ofxsInteract.h
ofxsInteract.cpp